export const demoRedundancyRules = [
      {
        'planningRule.name': '关键链路冗余优先基于业务连续性确定',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '链路冗余',
        'planningRule.trigger': '链路中断会直接影响关键业务连续性。',
        'planningRule.scene': '关键控制链路 / 核心上联 / 跨区域主干',
        'planningRule.recommend': '优先按业务连续性要求决定是否采用链路、设备或协议层冗余。',
        'planningRule.avoid': '避免不分主次地全网堆叠冗余。',
        'planningRule.reason': '冗余应服务于关键业务，而非为了形式完整。',
        'planningRule.scope': '适用于关键主干与关键控制对象。',
        'planningRule.alternative': '若业务可中断，可采用快速恢复而非双活冗余。',
        'planningRule.example': '控制区核心上联采用双链路或环网冗余。',
        'planningRule.note': '与拓扑规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '主干冗余优先集中在关键层级',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '层级冗余',
        'planningRule.trigger': '网络包含核心、汇聚、接入等多个层级，且业务重要性不同。',
        'planningRule.scene': '分层网络 / 多层主干网络',
        'planningRule.recommend': '优先将冗余能力集中在核心层和关键汇聚层。',
        'planningRule.avoid': '避免在低价值层级盲目铺满冗余。',
        'planningRule.reason': '关键层级的冗余收益最大。',
        'planningRule.scope': '适用于分层网络主干设计。',
        'planningRule.alternative': '小规模场景可采用单层快速恢复设计。',
        'planningRule.example': '核心双机、关键汇聚双上联。',
        'planningRule.note': '与分层规则联动。',
      },
      {
        'planningRule.name': '冗余模式优先匹配维护能力',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '冗余模式',
        'planningRule.trigger': '存在多种冗余协议或模式可选，但团队运维能力差异明显。',
        'planningRule.scene': '环网协议 / 双活 / 链路保护 / 协议冗余',
        'planningRule.recommend': '优先采用团队能理解、能维护、能排障的冗余模式。',
        'planningRule.avoid': '避免选择运维团队无法掌握的复杂冗余机制。',
        'planningRule.reason': '无法维护的冗余会变成新的风险源。',
        'planningRule.scope': '适用于冗余模式有多种选择的项目。',
        'planningRule.alternative': '可先采用简单冗余，再逐步演进。',
        'planningRule.example': '优先简化环网或双链路，而非复杂双活结构。',
        'planningRule.note': '与稳定性规则和技术选择规则联动。',
      },
    ];
