export const demoSecurityRules = [
      {
        'planningRule.name': '远程接入优先先定控制再定连通',
        'planningRule.domain': '安全设计',
        'planningRule.category': '远程接入',
        'planningRule.trigger': '项目涉及第三方远程维护、总部远程监控或跨域调试。',
        'planningRule.scene': '远程运维 / 第三方维护 / 总部监控',
        'planningRule.recommend': '先确定认证、审批、审计和访问边界，再组织连通方式。',
        'planningRule.avoid': '避免先打通远程链路再补安全控制。',
        'planningRule.reason': '安全控制缺位会直接放大远程接入风险。',
        'planningRule.scope': '适用于所有涉及外部访问的工业网络场景。',
        'planningRule.alternative': '若无远程维护需求，可简化为本地运维边界。',
        'planningRule.example': '第三方维护统一经 DMZ、堡垒机和审批审计链路接入。',
        'planningRule.note': '应与通道规则和边界互联规则配套使用。',
      },
      {
        'planningRule.name': '关键区域优先最小权限访问',
        'planningRule.domain': '安全设计',
        'planningRule.category': '访问控制',
        'planningRule.trigger': '区域内对象对业务连续性或安全性影响高。',
        'planningRule.scene': '控制区 / 关键服务区 / 核心边界',
        'planningRule.recommend': '优先采用最小权限访问策略，限定对象、方向和协议。',
        'planningRule.avoid': '避免为图省事放开整区访问。',
        'planningRule.reason': '关键区域访问面越大，风险越高。',
        'planningRule.scope': '适用于关键区域与高价值对象。',
        'planningRule.alternative': '在短期调试阶段可临时放宽，但需限时与留痕。',
        'planningRule.example': '仅允许历史库单向读取控制区数据。',
        'planningRule.note': '需与边界互联和通道规则一并落地。',
      },
      {
        'planningRule.name': '安全设计优先结合运维可执行性',
        'planningRule.domain': '安全设计',
        'planningRule.category': '安全实施',
        'planningRule.trigger': '项目安全要求高，但现场运维能力有限。',
        'planningRule.scene': '传统工厂 / 运维资源有限 / 人员能力不均衡',
        'planningRule.recommend': '优先采用运维可执行、可长期坚持的安全控制策略。',
        'planningRule.avoid': '避免设计出纸面完美但现场无法长期执行的复杂安全方案。',
        'planningRule.reason': '不能长期执行的安全策略最终会失效。',
        'planningRule.scope': '适用于安全与运维平衡要求高的项目。',
        'planningRule.alternative': '可分阶段实施，先落关键控制点，再逐步提升。',
        'planningRule.example': '先落审批、堡垒机、白名单，再逐步细化分区策略。',
        'planningRule.note': '与部署规则、场景规则联动。',
      },
    ];
