export const demoAddressRules = [
      {
        'planningRule.name': '地址规划优先按区域与用途分段',
        'planningRule.domain': '地址规划',
        'planningRule.category': '分段设计',
        'planningRule.trigger': '网络中存在多个区域、多个对象类型或不同运维需求。',
        'planningRule.scene': '多区域厂区 / 多系统并行 / 长周期运维项目',
        'planningRule.recommend': '按区域、用途、对象类型组织地址分段，并预留扩展余量。',
        'planningRule.avoid': '避免全网混用连续地址，导致边界和用途难以识别。',
        'planningRule.reason': '分段规则清晰有助于实施、运维和扩容。',
        'planningRule.scope': '适用于需要长期维护和持续扩展的网络。',
        'planningRule.alternative': '在极小规模场景下，可先简化分段，但应保留演进空间。',
        'planningRule.example': '按控制区、监控区、维护区分别规划 VLAN 与网段。',
        'planningRule.note': '应与区域规则和边界规则协同。',
      },
      {
        'planningRule.name': '关键对象优先固定地址规划',
        'planningRule.domain': '地址规划',
        'planningRule.category': '地址分配',
        'planningRule.trigger': '对象承担关键控制、关键服务或关键边界职责。',
        'planningRule.scene': 'PLC / HMI / 历史库 / 边界设备 / 核心交换机',
        'planningRule.recommend': '优先为关键对象规划固定地址，并明确用途与管理归属。',
        'planningRule.avoid': '避免关键对象长期依赖动态分配地址。',
        'planningRule.reason': '固定地址便于审计、维护、策略绑定和故障定位。',
        'planningRule.scope': '适用于关键业务对象与关键网络节点。',
        'planningRule.alternative': '普通终端可在受控前提下采用 DHCP。',
        'planningRule.example': 'PLC、服务器、防火墙使用固定地址。',
        'planningRule.note': '应与接入规则和安全规则联动。',
      },
      {
        'planningRule.name': '地址预留优先按扩展方向规划',
        'planningRule.domain': '地址规划',
        'planningRule.category': '扩展预留',
        'planningRule.trigger': '项目存在后续扩产、扩线、扩系统预期。',
        'planningRule.scene': '中长期建设 / 分阶段交付 / 平台型项目',
        'planningRule.recommend': '优先按区域扩展方向和对象增长方式预留地址空间。',
        'planningRule.avoid': '避免只按当前数量刚性切分，导致后期重编址。',
        'planningRule.reason': '地址预留是长期可维护性的关键基础。',
        'planningRule.scope': '适用于有明显扩展预期的项目。',
        'planningRule.alternative': '若项目生命周期短且边界固定，可适度简化预留。',
        'planningRule.example': '为未来新增产线预留独立地址段。',
        'planningRule.note': '应与场景规则和部署规则协同。',
      },
    ];
