export const demoZoneRules = [
  {
    'planningRule.name': '关键控制对象优先独立成区',
    'planningRule.domain': '安全设计',
    'planningRule.category': '区域划分',
    'planningRule.trigger': '关键控制对象与一般监控、办公或维护对象在职责和风险上明显不同。',
    'planningRule.scene': '控制系统 / 关键控制区 / 高风险对象',
    'planningRule.recommend': '优先将关键控制对象独立成区，并明确边界职责。',
    'planningRule.avoid': '避免将关键控制对象与一般服务对象混放在同一区域。',
    'planningRule.reason': '独立成区便于边界控制、访问审计和风险隔离。',
    'planningRule.scope': '适用于控制区、保护区、关键服务区划分。',
    'planningRule.alternative': '若规模过小无法独立成区，可先逻辑隔离并保留后续演进空间。',
    'planningRule.example': 'PLC、控制服务器、关键 HMI 独立控制区。',
    'planningRule.note': '需结合边界互联规则一并判断。',
  },
  {
    'planningRule.name': '运维对象优先单独管理分区',
    'planningRule.domain': '安全设计',
    'planningRule.category': '区域划分',
    'planningRule.trigger': '维护终端、跳板机、工程师站承担跨区管理职责。',
    'planningRule.scene': '远程运维 / 本地运维 / 跨区调试',
    'planningRule.recommend': '优先将运维对象归入独立运维区或独立管理分区。',
    'planningRule.avoid': '避免维护终端长期混接在控制区或普通监控区。',
    'planningRule.reason': '运维对象天然具备跨区访问能力，应重点约束。',
    'planningRule.scope': '适用于远程维护、本地工程师站和第三方维护场景。',
    'planningRule.alternative': '在极小规模项目中，可先逻辑隔离并强化账户与审计。',
    'planningRule.example': '工程师站、跳板机、远程维护代理单独成区。',
    'planningRule.note': '与安全规则和通道规则联动。',
  },
  {
    'planningRule.name': '区域划分优先服从职责边界',
    'planningRule.domain': '网络设计',
    'planningRule.category': '区域划分',
    'planningRule.trigger': '同一物理区域内存在不同职责对象或不同管理边界。',
    'planningRule.scene': '混合机柜 / 混合控制室 / 多角色对象共存',
    'planningRule.recommend': '优先按职责边界划分区域，再决定物理部署细节。',
    'planningRule.avoid': '避免只按空间位置划区，忽略职责差异。',
    'planningRule.reason': '职责边界决定访问关系和后续控制要求。',
    'planningRule.scope': '适用于职责差异明显但空间混布的场景。',
    'planningRule.alternative': '若职责一致且访问关系简单，可按物理位置简化划区。',
    'planningRule.example': '同一控制室内区分控制、监控与维护对象。',
    'planningRule.note': '与场景规则协同判断。',
  },
];
