export const demoSelectionRules = [
      {
        'planningRule.name': '设备选型优先匹配场景能力缺口',
        'planningRule.domain': '设备选型',
        'planningRule.category': '能力匹配',
        'planningRule.trigger': '项目对接口数量、环境等级、冗余、协议或管理能力有明确要求。',
        'planningRule.scene': '工业交换机 / 边界设备 / 接入设备选型',
        'planningRule.recommend': '先定义能力缺口，再选择满足能力要求的设备类型或型号。',
        'planningRule.avoid': '避免先定型号再倒推能力说明。',
        'planningRule.reason': '能力驱动的选型更稳定，也便于后续复用。',
        'planningRule.scope': '适用于核心、汇聚、接入及边界设备选型。',
        'planningRule.alternative': '若预算严格，可分层次满足关键能力与非关键能力。',
        'planningRule.example': '根据温度、端口、电源冗余要求确定交换机系列。',
        'planningRule.note': '与性能、稳定性和部署规则联动。',
      },
      {
        'planningRule.name': '边界设备优先匹配控制能力',
        'planningRule.domain': '设备选型',
        'planningRule.category': '边界设备',
        'planningRule.trigger': '设备承担访问控制、审计、协议转换或边界隔离职责。',
        'planningRule.scene': '工业防火墙 / 安全网关 / 代理服务器',
        'planningRule.recommend': '优先匹配访问控制、审计留痕和可维护能力。',
        'planningRule.avoid': '避免仅按转发性能选择边界设备。',
        'planningRule.reason': '边界设备的价值在于控制能力，而不只是转发能力。',
        'planningRule.scope': '适用于所有边界类设备。',
        'planningRule.alternative': '在简单互联场景下可采用轻量边界节点，但仍需可审计。',
        'planningRule.example': '工业防火墙需要支持规则审计和细粒度访问控制。',
        'planningRule.note': '与边界规则、安全规则联动。',
      },
      {
        'planningRule.name': '工业现场选型优先满足环境适应性',
        'planningRule.domain': '设备选型',
        'planningRule.category': '环境适配',
        'planningRule.trigger': '现场存在高温、高湿、振动、防爆、电磁干扰等环境要求。',
        'planningRule.scene': '严苛工业环境 / 防爆区域 / 户外柜体',
        'planningRule.recommend': '优先匹配环境等级、安装方式和供电条件。',
        'planningRule.avoid': '避免用商用设备硬套工业现场。',
        'planningRule.reason': '环境适配性直接影响设备寿命和故障率。',
        'planningRule.scope': '适用于工业现场设备选型。',
        'planningRule.alternative': '若环境可控，可适度放宽工业等级要求。',
        'planningRule.example': '防爆区设备需满足防爆要求与耐环境等级。',
        'planningRule.note': '与部署规则联动。',
      },
    ];
