export const demoLayerRules = [
  {
    'planningRule.name': '大规模厂区引入汇聚层',
    'planningRule.domain': '网络设计',
    'planningRule.category': '分层设计',
    'planningRule.trigger': '厂区范围大、对象数量多、跨区域布线明显。',
    'planningRule.scene': '大规模厂区 / 多车间 / 多楼栋',
    'planningRule.recommend': '设置汇聚层，按区域或功能块汇聚后再上联核心层。',
    'planningRule.avoid': '避免所有接入点直接上联核心，造成核心口数和管理复杂度失控。',
    'planningRule.reason': '汇聚层有利于控制规模、清晰层级并降低主干复杂度。',
    'planningRule.scope': '影响分层结构、主干布线、交换机数量与容量规划。',
    'planningRule.example': '整厂级项目、跨楼栋项目、多个系统统一汇聚项目。',
    'planningRule.note': '汇聚层划分应尽量与区域或系统边界保持一致。',
  },
  {
    'planningRule.name': '小规模场景接入可直上核心',
    'planningRule.domain': '网络设计',
    'planningRule.category': '分层设计',
    'planningRule.trigger': '对象数量有限、布线资源充足、核心接口能力足够。',
    'planningRule.scene': '小规模厂区 / 单车间 / 集中部署',
    'planningRule.recommend': '采用两层甚至单层简化结构，接入层可直接上联核心。',
    'planningRule.avoid': '避免为了形式追求完整三层，导致结构虚胖。',
    'planningRule.reason': '简化结构便于实施、维护和故障定位，也更经济。',
    'planningRule.scope': '影响核心接口规划、布线方式、设备数量和维护复杂度。',
    'planningRule.example': '单产线改造、单控制室、小型能源站。',
    'planningRule.note': '若后续扩展可能较大，应预留向汇聚层演进的空间。',
  },
  {
    'planningRule.name': '多系统汇聚场景分层优先按功能划分',
    'planningRule.domain': '网络设计',
    'planningRule.category': '分层设计',
    'planningRule.trigger': 'MES、SCADA、历史库、FMCS 等多个系统同时接入。',
    'planningRule.scene': '多系统汇聚 / 平台集中监控 / 上下游系统集成',
    'planningRule.recommend': '优先按系统角色和访问关系分层，再确定核心与汇聚职责。',
    'planningRule.avoid': '避免单纯按设备数量分层，忽略系统交互特征。',
    'planningRule.reason': '功能驱动的分层更利于后续边界控制和运维管理。',
    'planningRule.scope': '影响分层逻辑、区域划分、边界设计和技术选择。',
    'planningRule.example': 'MES 与产线控制系统、FMCS 与公用工程子系统汇聚。',
    'planningRule.note': '建议与区域与边界规则联动判断。',
  },
];
