export const demoConduitRules = [
  {
    'planningRule.name': '跨区访问优先收敛通道',
    'planningRule.domain': '安全设计',
    'planningRule.category': '通道设计',
    'planningRule.trigger': '区域之间存在明确访问需求，且访问对象与方向相对固定。',
    'planningRule.scene': '跨区访问 / 远程维护 / 上下游接口',
    'planningRule.recommend': '优先通过收敛通道组织跨区访问，并明确方向、协议与控制策略。',
    'planningRule.avoid': '避免跨区链路任意直通，导致访问路径不可控。',
    'planningRule.reason': '通道收敛有助于统一审计、统一控制和统一维护。',
    'planningRule.scope': '适用于区域间固定访问关系的场景。',
    'planningRule.alternative': '若访问关系极少且可控，可采用单点受控互联。',
    'planningRule.example': 'DMZ 到控制区的远程维护通道。',
    'planningRule.note': '应与边界互联规则和安全规则联动。',
  },
  {
    'planningRule.name': '高风险访问优先单独控制通道',
    'planningRule.domain': '安全设计',
    'planningRule.category': '通道设计',
    'planningRule.trigger': '访问路径涉及第三方、远程运维或高权限维护对象。',
    'planningRule.scene': '第三方维护 / 高权限运维 / 临时调试',
    'planningRule.recommend': '为高风险访问建立独立受控通道，并单独配置认证和审计策略。',
    'planningRule.avoid': '避免与普通业务通道共用控制策略。',
    'planningRule.reason': '高风险访问需要更高粒度的控制和审计。',
    'planningRule.scope': '适用于高权限或高风险访问链路。',
    'planningRule.alternative': '若高风险访问频次极低，可采用临时启用并全程审计的方式。',
    'planningRule.example': '第三方设备厂商远程维护通道独立收敛。',
    'planningRule.note': '应与账户、审计和边界规则配合。',
  },
  {
    'planningRule.name': '固定交互优先固定通道策略',
    'planningRule.domain': '网络设计',
    'planningRule.category': '通道设计',
    'planningRule.trigger': '跨区交互对象、方向和协议较稳定。',
    'planningRule.scene': '固定系统接口 / 稳定跨区通信',
    'planningRule.recommend': '优先固化通道方向、协议范围和控制点。',
    'planningRule.avoid': '避免将长期固定交互设计成临时开放模式。',
    'planningRule.reason': '固定策略有助于长期运维与审计。',
    'planningRule.scope': '适用于稳定接口型通道。',
    'planningRule.alternative': '若交互关系频繁变化，可采用受控白名单策略。',
    'planningRule.example': 'MES 到控制区接口服务的固定通道。',
    'planningRule.note': '与边界互联规则联动。',
  },
];
