export const demoDeploymentRules = [
      {
        'planningRule.name': '部署设计优先服从现场施工条件',
        'planningRule.domain': '部署设计',
        'planningRule.category': '实施落地',
        'planningRule.trigger': '现场存在防爆、空间受限、布线困难或不停产施工约束。',
        'planningRule.scene': '改造项目 / 防爆区域 / 施工窗口受限',
        'planningRule.recommend': '优先按现场施工条件调整部署位置、布线路径和安装方式。',
        'planningRule.avoid': '避免纸面最优但现场无法落地的设计。',
        'planningRule.reason': '部署设计最终必须服务可实施性。',
        'planningRule.scope': '适用于改造项目和复杂现场实施条件。',
        'planningRule.alternative': '若施工条件宽松，可优先按长期维护最优部署。',
        'planningRule.example': '不停产条件下优先沿既有桥架分阶段改造。',
        'planningRule.note': '与实施约束页和稳定性规则联动。',
      },
      {
        'planningRule.name': '关键设备优先部署在可维护位置',
        'planningRule.domain': '部署设计',
        'planningRule.category': '运维可达性',
        'planningRule.trigger': '设备承担关键汇聚、边界或控制职责，后期维护频率较高。',
        'planningRule.scene': '核心设备 / 边界设备 / 汇聚设备',
        'planningRule.recommend': '优先部署在可达、可维护、便于替换的位置。',
        'planningRule.avoid': '避免关键设备部署在难以维护的角落或高风险位置。',
        'planningRule.reason': '关键设备的运维可达性会直接影响恢复时间。',
        'planningRule.scope': '适用于关键网络设备部署。',
        'planningRule.alternative': '若位置受限，应通过冗余和布线设计降低风险。',
        'planningRule.example': '核心交换机布置在可维护机柜而非临时箱体。',
        'planningRule.note': '与稳定性规则和选型规则联动。',
      },
      {
        'planningRule.name': '布线设计优先减少后期变更成本',
        'planningRule.domain': '部署设计',
        'planningRule.category': '布线策略',
        'planningRule.trigger': '项目存在未来扩展、分阶段建设或长期运维需求。',
        'planningRule.scene': '整厂建设 / 分阶段建设 / 中长期运维',
        'planningRule.recommend': '优先选择便于扩展、标识清晰、维护成本低的布线与部署方式。',
        'planningRule.avoid': '避免只满足当前最短路径，忽略后续维护与扩展。',
        'planningRule.reason': '部署阶段的布线选择会长期影响运维成本。',
        'planningRule.scope': '适用于中长期运营项目。',
        'planningRule.alternative': '短生命周期项目可适度简化布线冗余。',
        'planningRule.example': '预留桥架空间、标准化标签与机柜配线。',
        'planningRule.note': '与地址规划规则和场景规则联动。',
      },
    ];
