export const demoScenarioRules = [
      {
        'planningRule.name': '小规模集中场景优先简化结构',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '项目对象集中、系统规模小、工期和预算要求紧。',
        'planningRule.scene': '小规模集中部署 / 单区域项目',
        'planningRule.recommend': '优先采用简化拓扑与简化分层，减少不必要中间层。',
        'planningRule.avoid': '避免照搬大厂区架构，造成结构和设备配置过重。',
        'planningRule.reason': '小规模项目更重视快速落地和清晰维护。',
        'planningRule.scope': '影响拓扑、分层、设备选型与实施策略。',
        'planningRule.example': '单车间改造、独立站房、小型站点网络。',
        'planningRule.note': '若后续扩展预期大，可在地址和接口上预留余量。',
      },
      {
        'planningRule.name': '线型产线场景优先沿线组织网络',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '对象沿生产节拍方向顺序排布，现场布线路径明确。',
        'planningRule.scene': '汽车产线 / 包装产线 / 输送产线',
        'planningRule.recommend': '按线体组织网络，优先沿线布局节点，再结合冗余要求决定环网或分段星型。',
        'planningRule.avoid': '避免只按房间或机柜组织网络，忽略生产链路的连续性。',
        'planningRule.reason': '沿线组织更符合现场物理布局和故障排查路径。',
        'planningRule.scope': '影响拓扑、部署位置、链路设计和维护路径。',
        'planningRule.example': '焊装线、装配线、输送系统网络。',
        'planningRule.note': '需要同时参考拓扑规则与冗余设计。',
      },
      {
        'planningRule.name': '远程运维场景优先先定边界再定结构',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '项目涉及第三方维护、远程访问或跨域调试。',
        'planningRule.scene': '远程运维 / 跨域访问 / 第三方维护',
        'planningRule.recommend': '先明确访问边界、控制点和路径，再决定拓扑、分层与地址策略。',
        'planningRule.avoid': '避免先把网络连通，再事后补访问控制。',
        'planningRule.reason': '远程运维场景中，边界和访问路径决定了后续结构约束。',
        'planningRule.scope': '影响区域划分、边界设计、技术选择和输出文档重点。',
        'planningRule.example': '供应商远程维护、总部远程监控、跨厂区支持场景。',
        'planningRule.note': '此类规则后续应与安全规则页进一步联动。',
      },
    ];
