export const demoBoundaryRules = [
  {
    'planningRule.name': '跨边界互联优先设控制点',
    'planningRule.domain': '边界设计',
    'planningRule.category': '边界互联',
    'planningRule.trigger': '不同安全属性、不同职责或不同管理域之间需要互联。',
    'planningRule.scene': '控制区与 DMZ / 生产网与办公网 / 多管理域互联',
    'planningRule.recommend': '在边界处设置明确控制点，定义互联结构与控制策略。',
    'planningRule.avoid': '避免通过普通二层直通跨越关键边界。',
    'planningRule.reason': '边界控制点是实现访问策略、审计和隔离的关键位置。',
    'planningRule.scope': '适用于安全边界、系统边界和管理边界互联。',
    'planningRule.alternative': '若边界极其简单，可采用最小化互联，但仍需可审计。',
    'planningRule.example': '控制区通过工业防火墙与上层区互联。',
    'planningRule.note': '与通道规则一起决定跨区实现方式。',
  },
  {
    'planningRule.name': '办公与控制互联优先经过中间区',
    'planningRule.domain': '安全设计',
    'planningRule.category': '边界互联',
    'planningRule.trigger': '办公网、信息网与控制相关网络存在数据或访问关系。',
    'planningRule.scene': '办公网 / 信息网 / 控制网互联',
    'planningRule.recommend': '优先通过 DMZ 或中间区承接互联，不直接跨越边界。',
    'planningRule.avoid': '避免办公网直达控制区。',
    'planningRule.reason': '中间区有助于隔离风险并统一控制。',
    'planningRule.scope': '适用于 IT/OT 互联场景。',
    'planningRule.alternative': '若仅有单向数据发布，可采用单向隔离方式。',
    'planningRule.example': '办公网经 DMZ 访问生产数据展示系统。',
    'planningRule.note': '与安全规则联动。',
  },
  {
    'planningRule.name': '边界设备优先承担边界职责',
    'planningRule.domain': '边界设计',
    'planningRule.category': '边界互联',
    'planningRule.trigger': '互联点既承担连通，又承担控制、审计或转换职责。',
    'planningRule.scene': '工业防火墙 / 代理网关 / 边界交换设备',
    'planningRule.recommend': '优先由边界设备承担边界职责，不将边界能力分散到普通接入设备。',
    'planningRule.avoid': '避免边界控制能力散落在多个普通节点。',
    'planningRule.reason': '边界职责集中有利于统一策略与可维护性。',
    'planningRule.scope': '适用于边界策略较复杂的互联点。',
    'planningRule.alternative': '在极简场景中，可采用少量受控节点临时承担边界职责。',
    'planningRule.example': '工业防火墙承担控制区到上层区的互联与策略控制。',
    'planningRule.note': '与选型规则、部署规则一并判断。',
  },
];
