export const demoPerformanceRules = [
      {
        'planningRule.name': '实时控制链路优先单独评估性能',
        'planningRule.domain': '性能设计',
        'planningRule.category': '实时性',
        'planningRule.trigger': '链路承载控制闭环、时钟同步或高实时要求业务。',
        'planningRule.scene': '运动控制 / 高速控制 / 精确时钟场景',
        'planningRule.recommend': '将关键实时链路单独识别并评估时延、抖动、带宽和同步要求。',
        'planningRule.avoid': '避免将高实时链路与普通监控流量混为一谈。',
        'planningRule.reason': '关键链路对实时性更敏感，需单独收敛性能设计。',
        'planningRule.scope': '适用于闭环控制和高实时业务链路。',
        'planningRule.alternative': '若实时要求不高，可采用通用工业以太网能力。',
        'planningRule.example': '机器人控制链路、同步采集链路。',
        'planningRule.note': '与技术选择规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '主干链路优先按峰值流量评估带宽',
        'planningRule.domain': '性能设计',
        'planningRule.category': '带宽评估',
        'planningRule.trigger': '主干链路汇聚多个系统或多个区域流量。',
        'planningRule.scene': '核心上联 / 汇聚上联 / 跨区主干',
        'planningRule.recommend': '优先按峰值并发流量和未来增长空间评估主干带宽。',
        'planningRule.avoid': '避免只按当前平均流量选带宽。',
        'planningRule.reason': '主干链路的瓶颈会放大整个系统的性能风险。',
        'planningRule.scope': '适用于汇聚与主干链路设计。',
        'planningRule.alternative': '若业务流量长期平稳，可按保守冗余系数规划。',
        'planningRule.example': '汇聚层到核心层上联按峰值并发评估千兆/万兆。',
        'planningRule.note': '与分层规则和冗余规则联动。',
      },
      {
        'planningRule.name': '混合业务优先区分控制流与监控流',
        'planningRule.domain': '性能设计',
        'planningRule.category': '业务区分',
        'planningRule.trigger': '链路同时承载控制、监控、视频、运维等多类业务。',
        'planningRule.scene': '综合业务网络 / 多系统融合网络',
        'planningRule.recommend': '优先识别并区分关键控制流与一般监控流，必要时做优先级或隔离设计。',
        'planningRule.avoid': '避免混合业务完全等价承载。',
        'planningRule.reason': '不同业务对时延、带宽和抖动容忍度不同。',
        'planningRule.scope': '适用于融合型工业网络。',
        'planningRule.alternative': '在业务单一场景中可简化性能分类。',
        'planningRule.example': '控制数据与视频流分级承载。',
        'planningRule.note': '与拓扑规则和技术选择规则联动。',
      },
    ];
