export const demoTechnologyRules = [
      {
        'planningRule.name': '技术选择优先服从场景约束',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '多种技术方案都能实现目标，但现场约束不同。',
        'planningRule.scene': 'TSN / Wi-Fi / 5G / APL / 工业以太网',
        'planningRule.recommend': '先明确时延、可靠性、布线、维护和安全约束，再决定技术路线。',
        'planningRule.avoid': '避免因为技术流行度而直接选型。',
        'planningRule.reason': '技术能力必须与现场约束和维护能力匹配。',
        'planningRule.scope': '适用于技术路线存在多选项的项目。',
        'planningRule.alternative': '若条件不成熟，可采用成熟技术先落地并预留演进能力。',
        'planningRule.example': '高时敏场景选 TSN，移动对象场景评估 Wi-Fi/5G。',
        'planningRule.note': '需与性能规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '成熟性优先于概念先进性',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '项目实施窗口紧、团队经验有限或维护体系尚不成熟。',
        'planningRule.scene': '改造项目 / 交付窗口紧 / 维护能力有限',
        'planningRule.recommend': '优先采用成熟、可维护、已验证的技术路线。',
        'planningRule.avoid': '避免为追求先进性而引入高不确定性技术。',
        'planningRule.reason': '工业项目更重视可交付与可维护。',
        'planningRule.scope': '适用于交付压力大或维护资源有限的项目。',
        'planningRule.alternative': '若项目具备试点属性，可局部引入新技术验证。',
        'planningRule.example': '优先工业以太网而非未验证的新型无线方案。',
        'planningRule.note': '与部署规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '无线技术优先用于移动与难布线场景',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '对象移动、布线困难或临时接入需求明显。',
        'planningRule.scene': 'AGV / 移动物料 / 临时接入 / 广域覆盖',
        'planningRule.recommend': '优先评估 Wi-Fi 或 5G 等无线技术，并同步评估安全与漫游能力。',
        'planningRule.avoid': '避免在固定关键控制链路上盲目使用无线。',
        'planningRule.reason': '无线的优势在于灵活性，但代价是可控性与稳定性评估要求更高。',
        'planningRule.scope': '适用于移动对象或布线困难场景。',
        'planningRule.alternative': '若可布线且对象固定，应优先采用有线方案。',
        'planningRule.example': 'AGV 调度网络、移动巡检终端网络。',
        'planningRule.note': '需与性能规则和安全规则联动。',
      },
    ];
