export const demoAccessRules = [
      {
        'planningRule.name': '对象接入优先按对象特性分类',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '网络中存在控制对象、监控对象、维护对象等多类终端。',
        'planningRule.scene': '混合对象接入 / 多角色终端接入',
        'planningRule.recommend': '按对象特性与访问权限组织接入方式和接入边界。',
        'planningRule.avoid': '避免只按物理位置接入而忽略对象角色差异。',
        'planningRule.reason': '对象角色决定了访问需求、权限边界与维护方式。',
        'planningRule.scope': '适用于对象类型差异明显的项目。',
        'planningRule.alternative': '若对象单一，可按位置优先接入。',
        'planningRule.example': 'PLC、摄像头、维护终端采用不同接入策略。',
        'planningRule.note': '需与区域规则和安全规则联动。',
      },
      {
        'planningRule.name': '关键控制对象优先有线独立接入',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '对象承担关键控制、关键联锁或实时闭环职责。',
        'planningRule.scene': 'PLC / DCS / 联锁控制 / 关键控制服务器',
        'planningRule.recommend': '优先采用有线、独立、可控的接入方式。',
        'planningRule.avoid': '避免关键控制对象依赖共享无线或混杂接入环境。',
        'planningRule.reason': '关键控制对象对稳定性、可控性和排障路径要求更高。',
        'planningRule.scope': '适用于关键控制和关键服务对象。',
        'planningRule.alternative': '若必须无线接入，应单独评估实时性与可靠性。',
        'planningRule.example': 'PLC 采用独立交换端口和专属 VLAN 接入。',
        'planningRule.note': '与性能规则和安全规则联动。',
      },
      {
        'planningRule.name': '维护终端优先受控接入',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '对象用于调试、维护、升级或排障。',
        'planningRule.scene': '工程师站 / 维护笔记本 / 调试终端',
        'planningRule.recommend': '优先通过受控端口、受控 VLAN 或受控维护区接入。',
        'planningRule.avoid': '避免维护终端长期接入生产控制端口。',
        'planningRule.reason': '维护对象具有高变更与高越权风险。',
        'planningRule.scope': '适用于所有运维与临时调试对象。',
        'planningRule.alternative': '在临时应急场景下可短期直连，但需严格留痕。',
        'planningRule.example': '维护笔记本通过专用维护口接入。',
        'planningRule.note': '与安全规则和区域规则联动。',
      },
    ];
