export const demoTopologyRules = [
  {
    'planningRule.name': '线型对象优先环网',
    'planningRule.domain': '网络设计',
    'planningRule.category': '拓扑设计',
    'planningRule.trigger': '设备沿产线或输送链路线性分布，且业务连续性要求高。',
    'planningRule.scene': '线型产线 / 连续排布设备 / 冗余要求高',
    'planningRule.recommend': '优先采用工业环网，并明确冗余切换方式和边界节点位置。',
    'planningRule.avoid': '避免在对象高度集中场景中机械套用环网，导致链路复杂度增加。',
    'planningRule.reason': '环网更适合线型部署，布线顺势且能兼顾冗余。',
    'planningRule.scope': '影响网络拓扑、交换机选型、链路设计、冗余设计。',
    'planningRule.example': '汽车焊装线、输送线、包装线等沿线设备网络。',
    'planningRule.note': '若存在多个线体汇聚，应与分层规则结合判断。',
  },
  {
    'planningRule.name': '集中对象优先星型',
    'planningRule.domain': '网络设计',
    'planningRule.category': '拓扑设计',
    'planningRule.trigger': '设备集中分布，上联关系清晰，现场布线条件较好。',
    'planningRule.scene': '集中设备区 / 机柜集中 / 单房间部署',
    'planningRule.recommend': '优先采用星型结构，由接入层或对象直接上联中心节点。',
    'planningRule.avoid': '避免为了形式统一强行做环网，增加不必要的节点和维护复杂度。',
    'planningRule.reason': '星型结构最直接，便于故障定位和容量管理。',
    'planningRule.scope': '影响拓扑形态、布线方式、中心交换设备接口规划。',
    'planningRule.example': '监控室、机房、集中控制室等对象集中场景。',
    'planningRule.note': '若中心节点成为单点，应结合冗余规则进一步处理。',
  },
  {
    'planningRule.name': '多区域场景优先混合拓扑',
    'planningRule.domain': '网络设计',
    'planningRule.category': '拓扑设计',
    'planningRule.trigger': '厂区存在多个功能区、多个车间或多楼栋分布。',
    'planningRule.scene': '多区域厂区 / 多车间 / 多楼栋',
    'planningRule.recommend': '优先采用核心汇聚星型 + 区域内部局部环网或星型的混合拓扑。',
    'planningRule.avoid': '避免用单一拓扑覆盖全厂，导致结构过大且边界不清。',
    'planningRule.reason': '混合拓扑更适合兼顾区域差异、扩展性和边界管理。',
    'planningRule.scope': '影响总体拓扑、分层设计、区域互联和边界实现。',
    'planningRule.example': '整厂级制造网络、公用工程 + 生产控制混合网络。',
    'planningRule.note': '应先明确区域边界，再决定区域内部采用何种局部拓扑。',
  },
];
