export const demoStabilityRules = [
      {
        'planningRule.name': '关键网络优先控制变化面',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '变更控制',
        'planningRule.trigger': '网络承载关键生产业务，且停机窗口短。',
        'planningRule.scene': '连续生产 / 停机窗口短 / 高连续性要求',
        'planningRule.recommend': '优先减少中间变化点，控制配置复杂度，并明确回退路径。',
        'planningRule.avoid': '避免在高连续性网络中引入过多复杂机制。',
        'planningRule.reason': '稳定性优先场景中，复杂度本身就是风险来源。',
        'planningRule.scope': '适用于关键生产网络与连续生产场景。',
        'planningRule.alternative': '若容错空间大，可适度增加复杂机制换取灵活性。',
        'planningRule.example': '不停产改造的核心网络。',
        'planningRule.note': '应与冗余规则、部署规则一并判断。',
      },
      {
        'planningRule.name': '协议机制优先保持必要最简',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '协议复杂度',
        'planningRule.trigger': '网络中拟引入多种控制、冗余、路由或安全机制。',
        'planningRule.scene': '综合工业网络 / 多协议混合网络',
        'planningRule.recommend': '优先保留必要且可维护的协议机制组合。',
        'planningRule.avoid': '避免无明确收益地堆叠机制。',
        'planningRule.reason': '机制越多，调试难度与故障面越大。',
        'planningRule.scope': '适用于需要兼顾可维护性的网络。',
        'planningRule.alternative': '在试点项目中可局部验证复杂机制。',
        'planningRule.example': '仅保留必要的环网与 VLAN，不叠加过多特性。',
        'planningRule.note': '与技术选择规则和冗余规则联动。',
      },
      {
        'planningRule.name': '改造项目优先兼容现网稳定边界',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '现网继承',
        'planningRule.trigger': '项目为改造类，且现网已有可稳定运行部分。',
        'planningRule.scene': '存量改造 / 分阶段替换 / 不停产切换',
        'planningRule.recommend': '优先保留已稳定的边界与结构，逐步替换高风险部分。',
        'planningRule.avoid': '避免在改造期全面推翻现网。',
        'planningRule.reason': '改造项目中最主要的风险来自过大变化面。',
        'planningRule.scope': '适用于存量系统改造项目。',
        'planningRule.alternative': '若现网问题严重，可局部并行新建后切换。',
        'planningRule.example': '先保留既有骨干，再分区替换接入层。',
        'planningRule.note': '与部署规则和实施约束联动。',
      },
    ];
