import { buildEmptyDraft } from '../engine/methodologyHelpers.js';

function createInitialDrafts() {
  return {
    'project-goal': buildEmptyDraft([
      'project.name',
      'project.customer',
      'project.industry',
      'project.scope',
      'project.goal',
      'project.delivery',
      'project.owner',
      'project.confirmStatus',
    ]),
    'scope-definition': buildEmptyDraft([
      'overview.name',
      'overview.space',
      'overview.distribution',
      'overview.cross',
      'overview.scale',
      'overview.note',
    ]),
    'business-description': buildEmptyDraft([
      'scene.name',
      'scene.mode',
      'scene.source',
      'scene.target',
      'scene.purpose',
      'scene.medium',
      'scene.continuity',
      'scene.note',
    ]),
    'asset-allocation': buildEmptyDraft([
      'asset.name',
      'asset.type',
      'asset.system',
      'asset.location',
      'asset.level',
      'asset.status',
      'asset.access',
      'asset.criticality',
      'asset.note',
    ]),
    'environment-conditions': buildEmptyDraft([
      'env.topic',
      'env.interference',
      'env.install',
      'env.distance',
      'env.medium',
      'env.power',
      'env.wireless',
      'env.note',
    ]),
    'implementation-constraints': buildEmptyDraft([
      'constraint.name',
      'constraint.type',
      'constraint.required',
      'constraint.scope',
      'constraint.existing',
      'constraint.note',
    ]),
    'security-scenario': buildEmptyDraft([
      'secScenario.name',
      'secScenario.type',
      'secScenario.scope',
      'secScenario.remote',
      'secScenario.external',
      'secScenario.note',
    ]),
    'exposure-analysis': buildEmptyDraft([
      'secExposure.name',
      'secExposure.relatedScenario',
      'secExposure.type',
      'secExposure.source',
      'secExposure.control',
      'secExposure.risk',
      'secExposure.note',
    ]),
    'consequence-analysis': buildEmptyDraft([
      'secConsequence.name',
      'secConsequence.relatedScenario',
      'secConsequence.type',
      'secConsequence.impact',
      'secConsequence.severity',
      'secConsequence.recovery',
      'secConsequence.note',
    ]),
    'baseline-check': buildEmptyDraft([
      'secBaseline.type',
      'secBaseline.object',
      'secBaseline.status',
      'secBaseline.evidence',
      'secBaseline.gap',
      'secBaseline.note',
    ]),
    'key-asset-analysis': buildEmptyDraft([
      'secKey.name',
      'secKey.type',
      'secKey.reason',
      'secKey.focus',
      'secKey.priority',
      'secKey.note',
    ]),
    'design-principles': buildEmptyDraft([
      'principle.category',
      'principle.main',
      'principle.scope',
      'principle.basis',
      'principle.desc',
      'principle.note',
    ]),
    'network-topology': buildEmptyDraft([
      'topology.object',
      'topology.type',
      'topology.backbone',
      'topology.access',
      'topology.scope',
      'topology.basis',
      'topology.tech',
      'topology.note',
    ]),
    'layer-design': buildEmptyDraft([
      'layer.object',
      'layer.mode',
      'layer.structure',
      'layer.policy',
      'layer.scope',
      'layer.note',
    ]),
    'segmentation-plan': buildEmptyDraft([
      'seg.object',
      'seg.purpose',
      'seg.range',
      'seg.margin',
      'seg.note',
    ]),
    'performance-design': buildEmptyDraft([
      'performance.object',
      'performance.latency',
      'performance.bandwidth',
      'performance.clock',
      'performance.measure',
      'performance.service',
      'performance.delay',
      'performance.risk',
      'performance.note',
    ]),
    'stability-design': buildEmptyDraft([
      'stability.object',
      'stability.target',
      'stability.risk',
      'stability.measure',
      'stability.control',
      'stability.maintain',
      'stability.note',
    ]),
    'redundancy-design': buildEmptyDraft([
      'redundancy.object',
      'redundancy.target',
      'redundancy.mode',
      'redundancy.switch',
      'redundancy.note',
    ]),
    'access-design': buildEmptyDraft([
      'access.object',
      'access.type',
      'access.scope',
      'access.limit',
      'access.reason',
      'access.note',
    ]),
    'selection-design': buildEmptyDraft([
      'selection.object',
      'selection.demand',
      'selection.capability',
      'selection.result',
      'selection.reason',
      'selection.note',
    ]),
    'deployment-design': buildEmptyDraft([
      'deployment.object',
      'deployment.location',
      'deployment.install',
      'deployment.cabling',
      'deployment.requirement',
      'deployment.note',
    ]),
    'link-design': buildEmptyDraft([
      'link.source',
      'link.target',
      'link.scene',
      'link.type',
      'link.role',
      'link.redundant',
      'link.sourceLocation',
      'link.targetLocation',
      'link.medium',
      'link.note',
    ]),
    'conduit-design': buildEmptyDraft([
      'conduit.source',
      'conduit.target',
      'conduit.scene',
      'conduit.purpose',
      'conduit.direction',
      'conduit.medium',
      'conduit.control',
      'conduit.delay',
      'conduit.criticality',
      'conduit.note',
    ]),
    'interconnect-design': buildEmptyDraft([
      'interconnect.source',
      'interconnect.target',
      'interconnect.structure',
      'interconnect.boundary',
      'interconnect.control',
      'interconnect.note',
    ]),
    'tech-selection': buildEmptyDraft([
      'tech.name',
      'tech.category',
      'tech.technology',
      'tech.scopeType',
      'tech.scopeTarget',
      'tech.scopeNote',
      'tech.goal',
      'tech.reason',
      'tech.alternative',
      'tech.alternativeReason',
      'tech.constraint',
      'tech.confirmStatus',
      'tech.note',
    ]),
    'security-limit': buildEmptyDraft([
      'secLimit.name',
      'secLimit.type',
      'secLimit.object',
      'secLimit.required',
      'secLimit.note',
    ]),
    'delay-analysis': buildEmptyDraft([
      'delay.name',
      'delay.length',
      'delay.medium',
      'delay.hops',
      'delay.boundary',
      'delay.dmz',
      'delay.demand',
      'delay.risk',
      'delay.result',
    ]),
    'perf-evaluation': buildEmptyDraft([
      'perf.object',
      'perf.type',
      'perf.load',
      'perf.bandwidth',
      'perf.path',
      'perf.risk',
      'perf.result',
    ]),
    'topology-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
    'layer-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
    'scenario-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
  };
}

export { createInitialDrafts };
