import {
  demoTopologyRules,
  demoLayerRules,
  demoZoneRules,
  demoConduitRules,
  demoBoundaryRules,
  demoTechnologyRules,
  demoAddressRules,
  demoPerformanceRules,
  demoStabilityRules,
  demoRedundancyRules,
  demoAccessRules,
  demoSelectionRules,
  demoDeploymentRules,
  demoSecurityRules,
  demoScenarioRules,
} from '../rules/index.js';

function createInitialCollections() {
  return {
    'project-goal': [
      {
        'project.name': '工业网络规划项目',
        'project.customer': '待填写客户名称',
        'project.industry': '离散制造',
        'project.scope': '整厂',
        'project.goal': '新建',
        'project.delivery': '网络规划方案、结果输出与实施建议。',
        'project.owner': '待填写负责人',
        'project.confirmStatus': '待确认',
      },
    ],
    'scope-definition': [
      {
        'overview.name': '主项目范围',
        'overview.space': '1 个厂区 / 若干车间 / 关键业务区域',
        'overview.distribution': '中心区与现场区混合分布',
        'overview.cross': '存在跨区访问',
        'overview.scale': '中等规模',
        'overview.note': '',
      },
    ],
    'business-description': [
      {
        'scene.name': '核心业务场景',
        'scene.mode': '周期通信',
        'scene.source': '上层系统',
        'scene.target': '现场控制对象',
        'scene.purpose': '生产控制',
        'scene.medium': '有线',
        'scene.continuity': '高',
        'scene.note': '',
      },
    ],
    'asset-allocation': [
      {
        'asset.name': 'PLC-01',
        'asset.type': 'PLC',
        'asset.system': '控制系统',
        'asset.location': '现场控制柜',
        'asset.level': 'Level 1',
        'asset.status': '在用',
        'asset.access': '有线固定接入',
        'asset.criticality': '高',
        'asset.note': '',
      },
    ],
    'environment-conditions': [
      {
        'env.topic': '现场环境条件',
        'env.interference': '一般工业干扰',
        'env.install': '机柜 + 桥架部署',
        'env.distance': '中心区到现场区 100m~500m',
        'env.medium': '工业以太网',
        'env.power': '稳定交流供电',
        'env.wireless': '无',
        'env.note': '',
      },
    ],
    'implementation-constraints': [
      {
        'constraint.name': '预算约束',
        'constraint.type': '预算',
        'constraint.required': '是',
        'constraint.scope': '整项目建设范围',
        'constraint.existing': '需兼顾现网继承与分阶段实施',
        'constraint.note': '',
      },
    ],
    'security-scenario': [
      {
        'secScenario.name': '本地生产场景',
        'secScenario.type': '本地生产',
        'secScenario.scope': '现场控制网络',
        'secScenario.remote': '无',
        'secScenario.external': '无',
        'secScenario.note': '',
      },
    ],
    'exposure-analysis': [
      {
        'secExposure.name': 'PLC-01',
        'secExposure.relatedScenario': '本地生产场景',
        'secExposure.type': '远程接入',
        'secExposure.source': '工程维护或远程维护入口',
        'secExposure.control': '基础账号口令与访问控制',
        'secExposure.risk': '中',
        'secExposure.note': '',
      },
    ],
    'consequence-analysis': [
      {
        'secConsequence.name': 'PLC-01',
        'secConsequence.relatedScenario': '本地生产场景',
        'secConsequence.type': '生产中断',
        'secConsequence.impact': '异常访问或误操作可能导致生产中断',
        'secConsequence.severity': '高',
        'secConsequence.recovery': '需人工恢复与现场排查',
        'secConsequence.note': '',
      },
    ],
    'baseline-check': [
      {
        'secBaseline.type': '边界防护',
        'secBaseline.object': 'PLC-01',
        'secBaseline.status': '已具备',
        'secBaseline.evidence': '已有基本网络隔离措施',
        'secBaseline.gap': '基本满足',
        'secBaseline.note': '',
      },
    ],
    'key-asset-analysis': [
      {
        'secKey.name': 'PLC-01',
        'secKey.type': '控制器',
        'secKey.reason': '直接影响生产连续性',
        'secKey.focus': '边界访问、变更控制与稳定运行',
        'secKey.priority': '高',
        'secKey.note': '',
      },
    ],
    'design-principles': [
      {
        'derive.ruleThemes': '场景规则 / 安全规则 / 技术选择规则',
        'principle.category': '区域划分思路',
        'principle.main': '优先按物理区域与业务边界划分',
        'principle.scope': '中心区、控制区、监控区与边界区',
        'principle.basis': '连续生产与边界治理要求',
        'principle.desc': '先明确边界，再收敛结构与接入方式',
        'principle.note': '',
      },
    ],
    'network-topology': [
      {
        'derive.ruleThemes': '拓扑规则 / 场景规则 / 冗余规则',
        'topology.object': '全厂主干网络',
        'topology.type': '星型',
        'topology.backbone': '中心交换节点统一汇聚',
        'topology.access': '现场控制柜和业务终端就近接入',
        'topology.scope': '中心区与现场区',
        'topology.basis': '便于实施、运维和后续扩展',
        'topology.tech': '工业以太网',
        'topology.note': '',
      },
    ],
    'layer-design': [
      {
        'derive.ruleThemes': '分层规则 / 场景规则',
        'layer.object': '车间汇聚层',
        'layer.mode': '二层',
        'layer.structure': '核心 / 汇聚 / 接入',
        'layer.policy': '按层组织访问与边界控制',
        'layer.scope': '中心区与车间区域',
        'layer.note': '',
      },
    ],
    'segmentation-plan': [
      {
        'seg.object': '控制区网段',
        'seg.purpose': '控制通信',
        'seg.range': '192.168.10.0/24',
        'seg.margin': '预留 20%',
        'seg.note': '',
      },
    ],
    'performance-design': [
      {
        'performance.object': '控制区主链路',
        'performance.latency': '毫秒级',
        'performance.bandwidth': '千兆',
        'performance.clock': '10ms 周期',
        'performance.measure': '关键控制流量优先保障',
        'performance.service': '控制通信',
        'performance.delay': '≤10ms',
        'performance.risk': '广播或异常访问影响时延',
        'performance.note': '',
      },
    ],
    'stability-design': [
      {
        'stability.object': '控制系统主链路',
        'stability.target': '连续稳定运行',
        'stability.risk': '误操作与边界异常',
        'stability.measure': '配置基线与变更审批',
        'stability.control': '日志审计与链路监测',
        'stability.maintain': '窗口期维护',
        'stability.note': '',
      },
    ],
    'redundancy-design': [
      {
        'redundancy.object': '主干光纤链路',
        'redundancy.target': '单点故障不中断业务',
        'redundancy.mode': '主备',
        'redundancy.switch': '故障自动或人工切换',
        'redundancy.note': '',
      },
    ],
    'access-design': [
      {
        'access.object': 'PLC-01',
        'access.type': '有线',
        'access.scope': '现场控制柜',
        'access.limit': '仅允许控制网络设备接入',
        'access.reason': '保证控制流量稳定与边界清晰',
        'access.note': '',
      },
    ],
    'selection-design': [
      {
        'selection.object': 'PLC-01',
        'selection.demand': '控制通信',
        'selection.capability': '工业协议支持、稳定运行、环境适应',
        'selection.result': '工业交换机接入',
        'selection.reason': '满足工业现场稳定性与维护要求',
        'selection.note': '',
      },
    ],
    'deployment-design': [
      {
        'deployment.object': 'PLC-01',
        'deployment.location': '主项目范围',
        'deployment.install': '',
        'deployment.cabling': '',
        'deployment.requirement': '',
        'deployment.note': '',
      },
    ],
    'link-design': [
      {
        'link.source': 'PLC-01',
        'link.target': 'SCADA-01',
        'link.scene': '核心业务场景',
        'link.type': '电口',
        'link.role': '接入链路',
        'link.redundant': '否',
        'link.sourceLocation': '',
        'link.targetLocation': '',
        'link.medium': '',
        'link.note': '',
      },
    ],
    'conduit-design': [
      {
        'derive.ruleThemes': '通道规则 / 安全规则',
        'conduit.source': '控制区',
        'conduit.target': '监控区',
        'conduit.scene': '核心业务场景',
        'conduit.purpose': '数据采集',
        'conduit.direction': '单向',
        'conduit.medium': '有线',
        'conduit.control': '受控开放',
        'conduit.delay': '毫秒级',
        'conduit.criticality': '高',
        'conduit.note': '',
      },
    ],
    'interconnect-design': [
      {
        'interconnect.source': '控制区',
        'interconnect.target': '监控区',
        'interconnect.structure': '边界设备互联',
        'interconnect.boundary': '',
        'interconnect.control': '',
        'interconnect.note': '',
      },
    ],
    'tech-selection': [
      {
        'derive.ruleThemes': '技术选择规则 / 性能规则 / 稳定性规则',
        'tech.name': '核心交换技术选择',
        'tech.category': '网络结构',
        'tech.technology': '工业以太网',
        'tech.scopeType': '区域',
        'tech.scopeTarget': '',
        'tech.scopeNote': '',
        'tech.goal': '',
        'tech.reason': '',
        'tech.alternative': '',
        'tech.alternativeReason': '',
        'tech.constraint': '',
        'tech.confirmStatus': '待确认',
        'tech.note': '',
      },
    ],
    'security-limit': [
      {
        'secLimit.name': '停机窗口限制',
        'secLimit.type': '停机窗口',
        'secLimit.object': '',
        'secLimit.required': '是',
        'secLimit.note': '',
      },
    ],
    'tech-selection': [
      {
        'tech.name': '核心交换技术选择',
        'tech.category': '网络结构',
        'tech.technology': '工业以太网',
        'tech.scopeType': '区域',
        'tech.scopeTarget': '',
        'tech.scopeNote': '',
        'tech.goal': '',
        'tech.reason': '',
        'tech.alternative': '',
        'tech.alternativeReason': '',
        'tech.constraint': '',
        'tech.confirmStatus': '待确认',
        'tech.note': '',
      },
    ],
    'delay-analysis': [
      {
        'delay.name': '控制区到监控区主链路',
        'delay.length': '',
        'delay.medium': '双绞线',
        'delay.hops': '',
        'delay.boundary': '无',
        'delay.dmz': '否',
        'delay.demand': '毫秒级',
        'delay.risk': '低',
        'delay.result': '',
      },
    ],
    'perf-evaluation': [
      {
        'perf.object': '控制区上联',
        'perf.type': '区域',
        'perf.load': '低',
        'perf.bandwidth': '百兆',
        'perf.path': '',
        'perf.risk': '低',
        'perf.result': '',
      },
    ],
    'topology-rules': demoTopologyRules,
    'layer-rules': demoLayerRules,
    'zone-rules': demoZoneRules,
    'conduit-rules': demoConduitRules,
    'boundary-rules': demoBoundaryRules,
    'technology-rules': demoTechnologyRules,
    'address-rules': demoAddressRules,
    'performance-rules': demoPerformanceRules,
    'stability-rules': demoStabilityRules,
    'redundancy-rules': demoRedundancyRules,
    'access-rules': demoAccessRules,
    'selection-rules': demoSelectionRules,
    'deployment-rules': demoDeploymentRules,
    'security-rules': demoSecurityRules,
    'scenario-rules': demoScenarioRules,
  };
}

export { createInitialCollections };
