import { useMemo, useState } from 'react';
import { buildEmptyDraft, buildInitialFormData, buildRecordFromDefaults, buildRecordFromDraft } from '../engine/methodologyHelpers.js';

function createInitialCollections() {
  return {
    'project-goal': [
      {
        'project.name': '工业网络规划项目',
        'project.customer': '待填写客户名称',
        'project.industry': '离散制造',
        'project.scope': '整厂',
        'project.goal': '新建',
        'project.delivery': '网络规划方案、结果输出与实施建议。',
        'project.owner': '待填写负责人',
        'project.confirmStatus': '待确认',
      },
    ],
    'scope-definition': [
      {
        'overview.name': '主项目范围',
        'overview.space': '1 个厂区 / 若干车间 / 关键业务区域',
        'overview.distribution': '中心区与现场区混合分布',
        'overview.cross': '存在跨区访问',
        'overview.scale': '中等规模',
        'overview.note': '',
      },
    ],
    'business-description': [
      {
        'scene.name': '核心业务场景',
        'scene.mode': '周期通信',
        'scene.source': '上层系统',
        'scene.target': '现场控制对象',
        'scene.purpose': '生产控制',
        'scene.medium': '有线',
        'scene.continuity': '高',
        'scene.note': '',
      },
    ],
    'asset-allocation': [
      {
        'asset.name': 'PLC-01',
        'asset.type': 'PLC',
        'asset.system': '控制系统',
        'asset.location': '现场控制柜',
        'asset.level': 'Level 1',
        'asset.status': '在用',
        'asset.access': '有线固定接入',
        'asset.criticality': '高',
        'asset.note': '',
      },
    ],
    'environment-conditions': [
      {
        'env.topic': '现场环境条件',
        'env.interference': '一般工业干扰',
        'env.install': '机柜 + 桥架部署',
        'env.distance': '中心区到现场区 100m~500m',
        'env.medium': '工业以太网',
        'env.power': '稳定交流供电',
        'env.wireless': '无',
        'env.note': '',
      },
    ],
    'implementation-constraints': [
      {
        'constraint.name': '预算约束',
        'constraint.type': '预算',
        'constraint.required': '是',
        'constraint.scope': '整项目建设范围',
        'constraint.existing': '需兼顾现网继承与分阶段实施',
        'constraint.note': '',
      },
    ],
    'security-scenario': [
      {
        'secScenario.name': '本地生产场景',
        'secScenario.type': '本地生产',
        'secScenario.scope': '现场控制网络',
        'secScenario.remote': '无',
        'secScenario.external': '无',
        'secScenario.note': '',
      },
    ],
    'exposure-analysis': [
      {
        'secExposure.name': 'PLC-01',
        'secExposure.relatedScenario': '本地生产场景',
        'secExposure.type': '远程接入',
        'secExposure.source': '工程维护或远程维护入口',
        'secExposure.control': '基础账号口令与访问控制',
        'secExposure.risk': '中',
        'secExposure.note': '',
      },
    ],
    'consequence-analysis': [
      {
        'secConsequence.name': 'PLC-01',
        'secConsequence.relatedScenario': '本地生产场景',
        'secConsequence.type': '生产中断',
        'secConsequence.impact': '异常访问或误操作可能导致生产中断',
        'secConsequence.severity': '高',
        'secConsequence.recovery': '需人工恢复与现场排查',
        'secConsequence.note': '',
      },
    ],
    'baseline-check': [
      {
        'secBaseline.type': '边界防护',
        'secBaseline.object': 'PLC-01',
        'secBaseline.status': '已具备',
        'secBaseline.evidence': '已有基本网络隔离措施',
        'secBaseline.gap': '基本满足',
        'secBaseline.note': '',
      },
    ],
    'key-asset-analysis': [
      {
        'secKey.name': 'PLC-01',
        'secKey.type': '控制器',
        'secKey.reason': '直接影响生产连续性',
        'secKey.focus': '边界访问、变更控制与稳定运行',
        'secKey.priority': '高',
        'secKey.note': '',
      },
    ],
    'design-principles': [
      {
        'derive.ruleThemes': '场景规则 / 安全规则 / 技术选择规则',
        'principle.category': '区域划分思路',
        'principle.main': '优先按物理区域与业务边界划分',
        'principle.scope': '中心区、控制区、监控区与边界区',
        'principle.basis': '连续生产与边界治理要求',
        'principle.desc': '先明确边界，再收敛结构与接入方式',
        'principle.note': '',
      },
    ],
    'network-topology': [
      {
        'derive.ruleThemes': '拓扑规则 / 场景规则 / 冗余规则',
        'topology.object': '全厂主干网络',
        'topology.type': '星型',
        'topology.backbone': '中心交换节点统一汇聚',
        'topology.access': '现场控制柜和业务终端就近接入',
        'topology.scope': '中心区与现场区',
        'topology.basis': '便于实施、运维和后续扩展',
        'topology.tech': '工业以太网',
        'topology.note': '',
      },
    ],
    'layer-design': [
      {
        'derive.ruleThemes': '分层规则 / 场景规则',
        'layer.object': '车间汇聚层',
        'layer.mode': '二层',
        'layer.structure': '核心 / 汇聚 / 接入',
        'layer.policy': '按层组织访问与边界控制',
        'layer.scope': '中心区与车间区域',
        'layer.note': '',
      },
    ],
    'segmentation-plan': [
      {
        'seg.object': '控制区网段',
        'seg.purpose': '控制通信',
        'seg.range': '192.168.10.0/24',
        'seg.margin': '预留 20%',
        'seg.note': '',
      },
    ],
    'performance-design': [
      {
        'performance.object': '控制区主链路',
        'performance.latency': '毫秒级',
        'performance.bandwidth': '千兆',
        'performance.clock': '10ms 周期',
        'performance.measure': '关键控制流量优先保障',
        'performance.service': '控制通信',
        'performance.delay': '≤10ms',
        'performance.risk': '广播或异常访问影响时延',
        'performance.note': '',
      },
    ],
    'stability-design': [
      {
        'stability.object': '控制系统主链路',
        'stability.target': '连续稳定运行',
        'stability.risk': '误操作与边界异常',
        'stability.measure': '配置基线与变更审批',
        'stability.control': '日志审计与链路监测',
        'stability.maintain': '窗口期维护',
        'stability.note': '',
      },
    ],
    'redundancy-design': [
      {
        'redundancy.object': '主干光纤链路',
        'redundancy.target': '单点故障不中断业务',
        'redundancy.mode': '主备',
        'redundancy.switch': '故障自动或人工切换',
        'redundancy.note': '',
      },
    ],
    'access-design': [
      {
        'access.object': 'PLC-01',
        'access.type': '有线',
        'access.scope': '现场控制柜',
        'access.limit': '仅允许控制网络设备接入',
        'access.reason': '保证控制流量稳定与边界清晰',
        'access.note': '',
      },
    ],
    'selection-design': [
      {
        'selection.object': 'PLC-01',
        'selection.demand': '控制通信',
        'selection.capability': '工业协议支持、稳定运行、环境适应',
        'selection.result': '工业交换机接入',
        'selection.reason': '满足工业现场稳定性与维护要求',
        'selection.note': '',
      },
    ],
    'deployment-design': [
      {
        'deployment.object': 'PLC-01',
        'deployment.location': '主项目范围',
        'deployment.install': '',
        'deployment.cabling': '',
        'deployment.requirement': '',
        'deployment.note': '',
      },
    ],
    'link-design': [
      {
        'link.source': 'PLC-01',
        'link.target': 'SCADA-01',
        'link.scene': '核心业务场景',
        'link.type': '电口',
        'link.role': '接入链路',
        'link.redundant': '否',
        'link.sourceLocation': '',
        'link.targetLocation': '',
        'link.medium': '',
        'link.note': '',
      },
    ],
    'conduit-design': [
      {
        'derive.ruleThemes': '通道规则 / 安全规则',
        'conduit.source': '控制区',
        'conduit.target': '监控区',
        'conduit.scene': '核心业务场景',
        'conduit.purpose': '数据采集',
        'conduit.direction': '单向',
        'conduit.medium': '有线',
        'conduit.control': '受控开放',
        'conduit.delay': '毫秒级',
        'conduit.criticality': '高',
        'conduit.note': '',
      },
    ],
    'interconnect-design': [
      {
        'interconnect.source': '控制区',
        'interconnect.target': '监控区',
        'interconnect.structure': '边界设备互联',
        'interconnect.boundary': '',
        'interconnect.control': '',
        'interconnect.note': '',
      },
    ],
    'tech-selection': [
      {
        'derive.ruleThemes': '技术选择规则 / 性能规则 / 稳定性规则',
        'tech.name': '核心交换技术选择',
        'tech.category': '网络结构',
        'tech.technology': '工业以太网',
        'tech.scopeType': '区域',
        'tech.scopeTarget': '',
        'tech.scopeNote': '',
        'tech.goal': '',
        'tech.reason': '',
        'tech.alternative': '',
        'tech.alternativeReason': '',
        'tech.constraint': '',
        'tech.confirmStatus': '待确认',
        'tech.note': '',
      },
    ],
    'security-limit': [
      {
        'secLimit.name': '停机窗口限制',
        'secLimit.type': '停机窗口',
        'secLimit.object': '',
        'secLimit.required': '是',
        'secLimit.note': '',
      },
    ],
    'tech-selection': [
      {
        'tech.name': '核心交换技术选择',
        'tech.category': '网络结构',
        'tech.technology': '工业以太网',
        'tech.scopeType': '区域',
        'tech.scopeTarget': '',
        'tech.scopeNote': '',
        'tech.goal': '',
        'tech.reason': '',
        'tech.alternative': '',
        'tech.alternativeReason': '',
        'tech.constraint': '',
        'tech.confirmStatus': '待确认',
        'tech.note': '',
      },
    ],
    'delay-analysis': [
      {
        'delay.name': '控制区到监控区主链路',
        'delay.length': '',
        'delay.medium': '双绞线',
        'delay.hops': '',
        'delay.boundary': '无',
        'delay.dmz': '否',
        'delay.demand': '毫秒级',
        'delay.risk': '低',
        'delay.result': '',
      },
    ],
    'perf-evaluation': [
      {
        'perf.object': '控制区上联',
        'perf.type': '区域',
        'perf.load': '低',
        'perf.bandwidth': '百兆',
        'perf.path': '',
        'perf.risk': '低',
        'perf.result': '',
      },
    ],
    'topology-rules': [
      {
        'planningRule.name': '线型对象优先环网',
        'planningRule.domain': '网络设计',
        'planningRule.category': '拓扑设计',
        'planningRule.trigger': '设备沿产线或输送链路线性分布，且业务连续性要求高。',
        'planningRule.scene': '线型产线 / 连续排布设备 / 冗余要求高',
        'planningRule.recommend': '优先采用工业环网，并明确冗余切换方式和边界节点位置。',
        'planningRule.avoid': '避免在对象高度集中场景中机械套用环网，导致链路复杂度增加。',
        'planningRule.reason': '环网更适合线型部署，布线顺势且能兼顾冗余。',
        'planningRule.scope': '影响网络拓扑、交换机选型、链路设计、冗余设计。',
        'planningRule.example': '汽车焊装线、输送线、包装线等沿线设备网络。',
        'planningRule.note': '若存在多个线体汇聚，应与分层规则结合判断。',
      },
      {
        'planningRule.name': '集中对象优先星型',
        'planningRule.domain': '网络设计',
        'planningRule.category': '拓扑设计',
        'planningRule.trigger': '设备集中分布，上联关系清晰，现场布线条件较好。',
        'planningRule.scene': '集中设备区 / 机柜集中 / 单房间部署',
        'planningRule.recommend': '优先采用星型结构，由接入层或对象直接上联中心节点。',
        'planningRule.avoid': '避免为了形式统一强行做环网，增加不必要的节点和维护复杂度。',
        'planningRule.reason': '星型结构最直接，便于故障定位和容量管理。',
        'planningRule.scope': '影响拓扑形态、布线方式、中心交换设备接口规划。',
        'planningRule.example': '监控室、机房、集中控制室等对象集中场景。',
        'planningRule.note': '若中心节点成为单点，应结合冗余规则进一步处理。',
      },
      {
        'planningRule.name': '多区域场景优先混合拓扑',
        'planningRule.domain': '网络设计',
        'planningRule.category': '拓扑设计',
        'planningRule.trigger': '厂区存在多个功能区、多个车间或多楼栋分布。',
        'planningRule.scene': '多区域厂区 / 多车间 / 多楼栋',
        'planningRule.recommend': '优先采用核心汇聚星型 + 区域内部局部环网或星型的混合拓扑。',
        'planningRule.avoid': '避免用单一拓扑覆盖全厂，导致结构过大且边界不清。',
        'planningRule.reason': '混合拓扑更适合兼顾区域差异、扩展性和边界管理。',
        'planningRule.scope': '影响总体拓扑、分层设计、区域互联和边界实现。',
        'planningRule.example': '整厂级制造网络、公用工程 + 生产控制混合网络。',
        'planningRule.note': '应先明确区域边界，再决定区域内部采用何种局部拓扑。',
      },
    ],
    'layer-rules': [
      {
        'planningRule.name': '大规模厂区引入汇聚层',
        'planningRule.domain': '网络设计',
        'planningRule.category': '分层设计',
        'planningRule.trigger': '厂区范围大、对象数量多、跨区域布线明显。',
        'planningRule.scene': '大规模厂区 / 多车间 / 多楼栋',
        'planningRule.recommend': '设置汇聚层，按区域或功能块汇聚后再上联核心层。',
        'planningRule.avoid': '避免所有接入点直接上联核心，造成核心口数和管理复杂度失控。',
        'planningRule.reason': '汇聚层有利于控制规模、清晰层级并降低主干复杂度。',
        'planningRule.scope': '影响分层结构、主干布线、交换机数量与容量规划。',
        'planningRule.example': '整厂级项目、跨楼栋项目、多个系统统一汇聚项目。',
        'planningRule.note': '汇聚层划分应尽量与区域或系统边界保持一致。',
      },
      {
        'planningRule.name': '小规模场景接入可直上核心',
        'planningRule.domain': '网络设计',
        'planningRule.category': '分层设计',
        'planningRule.trigger': '对象数量有限、布线资源充足、核心接口能力足够。',
        'planningRule.scene': '小规模厂区 / 单车间 / 集中部署',
        'planningRule.recommend': '采用两层甚至单层简化结构，接入层可直接上联核心。',
        'planningRule.avoid': '避免为了形式追求完整三层，导致结构虚胖。',
        'planningRule.reason': '简化结构便于实施、维护和故障定位，也更经济。',
        'planningRule.scope': '影响核心接口规划、布线方式、设备数量和维护复杂度。',
        'planningRule.example': '单产线改造、单控制室、小型能源站。',
        'planningRule.note': '若后续扩展可能较大，应预留向汇聚层演进的空间。',
      },
      {
        'planningRule.name': '多系统汇聚场景分层优先按功能划分',
        'planningRule.domain': '网络设计',
        'planningRule.category': '分层设计',
        'planningRule.trigger': 'MES、SCADA、历史库、FMCS 等多个系统同时接入。',
        'planningRule.scene': '多系统汇聚 / 平台集中监控 / 上下游系统集成',
        'planningRule.recommend': '优先按系统角色和访问关系分层，再确定核心与汇聚职责。',
        'planningRule.avoid': '避免单纯按设备数量分层，忽略系统交互特征。',
        'planningRule.reason': '功能驱动的分层更利于后续边界控制和运维管理。',
        'planningRule.scope': '影响分层逻辑、区域划分、边界设计和技术选择。',
        'planningRule.example': 'MES 与产线控制系统、FMCS 与公用工程子系统汇聚。',
        'planningRule.note': '建议与区域与边界规则联动判断。',
      },
    ],
    'zone-rules': [
      {
        'planningRule.name': '关键控制对象优先独立成区',
        'planningRule.domain': '安全设计',
        'planningRule.category': '区域划分',
        'planningRule.trigger': '关键控制对象与一般监控、办公或维护对象在职责和风险上明显不同。',
        'planningRule.scene': '控制系统 / 关键控制区 / 高风险对象',
        'planningRule.recommend': '优先将关键控制对象独立成区，并明确边界职责。',
        'planningRule.avoid': '避免将关键控制对象与一般服务对象混放在同一区域。',
        'planningRule.reason': '独立成区便于边界控制、访问审计和风险隔离。',
        'planningRule.scope': '适用于控制区、保护区、关键服务区划分。',
        'planningRule.alternative': '若规模过小无法独立成区，可先逻辑隔离并保留后续演进空间。',
        'planningRule.example': 'PLC、控制服务器、关键 HMI 独立控制区。',
        'planningRule.note': '需结合边界互联规则一并判断。',
      },
      {
        'planningRule.name': '运维对象优先单独管理分区',
        'planningRule.domain': '安全设计',
        'planningRule.category': '区域划分',
        'planningRule.trigger': '维护终端、跳板机、工程师站承担跨区管理职责。',
        'planningRule.scene': '远程运维 / 本地运维 / 跨区调试',
        'planningRule.recommend': '优先将运维对象归入独立运维区或独立管理分区。',
        'planningRule.avoid': '避免维护终端长期混接在控制区或普通监控区。',
        'planningRule.reason': '运维对象天然具备跨区访问能力，应重点约束。',
        'planningRule.scope': '适用于远程维护、本地工程师站和第三方维护场景。',
        'planningRule.alternative': '在极小规模项目中，可先逻辑隔离并强化账户与审计。',
        'planningRule.example': '工程师站、跳板机、远程维护代理单独成区。',
        'planningRule.note': '与安全规则和通道规则联动。',
      },
      {
        'planningRule.name': '区域划分优先服从职责边界',
        'planningRule.domain': '网络设计',
        'planningRule.category': '区域划分',
        'planningRule.trigger': '同一物理区域内存在不同职责对象或不同管理边界。',
        'planningRule.scene': '混合机柜 / 混合控制室 / 多角色对象共存',
        'planningRule.recommend': '优先按职责边界划分区域，再决定物理部署细节。',
        'planningRule.avoid': '避免只按空间位置划区，忽略职责差异。',
        'planningRule.reason': '职责边界决定访问关系和后续控制要求。',
        'planningRule.scope': '适用于职责差异明显但空间混布的场景。',
        'planningRule.alternative': '若职责一致且访问关系简单，可按物理位置简化划区。',
        'planningRule.example': '同一控制室内区分控制、监控与维护对象。',
        'planningRule.note': '与场景规则协同判断。',
      },
    ],
    'conduit-rules': [
      {
        'planningRule.name': '跨区访问优先收敛通道',
        'planningRule.domain': '安全设计',
        'planningRule.category': '通道设计',
        'planningRule.trigger': '区域之间存在明确访问需求，且访问对象与方向相对固定。',
        'planningRule.scene': '跨区访问 / 远程维护 / 上下游接口',
        'planningRule.recommend': '优先通过收敛通道组织跨区访问，并明确方向、协议与控制策略。',
        'planningRule.avoid': '避免跨区链路任意直通，导致访问路径不可控。',
        'planningRule.reason': '通道收敛有助于统一审计、统一控制和统一维护。',
        'planningRule.scope': '适用于区域间固定访问关系的场景。',
        'planningRule.alternative': '若访问关系极少且可控，可采用单点受控互联。',
        'planningRule.example': 'DMZ 到控制区的远程维护通道。',
        'planningRule.note': '应与边界互联规则和安全规则联动。',
      },
      {
        'planningRule.name': '高风险访问优先单独控制通道',
        'planningRule.domain': '安全设计',
        'planningRule.category': '通道设计',
        'planningRule.trigger': '访问路径涉及第三方、远程运维或高权限维护对象。',
        'planningRule.scene': '第三方维护 / 高权限运维 / 临时调试',
        'planningRule.recommend': '为高风险访问建立独立受控通道，并单独配置认证和审计策略。',
        'planningRule.avoid': '避免与普通业务通道共用控制策略。',
        'planningRule.reason': '高风险访问需要更高粒度的控制和审计。',
        'planningRule.scope': '适用于高权限或高风险访问链路。',
        'planningRule.alternative': '若高风险访问频率极低，可采用临时授权通道。',
        'planningRule.example': '第三方厂家远程维护独立通道。',
        'planningRule.note': '与安全规则协同。',
      },
      {
        'planningRule.name': '固定交互优先固定通道策略',
        'planningRule.domain': '网络设计',
        'planningRule.category': '通道设计',
        'planningRule.trigger': '跨区交互对象、方向和协议较稳定。',
        'planningRule.scene': '固定系统接口 / 稳定跨区通信',
        'planningRule.recommend': '优先固化通道方向、协议范围和控制点。',
        'planningRule.avoid': '避免将长期固定交互设计成临时开放模式。',
        'planningRule.reason': '固定策略有助于长期运维与审计。',
        'planningRule.scope': '适用于稳定接口型通道。',
        'planningRule.alternative': '若交互关系频繁变化，可采用受控白名单策略。',
        'planningRule.example': 'MES 到控制区接口服务的固定通道。',
        'planningRule.note': '与边界互联规则联动。',
      },
    ],
    'boundary-rules': [
      {
        'planningRule.name': '跨边界互联优先设控制点',
        'planningRule.domain': '边界设计',
        'planningRule.category': '边界互联',
        'planningRule.trigger': '不同安全属性、不同职责或不同管理域之间需要互联。',
        'planningRule.scene': '控制区与 DMZ / 生产网与办公网 / 多管理域互联',
        'planningRule.recommend': '在边界处设置明确控制点，定义互联结构与控制策略。',
        'planningRule.avoid': '避免通过普通二层直通跨越关键边界。',
        'planningRule.reason': '边界控制点是实现访问策略、审计和隔离的关键位置。',
        'planningRule.scope': '适用于安全边界、系统边界和管理边界互联。',
        'planningRule.alternative': '若边界极其简单，可采用最小化互联，但仍需可审计。',
        'planningRule.example': '控制区通过工业防火墙与上层区互联。',
        'planningRule.note': '与通道规则一起决定跨区实现方式。',
      },
      {
        'planningRule.name': '办公与控制互联优先经过中间区',
        'planningRule.domain': '安全设计',
        'planningRule.category': '边界互联',
        'planningRule.trigger': '办公网、信息网与控制相关网络存在数据或访问关系。',
        'planningRule.scene': '办公网 / 信息网 / 控制网互联',
        'planningRule.recommend': '优先通过 DMZ 或中间区承接互联，不直接跨越边界。',
        'planningRule.avoid': '避免办公网直达控制区。',
        'planningRule.reason': '中间区有助于隔离风险并统一控制。',
        'planningRule.scope': '适用于 IT/OT 互联场景。',
        'planningRule.alternative': '若仅有单向数据发布，可采用单向隔离方式。',
        'planningRule.example': '办公网经 DMZ 访问生产数据展示系统。',
        'planningRule.note': '与安全规则联动。',
      },
      {
        'planningRule.name': '边界设备优先承担边界职责',
        'planningRule.domain': '边界设计',
        'planningRule.category': '边界互联',
        'planningRule.trigger': '互联点既承担连通，又承担控制、审计或转换职责。',
        'planningRule.scene': '工业防火墙 / 代理网关 / 边界交换设备',
        'planningRule.recommend': '优先由边界设备承担边界职责，不将边界能力分散到普通接入设备。',
        'planningRule.avoid': '避免边界控制能力散落在多个普通节点。',
        'planningRule.reason': '边界职责集中有利于统一策略与可维护性。',
        'planningRule.scope': '适用于边界策略较复杂的互联点。',
        'planningRule.alternative': '在极简场景中，可采用少量受控节点临时承担边界职责。',
        'planningRule.example': '工业防火墙承担控制区到上层区的互联与策略控制。',
        'planningRule.note': '与选型规则、部署规则一并判断。',
      },
    ],
    'technology-rules': [
      {
        'planningRule.name': '技术选择优先服从场景约束',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '多种技术方案都能实现目标，但现场约束不同。',
        'planningRule.scene': 'TSN / Wi-Fi / 5G / APL / 工业以太网',
        'planningRule.recommend': '先明确时延、可靠性、布线、维护和安全约束，再决定技术路线。',
        'planningRule.avoid': '避免因为技术流行度而直接选型。',
        'planningRule.reason': '技术能力必须与现场约束和维护能力匹配。',
        'planningRule.scope': '适用于技术路线存在多选项的项目。',
        'planningRule.alternative': '若条件不成熟，可采用成熟技术先落地并预留演进能力。',
        'planningRule.example': '高时敏场景选 TSN，移动对象场景评估 Wi-Fi/5G。',
        'planningRule.note': '需与性能规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '成熟性优先于概念先进性',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '项目实施窗口紧、团队经验有限或维护体系尚不成熟。',
        'planningRule.scene': '改造项目 / 交付窗口紧 / 维护能力有限',
        'planningRule.recommend': '优先采用成熟、可维护、已验证的技术路线。',
        'planningRule.avoid': '避免为追求先进性而引入高不确定性技术。',
        'planningRule.reason': '工业项目更重视可交付与可维护。',
        'planningRule.scope': '适用于交付压力大或维护资源有限的项目。',
        'planningRule.alternative': '若项目具备试点属性，可局部引入新技术验证。',
        'planningRule.example': '优先工业以太网而非未验证的新型无线方案。',
        'planningRule.note': '与部署规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '无线技术优先用于移动与难布线场景',
        'planningRule.domain': '技术选择',
        'planningRule.category': '技术路线',
        'planningRule.trigger': '对象移动、布线困难或临时接入需求明显。',
        'planningRule.scene': 'AGV / 移动物料 / 临时接入 / 广域覆盖',
        'planningRule.recommend': '优先评估 Wi-Fi 或 5G 等无线技术，并同步评估安全与漫游能力。',
        'planningRule.avoid': '避免在固定关键控制链路上盲目使用无线。',
        'planningRule.reason': '无线的优势在于灵活性，但代价是可控性与稳定性评估要求更高。',
        'planningRule.scope': '适用于移动对象或布线困难场景。',
        'planningRule.alternative': '若可布线且对象固定，应优先采用有线方案。',
        'planningRule.example': 'AGV 调度网络、移动巡检终端网络。',
        'planningRule.note': '需与性能规则和安全规则联动。',
      },
    ],
    'address-rules': [
      {
        'planningRule.name': '地址规划优先按区域与用途分段',
        'planningRule.domain': '地址规划',
        'planningRule.category': '分段设计',
        'planningRule.trigger': '网络中存在多个区域、多个对象类型或不同运维需求。',
        'planningRule.scene': '多区域厂区 / 多系统并行 / 长周期运维项目',
        'planningRule.recommend': '按区域、用途、对象类型组织地址分段，并预留扩展余量。',
        'planningRule.avoid': '避免全网混用连续地址，导致边界和用途难以识别。',
        'planningRule.reason': '分段规则清晰有助于实施、运维和扩容。',
        'planningRule.scope': '适用于需要长期维护和持续扩展的网络。',
        'planningRule.alternative': '在极小规模场景下，可先简化分段，但应保留演进空间。',
        'planningRule.example': '按控制区、监控区、维护区分别规划 VLAN 与网段。',
        'planningRule.note': '应与区域规则和边界规则协同。',
      },
      {
        'planningRule.name': '关键对象优先固定地址规划',
        'planningRule.domain': '地址规划',
        'planningRule.category': '地址分配',
        'planningRule.trigger': '对象承担关键控制、关键服务或关键边界职责。',
        'planningRule.scene': 'PLC / HMI / 历史库 / 边界设备 / 核心交换机',
        'planningRule.recommend': '优先为关键对象规划固定地址，并明确用途与管理归属。',
        'planningRule.avoid': '避免关键对象长期依赖动态分配地址。',
        'planningRule.reason': '固定地址便于审计、维护、策略绑定和故障定位。',
        'planningRule.scope': '适用于关键业务对象与关键网络节点。',
        'planningRule.alternative': '普通终端可在受控前提下采用 DHCP。',
        'planningRule.example': 'PLC、服务器、防火墙使用固定地址。',
        'planningRule.note': '应与接入规则和安全规则联动。',
      },
      {
        'planningRule.name': '地址预留优先按扩展方向规划',
        'planningRule.domain': '地址规划',
        'planningRule.category': '扩展预留',
        'planningRule.trigger': '项目存在后续扩产、扩线、扩系统预期。',
        'planningRule.scene': '中长期建设 / 分阶段交付 / 平台型项目',
        'planningRule.recommend': '优先按区域扩展方向和对象增长方式预留地址空间。',
        'planningRule.avoid': '避免只按当前数量刚性切分，导致后期重编址。',
        'planningRule.reason': '地址预留是长期可维护性的关键基础。',
        'planningRule.scope': '适用于有明显扩展预期的项目。',
        'planningRule.alternative': '若项目生命周期短且边界固定，可适度简化预留。',
        'planningRule.example': '为未来新增产线预留独立地址段。',
        'planningRule.note': '应与场景规则和部署规则协同。',
      },
    ],
    'performance-rules': [
      {
        'planningRule.name': '实时控制链路优先单独评估性能',
        'planningRule.domain': '性能设计',
        'planningRule.category': '实时性',
        'planningRule.trigger': '链路承载控制闭环、时钟同步或高实时要求业务。',
        'planningRule.scene': '运动控制 / 高速控制 / 精确时钟场景',
        'planningRule.recommend': '将关键实时链路单独识别并评估时延、抖动、带宽和同步要求。',
        'planningRule.avoid': '避免将高实时链路与普通监控流量混为一谈。',
        'planningRule.reason': '关键链路对实时性更敏感，需单独收敛性能设计。',
        'planningRule.scope': '适用于闭环控制和高实时业务链路。',
        'planningRule.alternative': '若实时要求不高，可采用通用工业以太网能力。',
        'planningRule.example': '机器人控制链路、同步采集链路。',
        'planningRule.note': '与技术选择规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '主干链路优先按峰值流量评估带宽',
        'planningRule.domain': '性能设计',
        'planningRule.category': '带宽评估',
        'planningRule.trigger': '主干链路汇聚多个系统或多个区域流量。',
        'planningRule.scene': '核心上联 / 汇聚上联 / 跨区主干',
        'planningRule.recommend': '优先按峰值并发流量和未来增长空间评估主干带宽。',
        'planningRule.avoid': '避免只按当前平均流量选带宽。',
        'planningRule.reason': '主干链路的瓶颈会放大整个系统的性能风险。',
        'planningRule.scope': '适用于汇聚与主干链路设计。',
        'planningRule.alternative': '若业务流量长期平稳，可按保守冗余系数规划。',
        'planningRule.example': '汇聚层到核心层上联按峰值并发评估千兆/万兆。',
        'planningRule.note': '与分层规则和冗余规则联动。',
      },
      {
        'planningRule.name': '混合业务优先区分控制流与监控流',
        'planningRule.domain': '性能设计',
        'planningRule.category': '业务区分',
        'planningRule.trigger': '链路同时承载控制、监控、视频、运维等多类业务。',
        'planningRule.scene': '综合业务网络 / 多系统融合网络',
        'planningRule.recommend': '优先识别并区分关键控制流与一般监控流，必要时做优先级或隔离设计。',
        'planningRule.avoid': '避免混合业务完全等价承载。',
        'planningRule.reason': '不同业务对时延、带宽和抖动容忍度不同。',
        'planningRule.scope': '适用于融合型工业网络。',
        'planningRule.alternative': '在业务单一场景中可简化性能分类。',
        'planningRule.example': '控制数据与视频流分级承载。',
        'planningRule.note': '与拓扑规则和技术选择规则联动。',
      },
    ],
    'stability-rules': [
      {
        'planningRule.name': '关键网络优先控制变化面',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '变更控制',
        'planningRule.trigger': '网络承载关键生产业务，且停机窗口短。',
        'planningRule.scene': '连续生产 / 停机窗口短 / 高连续性要求',
        'planningRule.recommend': '优先减少中间变化点，控制配置复杂度，并明确回退路径。',
        'planningRule.avoid': '避免在高连续性网络中引入过多复杂机制。',
        'planningRule.reason': '稳定性优先场景中，复杂度本身就是风险来源。',
        'planningRule.scope': '适用于关键生产网络与连续生产场景。',
        'planningRule.alternative': '若容错空间大，可适度增加复杂机制换取灵活性。',
        'planningRule.example': '不停产改造的核心网络。',
        'planningRule.note': '应与冗余规则、部署规则一并判断。',
      },
      {
        'planningRule.name': '协议机制优先保持必要最简',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '协议复杂度',
        'planningRule.trigger': '网络中拟引入多种控制、冗余、路由或安全机制。',
        'planningRule.scene': '综合工业网络 / 多协议混合网络',
        'planningRule.recommend': '优先保留必要且可维护的协议机制组合。',
        'planningRule.avoid': '避免无明确收益地堆叠机制。',
        'planningRule.reason': '机制越多，调试难度与故障面越大。',
        'planningRule.scope': '适用于需要兼顾可维护性的网络。',
        'planningRule.alternative': '在试点项目中可局部验证复杂机制。',
        'planningRule.example': '仅保留必要的环网与 VLAN，不叠加过多特性。',
        'planningRule.note': '与技术选择规则和冗余规则联动。',
      },
      {
        'planningRule.name': '改造项目优先兼容现网稳定边界',
        'planningRule.domain': '稳定性设计',
        'planningRule.category': '现网继承',
        'planningRule.trigger': '项目为改造类，且现网已有可稳定运行部分。',
        'planningRule.scene': '存量改造 / 分阶段替换 / 不停产切换',
        'planningRule.recommend': '优先保留已稳定的边界与结构，逐步替换高风险部分。',
        'planningRule.avoid': '避免在改造期全面推翻现网。',
        'planningRule.reason': '改造项目中最主要的风险来自过大变化面。',
        'planningRule.scope': '适用于存量系统改造项目。',
        'planningRule.alternative': '若现网问题严重，可局部并行新建后切换。',
        'planningRule.example': '先保留既有骨干，再分区替换接入层。',
        'planningRule.note': '与部署规则和实施约束联动。',
      },
    ],
    'redundancy-rules': [
      {
        'planningRule.name': '关键链路冗余优先基于业务连续性确定',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '链路冗余',
        'planningRule.trigger': '链路中断会直接影响关键业务连续性。',
        'planningRule.scene': '关键控制链路 / 核心上联 / 跨区域主干',
        'planningRule.recommend': '优先按业务连续性要求决定是否采用链路、设备或协议层冗余。',
        'planningRule.avoid': '避免不分主次地全网堆叠冗余。',
        'planningRule.reason': '冗余应服务于关键业务，而非为了形式完整。',
        'planningRule.scope': '适用于关键主干与关键控制对象。',
        'planningRule.alternative': '若业务可中断，可采用快速恢复而非双活冗余。',
        'planningRule.example': '控制区核心上联采用双链路或环网冗余。',
        'planningRule.note': '与拓扑规则和稳定性规则联动。',
      },
      {
        'planningRule.name': '主干冗余优先集中在关键层级',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '层级冗余',
        'planningRule.trigger': '网络包含核心、汇聚、接入等多个层级，且业务重要性不同。',
        'planningRule.scene': '分层网络 / 多层主干网络',
        'planningRule.recommend': '优先将冗余能力集中在核心层和关键汇聚层。',
        'planningRule.avoid': '避免在低价值层级盲目铺满冗余。',
        'planningRule.reason': '关键层级的冗余收益最大。',
        'planningRule.scope': '适用于分层网络主干设计。',
        'planningRule.alternative': '小规模场景可采用单层快速恢复设计。',
        'planningRule.example': '核心双机、关键汇聚双上联。',
        'planningRule.note': '与分层规则联动。',
      },
      {
        'planningRule.name': '冗余模式优先匹配维护能力',
        'planningRule.domain': '冗余设计',
        'planningRule.category': '冗余模式',
        'planningRule.trigger': '存在多种冗余协议或模式可选，但团队运维能力差异明显。',
        'planningRule.scene': '环网协议 / 双活 / 链路保护 / 协议冗余',
        'planningRule.recommend': '优先采用团队能理解、能维护、能排障的冗余模式。',
        'planningRule.avoid': '避免选择运维团队无法掌握的复杂冗余机制。',
        'planningRule.reason': '无法维护的冗余会变成新的风险源。',
        'planningRule.scope': '适用于冗余模式有多种选择的项目。',
        'planningRule.alternative': '可先采用简单冗余，再逐步演进。',
        'planningRule.example': '优先简化环网或双链路，而非复杂双活结构。',
        'planningRule.note': '与稳定性规则和技术选择规则联动。',
      },
    ],
    'access-rules': [
      {
        'planningRule.name': '对象接入优先按对象特性分类',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '网络中存在控制对象、监控对象、维护对象等多类终端。',
        'planningRule.scene': '混合对象接入 / 多角色终端接入',
        'planningRule.recommend': '按对象特性与访问权限组织接入方式和接入边界。',
        'planningRule.avoid': '避免只按物理位置接入而忽略对象角色差异。',
        'planningRule.reason': '对象角色决定了访问需求、权限边界与维护方式。',
        'planningRule.scope': '适用于对象类型差异明显的项目。',
        'planningRule.alternative': '若对象单一，可按位置优先接入。',
        'planningRule.example': 'PLC、摄像头、维护终端采用不同接入策略。',
        'planningRule.note': '需与区域规则和安全规则联动。',
      },
      {
        'planningRule.name': '关键控制对象优先有线独立接入',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '对象承担关键控制、关键联锁或实时闭环职责。',
        'planningRule.scene': 'PLC / DCS / 联锁控制 / 关键控制服务器',
        'planningRule.recommend': '优先采用有线、独立、可控的接入方式。',
        'planningRule.avoid': '避免关键控制对象依赖共享无线或混杂接入环境。',
        'planningRule.reason': '关键控制对象对稳定性、可控性和排障路径要求更高。',
        'planningRule.scope': '适用于关键控制和关键服务对象。',
        'planningRule.alternative': '若必须无线接入，应单独评估实时性与可靠性。',
        'planningRule.example': 'PLC 采用独立交换端口和专属 VLAN 接入。',
        'planningRule.note': '与性能规则和安全规则联动。',
      },
      {
        'planningRule.name': '维护终端优先受控接入',
        'planningRule.domain': '接入设计',
        'planningRule.category': '对象接入',
        'planningRule.trigger': '对象用于调试、维护、升级或排障。',
        'planningRule.scene': '工程师站 / 维护笔记本 / 调试终端',
        'planningRule.recommend': '优先通过受控端口、受控 VLAN 或受控维护区接入。',
        'planningRule.avoid': '避免维护终端长期接入生产控制端口。',
        'planningRule.reason': '维护对象具有高变更与高越权风险。',
        'planningRule.scope': '适用于所有运维与临时调试对象。',
        'planningRule.alternative': '在临时应急场景下可短期直连，但需严格留痕。',
        'planningRule.example': '维护笔记本通过专用维护口接入。',
        'planningRule.note': '与安全规则和区域规则联动。',
      },
    ],
    'selection-rules': [
      {
        'planningRule.name': '设备选型优先匹配场景能力缺口',
        'planningRule.domain': '设备选型',
        'planningRule.category': '能力匹配',
        'planningRule.trigger': '项目对接口数量、环境等级、冗余、协议或管理能力有明确要求。',
        'planningRule.scene': '工业交换机 / 边界设备 / 接入设备选型',
        'planningRule.recommend': '先定义能力缺口，再选择满足能力要求的设备类型或型号。',
        'planningRule.avoid': '避免先定型号再倒推能力说明。',
        'planningRule.reason': '能力驱动的选型更稳定，也便于后续复用。',
        'planningRule.scope': '适用于核心、汇聚、接入及边界设备选型。',
        'planningRule.alternative': '若预算严格，可分层次满足关键能力与非关键能力。',
        'planningRule.example': '根据温度、端口、电源冗余要求确定交换机系列。',
        'planningRule.note': '与性能、稳定性和部署规则联动。',
      },
      {
        'planningRule.name': '边界设备优先匹配控制能力',
        'planningRule.domain': '设备选型',
        'planningRule.category': '边界设备',
        'planningRule.trigger': '设备承担访问控制、审计、协议转换或边界隔离职责。',
        'planningRule.scene': '工业防火墙 / 安全网关 / 代理服务器',
        'planningRule.recommend': '优先匹配访问控制、审计留痕和可维护能力。',
        'planningRule.avoid': '避免仅按转发性能选择边界设备。',
        'planningRule.reason': '边界设备的价值在于控制能力，而不只是转发能力。',
        'planningRule.scope': '适用于所有边界类设备。',
        'planningRule.alternative': '在简单互联场景下可采用轻量边界节点，但仍需可审计。',
        'planningRule.example': '工业防火墙需要支持规则审计和细粒度访问控制。',
        'planningRule.note': '与边界规则、安全规则联动。',
      },
      {
        'planningRule.name': '工业现场选型优先满足环境适应性',
        'planningRule.domain': '设备选型',
        'planningRule.category': '环境适配',
        'planningRule.trigger': '现场存在高温、高湿、振动、防爆、电磁干扰等环境要求。',
        'planningRule.scene': '严苛工业环境 / 防爆区域 / 户外柜体',
        'planningRule.recommend': '优先匹配环境等级、安装方式和供电条件。',
        'planningRule.avoid': '避免用商用设备硬套工业现场。',
        'planningRule.reason': '环境适配性直接影响设备寿命和故障率。',
        'planningRule.scope': '适用于工业现场设备选型。',
        'planningRule.alternative': '若环境可控，可适度放宽工业等级要求。',
        'planningRule.example': '防爆区设备需满足防爆要求与耐环境等级。',
        'planningRule.note': '与部署规则联动。',
      },
    ],
    'deployment-rules': [
      {
        'planningRule.name': '部署设计优先服从现场施工条件',
        'planningRule.domain': '部署设计',
        'planningRule.category': '实施落地',
        'planningRule.trigger': '现场存在防爆、空间受限、布线困难或不停产施工约束。',
        'planningRule.scene': '改造项目 / 防爆区域 / 施工窗口受限',
        'planningRule.recommend': '优先按现场施工条件调整部署位置、布线路径和安装方式。',
        'planningRule.avoid': '避免纸面最优但现场无法落地的设计。',
        'planningRule.reason': '部署设计最终必须服务可实施性。',
        'planningRule.scope': '适用于改造项目和复杂现场实施条件。',
        'planningRule.alternative': '若施工条件宽松，可优先按长期维护最优部署。',
        'planningRule.example': '不停产条件下优先沿既有桥架分阶段改造。',
        'planningRule.note': '与实施约束页和稳定性规则联动。',
      },
      {
        'planningRule.name': '关键设备优先部署在可维护位置',
        'planningRule.domain': '部署设计',
        'planningRule.category': '运维可达性',
        'planningRule.trigger': '设备承担关键汇聚、边界或控制职责，后期维护频率较高。',
        'planningRule.scene': '核心设备 / 边界设备 / 汇聚设备',
        'planningRule.recommend': '优先部署在可达、可维护、便于替换的位置。',
        'planningRule.avoid': '避免关键设备部署在难以维护的角落或高风险位置。',
        'planningRule.reason': '关键设备的运维可达性会直接影响恢复时间。',
        'planningRule.scope': '适用于关键网络设备部署。',
        'planningRule.alternative': '若位置受限，应通过冗余和布线设计降低风险。',
        'planningRule.example': '核心交换机布置在可维护机柜而非临时箱体。',
        'planningRule.note': '与稳定性规则和选型规则联动。',
      },
      {
        'planningRule.name': '布线设计优先减少后期变更成本',
        'planningRule.domain': '部署设计',
        'planningRule.category': '布线策略',
        'planningRule.trigger': '项目存在未来扩展、分阶段建设或长期运维需求。',
        'planningRule.scene': '整厂建设 / 分阶段建设 / 中长期运维',
        'planningRule.recommend': '优先选择便于扩展、标识清晰、维护成本低的布线与部署方式。',
        'planningRule.avoid': '避免只满足当前最短路径，忽略后续维护与扩展。',
        'planningRule.reason': '部署阶段的布线选择会长期影响运维成本。',
        'planningRule.scope': '适用于中长期运营项目。',
        'planningRule.alternative': '短生命周期项目可适度简化布线冗余。',
        'planningRule.example': '预留桥架空间、标准化标签与机柜配线。',
        'planningRule.note': '与地址规划规则和场景规则联动。',
      },
    ],
    'security-rules': [
      {
        'planningRule.name': '远程接入优先先定控制再定连通',
        'planningRule.domain': '安全设计',
        'planningRule.category': '远程接入',
        'planningRule.trigger': '项目涉及第三方远程维护、总部远程监控或跨域调试。',
        'planningRule.scene': '远程运维 / 第三方维护 / 总部监控',
        'planningRule.recommend': '先确定认证、审批、审计和访问边界，再组织连通方式。',
        'planningRule.avoid': '避免先打通远程链路再补安全控制。',
        'planningRule.reason': '安全控制缺位会直接放大远程接入风险。',
        'planningRule.scope': '适用于所有涉及外部访问的工业网络场景。',
        'planningRule.alternative': '若无远程维护需求，可简化为本地运维边界。',
        'planningRule.example': '第三方维护统一经 DMZ、堡垒机和审批审计链路接入。',
        'planningRule.note': '应与通道规则和边界互联规则配套使用。',
      },
      {
        'planningRule.name': '关键区域优先最小权限访问',
        'planningRule.domain': '安全设计',
        'planningRule.category': '访问控制',
        'planningRule.trigger': '区域内对象对业务连续性或安全性影响高。',
        'planningRule.scene': '控制区 / 关键服务区 / 核心边界',
        'planningRule.recommend': '优先采用最小权限访问策略，限定对象、方向和协议。',
        'planningRule.avoid': '避免为图省事放开整区访问。',
        'planningRule.reason': '关键区域访问面越大，风险越高。',
        'planningRule.scope': '适用于关键区域与高价值对象。',
        'planningRule.alternative': '在短期调试阶段可临时放宽，但需限时与留痕。',
        'planningRule.example': '仅允许历史库单向读取控制区数据。',
        'planningRule.note': '需与边界互联和通道规则一并落地。',
      },
      {
        'planningRule.name': '安全设计优先结合运维可执行性',
        'planningRule.domain': '安全设计',
        'planningRule.category': '安全实施',
        'planningRule.trigger': '项目安全要求高，但现场运维能力有限。',
        'planningRule.scene': '传统工厂 / 运维资源有限 / 人员能力不均衡',
        'planningRule.recommend': '优先采用运维可执行、可长期坚持的安全控制策略。',
        'planningRule.avoid': '避免设计出纸面完美但现场无法长期执行的复杂安全方案。',
        'planningRule.reason': '不能长期执行的安全策略最终会失效。',
        'planningRule.scope': '适用于安全与运维平衡要求高的项目。',
        'planningRule.alternative': '可分阶段实施，先落关键控制点，再逐步提升。',
        'planningRule.example': '先落审批、堡垒机、白名单，再逐步细化分区策略。',
        'planningRule.note': '与部署规则、场景规则联动。',
      },
    ],
    'scenario-rules': [
      {
        'planningRule.name': '小规模集中场景优先简化结构',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '项目对象集中、系统规模小、工期和预算要求紧。',
        'planningRule.scene': '小规模集中部署 / 单区域项目',
        'planningRule.recommend': '优先采用简化拓扑与简化分层，减少不必要中间层。',
        'planningRule.avoid': '避免照搬大厂区架构，造成结构和设备配置过重。',
        'planningRule.reason': '小规模项目更重视快速落地和清晰维护。',
        'planningRule.scope': '影响拓扑、分层、设备选型与实施策略。',
        'planningRule.example': '单车间改造、独立站房、小型站点网络。',
        'planningRule.note': '若后续扩展预期大，可在地址和接口上预留余量。',
      },
      {
        'planningRule.name': '线型产线场景优先沿线组织网络',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '对象沿生产节拍方向顺序排布，现场布线路径明确。',
        'planningRule.scene': '汽车产线 / 包装产线 / 输送产线',
        'planningRule.recommend': '按线体组织网络，优先沿线布局节点，再结合冗余要求决定环网或分段星型。',
        'planningRule.avoid': '避免只按房间或机柜组织网络，忽略生产链路的连续性。',
        'planningRule.reason': '沿线组织更符合现场物理布局和故障排查路径。',
        'planningRule.scope': '影响拓扑、部署位置、链路设计和维护路径。',
        'planningRule.example': '焊装线、装配线、输送系统网络。',
        'planningRule.note': '需要同时参考拓扑规则与冗余设计。',
      },
      {
        'planningRule.name': '远程运维场景优先先定边界再定结构',
        'planningRule.domain': '场景规划',
        'planningRule.category': '场景规则',
        'planningRule.trigger': '项目涉及第三方维护、远程访问或跨域调试。',
        'planningRule.scene': '远程运维 / 跨域访问 / 第三方维护',
        'planningRule.recommend': '先明确访问边界、控制点和路径，再决定拓扑、分层与地址策略。',
        'planningRule.avoid': '避免先把网络连通，再事后补访问控制。',
        'planningRule.reason': '远程运维场景中，边界和访问路径决定了后续结构约束。',
        'planningRule.scope': '影响区域划分、边界设计、技术选择和输出文档重点。',
        'planningRule.example': '供应商远程维护、总部远程监控、跨厂区支持场景。',
        'planningRule.note': '此类规则后续应与安全规则页进一步联动。',
      },
    ],
  };
}

function createInitialDrafts() {
  return {
    'project-goal': buildEmptyDraft([
      'project.name',
      'project.customer',
      'project.industry',
      'project.scope',
      'project.goal',
      'project.delivery',
      'project.owner',
      'project.confirmStatus',
    ]),
    'scope-definition': buildEmptyDraft([
      'overview.name',
      'overview.space',
      'overview.distribution',
      'overview.cross',
      'overview.scale',
      'overview.note',
    ]),
    'business-description': buildEmptyDraft([
      'scene.name',
      'scene.mode',
      'scene.source',
      'scene.target',
      'scene.purpose',
      'scene.medium',
      'scene.continuity',
      'scene.note',
    ]),
    'asset-allocation': buildEmptyDraft([
      'asset.name',
      'asset.type',
      'asset.system',
      'asset.location',
      'asset.level',
      'asset.status',
      'asset.access',
      'asset.criticality',
      'asset.note',
    ]),
    'environment-conditions': buildEmptyDraft([
      'env.topic',
      'env.interference',
      'env.install',
      'env.distance',
      'env.medium',
      'env.power',
      'env.wireless',
      'env.note',
    ]),
    'implementation-constraints': buildEmptyDraft([
      'constraint.name',
      'constraint.type',
      'constraint.required',
      'constraint.scope',
      'constraint.existing',
      'constraint.note',
    ]),
    'security-scenario': buildEmptyDraft([
      'secScenario.name',
      'secScenario.type',
      'secScenario.scope',
      'secScenario.remote',
      'secScenario.external',
      'secScenario.note',
    ]),
    'exposure-analysis': buildEmptyDraft([
      'secExposure.name',
      'secExposure.relatedScenario',
      'secExposure.type',
      'secExposure.source',
      'secExposure.control',
      'secExposure.risk',
      'secExposure.note',
    ]),
    'consequence-analysis': buildEmptyDraft([
      'secConsequence.name',
      'secConsequence.relatedScenario',
      'secConsequence.type',
      'secConsequence.impact',
      'secConsequence.severity',
      'secConsequence.recovery',
      'secConsequence.note',
    ]),
    'baseline-check': buildEmptyDraft([
      'secBaseline.type',
      'secBaseline.object',
      'secBaseline.status',
      'secBaseline.evidence',
      'secBaseline.gap',
      'secBaseline.note',
    ]),
    'key-asset-analysis': buildEmptyDraft([
      'secKey.name',
      'secKey.type',
      'secKey.reason',
      'secKey.focus',
      'secKey.priority',
      'secKey.note',
    ]),
    'design-principles': buildEmptyDraft([
      'principle.category',
      'principle.main',
      'principle.scope',
      'principle.basis',
      'principle.desc',
      'principle.note',
    ]),
    'network-topology': buildEmptyDraft([
      'topology.object',
      'topology.type',
      'topology.backbone',
      'topology.access',
      'topology.scope',
      'topology.basis',
      'topology.tech',
      'topology.note',
    ]),
    'layer-design': buildEmptyDraft([
      'layer.object',
      'layer.mode',
      'layer.structure',
      'layer.policy',
      'layer.scope',
      'layer.note',
    ]),
    'segmentation-plan': buildEmptyDraft([
      'seg.object',
      'seg.purpose',
      'seg.range',
      'seg.margin',
      'seg.note',
    ]),
    'performance-design': buildEmptyDraft([
      'performance.object',
      'performance.latency',
      'performance.bandwidth',
      'performance.clock',
      'performance.measure',
      'performance.service',
      'performance.delay',
      'performance.risk',
      'performance.note',
    ]),
    'stability-design': buildEmptyDraft([
      'stability.object',
      'stability.target',
      'stability.risk',
      'stability.measure',
      'stability.control',
      'stability.maintain',
      'stability.note',
    ]),
    'redundancy-design': buildEmptyDraft([
      'redundancy.object',
      'redundancy.target',
      'redundancy.mode',
      'redundancy.switch',
      'redundancy.note',
    ]),
    'access-design': buildEmptyDraft([
      'access.object',
      'access.type',
      'access.scope',
      'access.limit',
      'access.reason',
      'access.note',
    ]),
    'selection-design': buildEmptyDraft([
      'selection.object',
      'selection.demand',
      'selection.capability',
      'selection.result',
      'selection.reason',
      'selection.note',
    ]),
    'deployment-design': buildEmptyDraft([
      'deployment.object',
      'deployment.location',
      'deployment.install',
      'deployment.cabling',
      'deployment.requirement',
      'deployment.note',
    ]),
    'link-design': buildEmptyDraft([
      'link.source',
      'link.target',
      'link.scene',
      'link.type',
      'link.role',
      'link.redundant',
      'link.sourceLocation',
      'link.targetLocation',
      'link.medium',
      'link.note',
    ]),
    'conduit-design': buildEmptyDraft([
      'conduit.source',
      'conduit.target',
      'conduit.scene',
      'conduit.purpose',
      'conduit.direction',
      'conduit.medium',
      'conduit.control',
      'conduit.delay',
      'conduit.criticality',
      'conduit.note',
    ]),
    'interconnect-design': buildEmptyDraft([
      'interconnect.source',
      'interconnect.target',
      'interconnect.structure',
      'interconnect.boundary',
      'interconnect.control',
      'interconnect.note',
    ]),
    'tech-selection': buildEmptyDraft([
      'tech.name',
      'tech.category',
      'tech.technology',
      'tech.scopeType',
      'tech.scopeTarget',
      'tech.scopeNote',
      'tech.goal',
      'tech.reason',
      'tech.alternative',
      'tech.alternativeReason',
      'tech.constraint',
      'tech.confirmStatus',
      'tech.note',
    ]),
    'security-limit': buildEmptyDraft([
      'secLimit.name',
      'secLimit.type',
      'secLimit.object',
      'secLimit.required',
      'secLimit.note',
    ]),
    'tech-selection': buildEmptyDraft([
      'tech.name',
      'tech.category',
      'tech.technology',
      'tech.scopeType',
      'tech.scopeTarget',
      'tech.scopeNote',
      'tech.goal',
      'tech.reason',
      'tech.alternative',
      'tech.alternativeReason',
      'tech.constraint',
      'tech.confirmStatus',
      'tech.note',
    ]),
    'delay-analysis': buildEmptyDraft([
      'delay.name',
      'delay.length',
      'delay.medium',
      'delay.hops',
      'delay.boundary',
      'delay.dmz',
      'delay.demand',
      'delay.risk',
      'delay.result',
    ]),
    'perf-evaluation': buildEmptyDraft([
      'perf.object',
      'perf.type',
      'perf.load',
      'perf.bandwidth',
      'perf.path',
      'perf.risk',
      'perf.result',
    ]),
    'topology-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
    'layer-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
    'scenario-rules': buildEmptyDraft([
      'planningRule.name',
      'planningRule.domain',
      'planningRule.category',
      'planningRule.trigger',
      'planningRule.scene',
      'planningRule.recommend',
      'planningRule.avoid',
      'planningRule.reason',
      'planningRule.scope',
      'planningRule.example',
      'planningRule.note',
    ]),
  };
}

function createInitialSelections() {
  return {
    'project-goal': 0,
    'scope-definition': 0,
    'business-description': 0,
    'asset-allocation': 0,
    'environment-conditions': 0,
    'implementation-constraints': 0,
    'security-scenario': 0,
    'exposure-analysis': 0,
    'consequence-analysis': 0,
    'baseline-check': 0,
    'key-asset-analysis': 0,
    'design-principles': 0,
    'network-topology': 0,
    'layer-design': 0,
    'segmentation-plan': 0,
    'performance-design': 0,
    'stability-design': 0,
    'redundancy-design': 0,
    'access-design': 0,
    'selection-design': 0,
    'deployment-design': 0,
    'link-design': 0,
    'conduit-design': 0,
    'interconnect-design': 0,
    'tech-selection': 0,
    'security-limit': 0,
    'tech-selection': 0,
    'delay-analysis': 0,
    'perf-evaluation': 0,
    'topology-rules': 0,
    'layer-rules': 0,
    'scenario-rules': 0,
  };
}

function createInitialExpandedGroups() {
  return {
    'how-to-ask': false,
    'how-to-judge': false,
    'how-to-derive': false,
    'how-to-land': false,
    'how-to-iterate': false,
    'for-customer': false,
    'for-internal': false,
    'security-design': false,
    'network-design': false,
    'engineering-design': false,
    'security-requirements': false,
  };
}

function createLoadedExpandedGroups() {
  return {
    'how-to-ask': true,
    'how-to-judge': true,
    'how-to-derive': true,
    'how-to-land': true,
    'how-to-iterate': true,
    'for-customer': false,
    'for-internal': false,
    'security-design': false,
    'network-design': false,
    'engineering-design': false,
    'security-requirements': false,
  };
}

export function usePlanningStore(initialMethodology = null) {
  const [currentMethodology, setCurrentMethodology] = useState(initialMethodology);
  const [activePageKey, setActivePageKey] = useState('home');
  const [expandedGroups, setExpandedGroups] = useState(createInitialExpandedGroups);
  const [formData, setFormData] = useState(() => buildInitialFormData(initialMethodology?.fields ?? {}));
  const [recordCollections, setRecordCollections] = useState(createInitialCollections);
  const [recordDrafts, setRecordDrafts] = useState(createInitialDrafts);
  const [selectedRecordIndexMap, setSelectedRecordIndexMap] = useState(createInitialSelections);

  const actions = useMemo(
    () => ({
      setActivePageKey,
      resetToHomeView() {
        setActivePageKey('home');
        setExpandedGroups(createInitialExpandedGroups());
      },
      selectMethodology(methodology) {
        setCurrentMethodology(methodology);
        setExpandedGroups(createLoadedExpandedGroups());
        setFormData(buildInitialFormData(methodology.fields ?? {}));
        setRecordCollections(createInitialCollections());
        setRecordDrafts(createInitialDrafts());
        setSelectedRecordIndexMap(createInitialSelections());
        setActivePageKey('home');
      },
      toggleExpanded(key) {
        setExpandedGroups((current) => {
          const nextValue = !current[key];
          const nextState = Object.keys(current).reduce((accumulator, currentKey) => {
            accumulator[currentKey] = false;
            return accumulator;
          }, {});
          nextState[key] = nextValue;
          return nextState;
        });
      },
      setExpandedWithinLevel(levelKeys, targetKey) {
        setExpandedGroups((current) => {
          const nextValue = !current[targetKey];
          const nextState = { ...current };

          levelKeys.forEach((key) => {
            nextState[key] = false;
          });

          nextState[targetKey] = nextValue;
          return nextState;
        });
      },
      setFieldValue(fieldKey, value) {
        setFormData((current) => ({
          ...current,
          [fieldKey]: value,
        }));
      },
      setDraftValue(pageKey, fieldKey, value) {
        setRecordDrafts((current) => ({
          ...current,
          [pageKey]: {
            ...current[pageKey],
            [fieldKey]: value,
          },
        }));
      },
      setSelectedRecord(pageKey, index) {
        setSelectedRecordIndexMap((current) => ({
          ...current,
          [pageKey]: index,
        }));
      },
      updateSelectedRecord(pageKey, fieldKey, value) {
        setRecordCollections((current) => {
          const nextRecords = [...(current[pageKey] ?? [])];
          const selectedIndex = selectedRecordIndexMap[pageKey] ?? 0;
          const currentRecord = nextRecords[selectedIndex] ?? {};
          nextRecords[selectedIndex] = {
            ...currentRecord,
            [fieldKey]: value,
          };
          return {
            ...current,
            [pageKey]: nextRecords,
          };
        });
      },
      addRecord(pageKey, fieldKeys) {
        setRecordCollections((currentCollections) => {
          const draft = recordDrafts[pageKey] ?? {};
          const hasDraftValue = fieldKeys.some((fieldKey) => Boolean(draft[fieldKey]));
          const nextRecord = hasDraftValue
            ? buildRecordFromDraft(fieldKeys, draft)
            : buildRecordFromDefaults(fieldKeys, currentMethodology?.fields ?? {});
          const nextRecords = [...(currentCollections[pageKey] ?? []), nextRecord];

          setSelectedRecordIndexMap((currentSelected) => ({
            ...currentSelected,
            [pageKey]: nextRecords.length - 1,
          }));

          return {
            ...currentCollections,
            [pageKey]: nextRecords,
          };
        });

        setRecordDrafts((currentDrafts) => ({
          ...currentDrafts,
          [pageKey]: buildEmptyDraft(fieldKeys),
        }));
      },
      loadCase(caseData) {
        setFormData((current) => ({
          ...current,
          ...(caseData.formData ?? {}),
        }));

        setRecordCollections((current) => ({
          ...current,
          ...(caseData.recordCollections ?? {}),
        }));

        setSelectedRecordIndexMap(createInitialSelections());
        setActivePageKey('project-goal');
      },
    }),
    [recordDrafts, selectedRecordIndexMap],
  );

  return {
    state: {
      currentMethodology,
      activePageKey,
      expandedGroups,
      formData,
      recordCollections,
      recordDrafts,
      selectedRecordIndexMap,
    },
    actions,
  };
}
