export const demoMethodology = {
  meta: {
    key: 'industrial-network-demo',
    title: '工业网络规划系统',
    subtitle: '方法论驱动的内容配置框架',
    version: '0.1.0',
    description: '用于验证菜单、标准页、记录页和字段依赖的示例方法论。',
  },
  systemPages: {
    home: {
      title: '首页',
      type: 'home',
      description: '用于展示系统简介、方法论信息、案例入口和导入导出能力。',
    },
  },
  navigation: [
    {
      key: 'raw-information',
      title: '原始信息',
      children: [
        { key: 'project-goal', title: '项目目标' },
        { key: 'scope-definition', title: '范围界定' },
        { key: 'business-description', title: '业务描述' },
        { key: 'asset-allocation', title: '设备归属' },
        { key: 'field-input', title: '现场输入' },
      ],
    },
    {
      key: 'design-derivation',
      title: '设计推导',
      children: [
        { key: 'zone-planning', title: '区域划分' },
        {
          key: 'security-analysis',
          title: '安全分析',
          children: [
            { key: 'threat-identification', title: '威胁识别' },
            { key: 'risk-assessment', title: '风险评估' },
          ],
        },
      ],
    },
    {
      key: 'deliverables',
      title: '成果输出',
      children: [
        { key: 'design-result', title: '设计结果' },
        { key: 'delivery-list', title: '交付清单' },
      ],
    },
  ],
  pages: {
    'project-goal': {
      title: '项目目标',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录项目名称、客户信息、建设范围、建设目标与确认信息。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '项目目标记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['project.name', 'project.customer', 'project.industry', 'project.scope', 'project.goal'],
      fields: [
        'project.name',
        'project.customer',
        'project.industry',
        'project.scope',
        'project.goal',
        'project.delivery',
        'project.owner',
        'project.confirmStatus',
      ],
    },
    'field-input': {
      title: '现场输入',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于整理现场采集到的网络、资产和约束输入。',
      fields: ['input.site', 'input.assets', 'input.constraints'],
    },
    'business-description': {
      title: '业务描述',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于采集多条业务场景记录，描述业务对象之间的通信与连续性要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '业务描述记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['scene.name', 'scene.mode', 'scene.source', 'scene.target', 'scene.purpose'],
      fields: ['scene.name', 'scene.mode', 'scene.source', 'scene.target', 'scene.purpose', 'scene.medium', 'scene.continuity', 'scene.note'],
    },
    'scope-definition': {
      title: '范围界定',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于界定空间范围、分布方式、跨域情况和总体规模。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '范围界定记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['overview.name', 'overview.space', 'overview.distribution', 'overview.cross', 'overview.scale'],
      fields: ['overview.name', 'overview.space', 'overview.distribution', 'overview.cross', 'overview.scale', 'overview.note'],
    },
    'asset-allocation': {
      title: '设备归属',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于整理关键对象、所属系统、部署位置和接入特征。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '设备归属记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['asset.name', 'asset.type', 'asset.system', 'asset.location', 'asset.level'],
      fields: ['asset.name', 'asset.type', 'asset.system', 'asset.location', 'asset.level', 'asset.status', 'asset.access', 'asset.criticality', 'asset.note'],
    },
    'zone-planning': {
      title: '区域划分',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于定义区域边界、对象归属和基础隔离策略。',
      fields: ['zone.scope', 'zone.businessZone', 'zone.relatedAsset', 'zone.strategy', 'zone.boundary', 'zone.isolationNotes'],
    },
    'security-analysis': {
      title: '安全分析',
      type: 'group',
      description: '用于承载威胁识别和风险评估等分析子页面。',
    },
    'threat-identification': {
      title: '威胁识别',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于梳理潜在威胁来源、攻击面和关键影响对象。',
      fields: ['threat.source', 'threat.surface', 'threat.asset'],
    },
    'risk-assessment': {
      title: '风险评估',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于评估风险等级、影响程度和优先处理顺序。',
      fields: ['risk.level', 'risk.impact', 'risk.priority'],
    },
    'design-result': {
      title: '设计结果',
      type: 'output',
      layout: 'summary-output',
      description: '用于集中展示设计输出和最终结果摘要。',
      sections: [
        { key: 'project-summary', kind: 'key-value-summary', title: '项目摘要' },
        { key: 'business-summary', kind: 'record-summary', title: '业务记录摘要' },
        { key: 'zone-summary', kind: 'key-value-summary', title: '区域规划摘要' },
      ],
    },
    'delivery-list': {
      title: '交付清单',
      type: 'output',
      layout: 'summary-output',
      description: '用于整理交付物组成和导出清单。',
      sections: [
        { key: 'delivery-summary', kind: 'key-value-summary', title: '交付内容摘要' },
      ],
    },
  },
  fields: {
    'project.name': {
      label: '项目名称',
      type: 'text',
      defaultValue: '工业网络规划项目',
    },
    'project.customer': {
      label: '客户名称',
      type: 'text',
      defaultValue: '某工业客户',
    },
    'project.industry': {
      label: '所属行业',
      type: 'select',
      defaultValue: '离散制造',
      options: ['离散制造', '流程工业', '食品饮料', '制药', '化工', '冶金', '能源', '水务环保', '仓储物流', '轨道交通', '电子半导体', '汽车制造', '其他'],
    },
    'project.scope': {
      label: '建设范围',
      type: 'select',
      defaultValue: '整厂',
      options: ['整厂', '单厂区', '单车间', '单产线', '专项系统'],
    },
    'project.goal': {
      label: '建设目标',
      type: 'select',
      defaultValue: '新建',
      options: ['新建', '改造', '现状梳理', '安全加固', '升级扩展'],
    },
    'project.delivery': {
      label: '期望交付',
      type: 'textarea',
      defaultValue: '',
    },
    'project.owner': {
      label: '业主确认人',
      type: 'text',
      defaultValue: '',
    },
    'project.confirmStatus': {
      label: '确认状态',
      type: 'select',
      defaultValue: '待确认',
      options: ['待确认', '业主已确认', '方案建议', '现场待复核'],
    },
    'input.site': {
      label: '现场位置',
      type: 'text',
      defaultValue: '华东区域工厂',
    },
    'input.assets': {
      label: '关键资产',
      type: 'textarea',
      defaultValue: 'PLC\nHMI\n工程师站\n交换机',
    },
    'input.constraints': {
      label: '主要约束',
      type: 'textarea',
      defaultValue: '不停产改造、老旧设备兼容、预算分期',
    },
    'zone.scope': {
      label: '规划范围',
      type: 'text',
      defaultValue: '控制网与工业 DMZ',
    },
    'zone.boundary': {
      label: '区域边界',
      type: 'textarea',
      defaultValue: '按产线、控制域和远程接入边界划分',
    },
    'zone.strategy': {
      label: '隔离策略',
      type: 'select',
      defaultValue: '分区分域',
      options: ['分区分域', '单网扁平优化', '核心隔离'],
    },
    'zone.relatedAsset': {
      label: '关联资产',
      type: 'select',
      defaultValue: 'PLC',
      optionsSource: {
        type: 'lines-from-field',
        field: 'input.assets',
      },
    },
    'scene.name': {
      label: '场景名称',
      type: 'text',
      defaultValue: '核心业务场景',
    },
    'scene.mode': {
      label: '通信方式',
      type: 'text',
      defaultValue: '周期通信',
    },
    'scene.source': {
      label: '源对象',
      type: 'text',
      defaultValue: '',
    },
    'scene.target': {
      label: '目标对象',
      type: 'text',
      defaultValue: '',
    },
    'scene.purpose': {
      label: '业务目的',
      type: 'text',
      defaultValue: '生产控制',
    },
    'scene.medium': {
      label: '通信介质',
      type: 'text',
      defaultValue: '有线',
    },
    'scene.continuity': {
      label: '连续性要求',
      type: 'text',
      defaultValue: '高',
    },
    'scene.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'overview.name': {
      label: '范围名称',
      type: 'text',
      defaultValue: '主项目范围',
    },
    'overview.space': {
      label: '空间范围',
      type: 'text',
      defaultValue: '',
    },
    'overview.distribution': {
      label: '分布方式',
      type: 'text',
      defaultValue: '',
    },
    'overview.cross': {
      label: '跨域情况',
      type: 'text',
      defaultValue: '',
    },
    'overview.scale': {
      label: '总体规模',
      type: 'text',
      defaultValue: '',
    },
    'overview.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'asset.name': {
      label: '对象名称',
      type: 'text',
      defaultValue: 'PLC-01',
    },
    'asset.type': {
      label: '对象类型',
      type: 'text',
      defaultValue: 'PLC',
    },
    'asset.system': {
      label: '所属系统',
      type: 'text',
      defaultValue: '',
    },
    'asset.location': {
      label: '部署位置',
      type: 'text',
      defaultValue: '',
    },
    'asset.level': {
      label: '网络层级',
      type: 'text',
      defaultValue: 'Level 1',
    },
    'asset.status': {
      label: '对象状态',
      type: 'text',
      defaultValue: '在用',
    },
    'asset.access': {
      label: '接入方式',
      type: 'text',
      defaultValue: '有线固定接入',
    },
    'asset.criticality': {
      label: '关键等级',
      type: 'select',
      defaultValue: '高',
      options: ['高', '中', '低'],
    },
    'asset.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'zone.businessZone': {
      label: '引用业务区域',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'business-description',
        field: 'scene.name',
        dedupe: true,
      },
    },
    'zone.isolationNotes': {
      label: '隔离补充说明',
      type: 'textarea',
      defaultValue: '当采用核心隔离时，需要补充边界访问控制与例外说明。',
      visibleWhen: {
        field: 'zone.strategy',
        equals: '核心隔离',
      },
    },
    'threat.source': {
      label: '威胁来源',
      type: 'textarea',
      defaultValue: '远程维护、供应链引入、内部误操作',
    },
    'threat.surface': {
      label: '攻击面',
      type: 'textarea',
      defaultValue: 'VPN 接入、工程师站、边界交换节点',
    },
    'threat.asset': {
      label: '关键影响对象',
      type: 'text',
      defaultValue: '控制器与关键生产单元',
    },
    'risk.level': {
      label: '风险等级',
      type: 'select',
      defaultValue: '中',
      options: ['低', '中', '高'],
    },
    'risk.impact': {
      label: '影响描述',
      type: 'textarea',
      defaultValue: '可能导致产线停机与远程运维中断',
    },
    'risk.priority': {
      label: '处置优先级',
      type: 'select',
      defaultValue: 'P1',
      options: ['P1', 'P2', 'P3'],
    },
  },
  outputs: {
    'design-result': {
      'project-summary': ['project.name', 'project.customer', 'project.industry'],
      'business-summary': {
        recordPage: 'business-description',
        fields: ['business.name', 'business.zone'],
      },
      'zone-summary': ['zone.scope', 'zone.businessZone', 'zone.relatedAsset', 'zone.strategy'],
    },
    'delivery-list': {
      'delivery-summary': ['project.name', 'zone.strategy', 'risk.priority'],
    },
  },
  cases: [
    {
      key: 'isa95-iec62443-case-1',
      title: '案例一：离散制造产线改造',
      description: '聚焦产线边界梳理与控制区隔离策略。',
      formData: {
        'project.name': '离散制造产线改造项目',
        'project.customer': '某装备制造客户',
        'project.industry': '离散制造',
        'project.scope': '单车间',
        'project.goal': '改造',
        'project.delivery': '网络规划方案、地址规划、拓扑图与实施建议。',
        'project.owner': '张工',
        'project.confirmStatus': '业主已确认',
        'input.site': '苏州工厂',
        'input.assets': 'PLC\nHMI\n工程师站\n工业交换机',
        'input.constraints': '不停产切换、窗口期短',
        'zone.scope': '产线控制区与工业 DMZ',
        'zone.businessZone': '区域1',
        'zone.relatedAsset': 'PLC',
        'zone.strategy': '核心隔离',
        'zone.boundary': '按控制域与远程运维边界划分',
        'zone.isolationNotes': '对远程维护通道实施白名单与审计。',
        'threat.source': '远程接入与供应链维护',
        'threat.surface': 'VPN、工程师站、边界交换设备',
        'threat.asset': '核心控制器',
        'risk.level': '高',
        'risk.impact': '可能导致关键产线停机',
        'risk.priority': 'P1',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '离散制造产线改造项目',
            'project.customer': '某装备制造客户',
            'project.industry': '离散制造',
            'project.scope': '单车间',
            'project.goal': '改造',
            'project.delivery': '网络规划方案、地址规划、拓扑图与实施建议。',
            'project.owner': '张工',
            'project.confirmStatus': '业主已确认',
          },
        ],
        'business-description': [
          {
            'scene.name': 'MES 下发工单',
            'scene.mode': '周期通信',
            'scene.source': 'MES-01',
            'scene.target': 'SCADA-01',
            'scene.purpose': '生产任务下发',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
          {
            'scene.name': 'SCADA 采集 PLC',
            'scene.mode': '周期通信',
            'scene.source': 'SCADA-01',
            'scene.target': 'PLC-01',
            'scene.purpose': '状态采集与受限控制',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '总装车间与信息中心',
            'overview.space': '1 个厂区 / 2 个车间 / 1 个信息中心',
            'overview.distribution': '生产区与信息中心分布',
            'overview.cross': '存在跨区访问',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'MES-01',
            'asset.type': 'MES',
            'asset.system': 'MES系统',
            'asset.location': '信息中心',
            'asset.level': 'Level 4',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
          {
            'asset.name': 'PLC-01',
            'asset.type': 'PLC',
            'asset.system': '产线控制系统',
            'asset.location': '总装车间',
            'asset.level': 'Level 1',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
      },
    },
    {
      key: 'isa95-iec62443-case-2',
      title: '案例二：流程工业远程运维整治',
      description: '聚焦远程接入面收敛与分区分域。',
      formData: {
        'project.name': '流程工业远程运维整治项目',
        'project.customer': '某化工客户',
        'project.industry': '流程工业',
        'project.scope': '专项系统',
        'project.goal': '安全加固',
        'project.delivery': '边界梳理、安全策略建议与整改清单。',
        'project.owner': '李经理',
        'project.confirmStatus': '方案建议',
        'input.site': '宁波生产基地',
        'input.assets': 'DCS\n工程师站\n历史数据库',
        'input.constraints': '合规审计压力高、变更窗口受限',
        'zone.scope': '控制区、监控区与 DMZ',
        'zone.businessZone': '工艺区',
        'zone.relatedAsset': 'DCS',
        'zone.strategy': '分区分域',
        'zone.boundary': '按工艺系统与远程接入链路划分',
        'zone.isolationNotes': '',
        'threat.source': '供应商维护与跨网访问',
        'threat.surface': '远程维护平台、跳板路径',
        'threat.asset': 'DCS 控制节点',
        'risk.level': '中',
        'risk.impact': '可能造成关键工艺监控受影响',
        'risk.priority': 'P2',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '流程工业远程运维整治项目',
            'project.customer': '某化工客户',
            'project.industry': '流程工业',
            'project.scope': '专项系统',
            'project.goal': '安全加固',
            'project.delivery': '边界梳理、安全策略建议与整改清单。',
            'project.owner': '李经理',
            'project.confirmStatus': '方案建议',
          },
        ],
        'business-description': [
          {
            'scene.name': '远程维护访问',
            'scene.mode': '按需通信',
            'scene.source': '堡垒机',
            'scene.target': '工程师站',
            'scene.purpose': '远程维护',
            'scene.medium': 'VPN',
            'scene.continuity': '中',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '主控室与生产控制区',
            'overview.space': '单厂区 / 主控室 / 生产装置区',
            'overview.distribution': '集中控制 + 分布现场',
            'overview.cross': '存在远程维护跨域',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'DCS-01',
            'asset.type': 'DCS',
            'asset.system': '控制系统',
            'asset.location': '主控室',
            'asset.level': 'Level 2',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
      },
    },
    {
      key: 'isa95-iec62443-case-3',
      title: '案例三：能源站网络分层优化',
      description: '聚焦区域边界清晰化与输出清单整理。',
      formData: {
        'project.name': '能源站网络分层优化项目',
        'project.customer': '某能源企业',
        'project.industry': '能源电力',
        'project.scope': '单厂区',
        'project.goal': '升级扩展',
        'project.delivery': '分层优化方案、关键对象清单与实施建议。',
        'project.owner': '王主任',
        'project.confirmStatus': '待确认',
        'input.site': '华北能源站',
        'input.assets': 'SCADA\nRTU\n防火墙\n交换机',
        'input.constraints': '老旧设备较多、网络连续性要求高',
        'zone.scope': '监控区与现场控制区',
        'zone.businessZone': '监控区',
        'zone.relatedAsset': 'SCADA',
        'zone.strategy': '单网扁平优化',
        'zone.boundary': '按监控层与现场层边界梳理',
        'zone.isolationNotes': '',
        'threat.source': '内部误操作与边界配置缺失',
        'threat.surface': '监控主机与边界设备',
        'threat.asset': 'SCADA 平台',
        'risk.level': '中',
        'risk.impact': '可能造成监控数据异常',
        'risk.priority': 'P2',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '能源站网络分层优化项目',
            'project.customer': '某能源企业',
            'project.industry': '能源电力',
            'project.scope': '单厂区',
            'project.goal': '升级扩展',
            'project.delivery': '分层优化方案、关键对象清单与实施建议。',
            'project.owner': '王主任',
            'project.confirmStatus': '待确认',
          },
        ],
        'business-description': [
          {
            'scene.name': '主站监控采集',
            'scene.mode': '周期通信',
            'scene.source': 'SCADA',
            'scene.target': 'RTU',
            'scene.purpose': '监控采集',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '监控室与现场采集区',
            'overview.space': '单厂区 / 监控室 / 现场设备区',
            'overview.distribution': '集中监控 + 现场采集',
            'overview.cross': '少量跨区访问',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'SCADA-01',
            'asset.type': 'SCADA',
            'asset.system': '监控系统',
            'asset.location': '监控室',
            'asset.level': 'Level 3',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
      },
    },
  ],
};
