export const demoMethodology = {
  meta: {
    key: 'industrial-network-demo',
    title: '工业网络规划系统',
    subtitle: '方法论驱动的内容配置框架',
    version: '0.1.0',
    description: '用于验证菜单、标准页、记录页和字段依赖的示例方法论。',
  },
  systemPages: {
    home: {
      title: '首页',
      type: 'home',
      description: '用于展示系统简介、方法论信息、案例入口和导入导出能力。',
    },
  },
  navigation: [
    {
      key: 'raw-information',
      title: '原始信息',
      children: [
        { key: 'project-goal', title: '项目目标' },
        { key: 'scope-definition', title: '范围界定' },
        { key: 'business-description', title: '业务描述' },
        { key: 'asset-allocation', title: '设备归属' },
        { key: 'environment-conditions', title: '环境条件' },
        { key: 'implementation-constraints', title: '实施约束' },
        { key: 'field-input', title: '现场输入' },
      ],
    },
    {
      key: 'design-derivation',
      title: '设计推导',
      children: [
        { key: 'design-principles', title: '设计原则' },
        { key: 'zone-planning', title: '区域划分' },
        { key: 'network-topology', title: '网络拓扑' },
        { key: 'layer-design', title: '分层设计' },
        { key: 'performance-design', title: '性能设计' },
        { key: 'stability-design', title: '稳定性设计' },
        { key: 'redundancy-design', title: '冗余设计' },
        { key: 'segmentation-plan', title: '地址分段' },
        { key: 'access-design', title: '对象接入' },
        { key: 'selection-design', title: '设备选型' },
        { key: 'deployment-design', title: '部署设计' },
        { key: 'link-design', title: '连接关系' },
        { key: 'conduit-design', title: '通道设计' },
        { key: 'interconnect-design', title: '边界互联' },
        { key: 'tech-selection', title: '技术选择' },
        { key: 'delay-analysis', title: '时延分析' },
        { key: 'perf-evaluation', title: '性能评估' },
        { key: 'planning-rules', title: '规划规则' },
        {
          key: 'security-analysis',
          title: '安全分析',
          children: [
            { key: 'security-scenario', title: '安全场景' },
            { key: 'exposure-analysis', title: '暴露面' },
            { key: 'consequence-analysis', title: '后果分析' },
            { key: 'baseline-check', title: '基线检查' },
            { key: 'security-limit', title: '安全约束' },
            { key: 'key-asset-analysis', title: '关键对象' },
            { key: 'threat-identification', title: '威胁识别' },
            { key: 'risk-assessment', title: '风险评估' },
          ],
        },
      ],
    },
    {
      key: 'deliverables',
      title: '成果输出',
      children: [
        { key: 'design-result', title: '设计结果' },
        { key: 'topology-result', title: '拓扑结果' },
        { key: 'ip-plan-result', title: 'IP规划结果' },
        { key: 'delivery-list', title: '交付清单' },
      ],
    },
  ],
  pages: {
    'project-goal': {
      title: '项目目标',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录项目名称、客户信息、建设范围、建设目标与确认信息。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '项目目标记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['project.name', 'project.customer', 'project.industry', 'project.scope', 'project.goal'],
      fields: [
        'project.name',
        'project.customer',
        'project.industry',
        'project.scope',
        'project.goal',
        'project.delivery',
        'project.owner',
        'project.confirmStatus',
      ],
    },
    'field-input': {
      title: '现场输入',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于整理现场采集到的网络、资产和约束输入。',
      fields: ['input.site', 'input.assets', 'input.constraints'],
    },
    'business-description': {
      title: '业务描述',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于采集多条业务场景记录，描述业务对象之间的通信与连续性要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '业务描述记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['scene.name', 'scene.mode', 'scene.source', 'scene.target', 'scene.purpose'],
      fields: ['scene.name', 'scene.mode', 'scene.source', 'scene.target', 'scene.purpose', 'scene.medium', 'scene.continuity', 'scene.note'],
    },
    'scope-definition': {
      title: '范围界定',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于界定空间范围、分布方式、跨域情况和总体规模。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '范围界定记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['overview.name', 'overview.space', 'overview.distribution', 'overview.cross', 'overview.scale'],
      fields: ['overview.name', 'overview.space', 'overview.distribution', 'overview.cross', 'overview.scale', 'overview.note'],
    },
    'asset-allocation': {
      title: '设备归属',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于整理关键对象、所属系统、部署位置和接入特征。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '设备归属记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['asset.name', 'asset.type', 'asset.system', 'asset.location', 'asset.level'],
      fields: ['asset.name', 'asset.type', 'asset.system', 'asset.location', 'asset.level', 'asset.status', 'asset.access', 'asset.criticality', 'asset.note'],
    },
    'environment-conditions': {
      title: '环境条件',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录干扰、安装、距离、介质、供电和无线等环境因素。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '环境条件记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['env.topic', 'env.interference', 'env.install', 'env.distance', 'env.medium'],
      fields: ['env.topic', 'env.interference', 'env.install', 'env.distance', 'env.medium', 'env.power', 'env.wireless', 'env.note'],
    },
    'implementation-constraints': {
      title: '实施约束',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录预算、停机窗口、现网继承和实施约束。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '实施约束记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['constraint.name', 'constraint.type', 'constraint.required', 'constraint.scope', 'constraint.existing'],
      fields: ['constraint.name', 'constraint.type', 'constraint.required', 'constraint.scope', 'constraint.existing', 'constraint.note'],
    },
    'zone-planning': {
      title: '区域划分',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于定义区域边界、对象归属和基础隔离策略。',
      fields: ['zone.scope', 'zone.businessZone', 'zone.relatedAsset', 'zone.relatedScene', 'zone.strategy', 'zone.boundary', 'zone.isolationNotes'],
    },
    'design-principles': {
      title: '设计原则',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于沉淀区域、结构与地址规划的设计原则。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '设计原则记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['principle.category', 'principle.main', 'principle.scope', 'principle.basis'],
      fields: ['principle.category', 'principle.main', 'principle.scope', 'principle.basis', 'principle.desc', 'principle.note'],
    },
    'network-topology': {
      title: '网络拓扑',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义网络总体拓扑、骨干方式与接入思路。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '网络拓扑记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['topology.object', 'topology.type', 'topology.backbone', 'topology.access'],
      fields: ['topology.object', 'topology.type', 'topology.backbone', 'topology.access', 'topology.scope', 'topology.basis', 'topology.tech', 'topology.note'],
    },
    'layer-design': {
      title: '分层设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义网络层级模式、结构与分层策略。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '分层设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['layer.object', 'layer.mode', 'layer.structure', 'layer.policy'],
      fields: ['layer.object', 'layer.mode', 'layer.structure', 'layer.policy', 'layer.scope', 'layer.note'],
    },
    'segmentation-plan': {
      title: '地址分段',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义网段对象、用途、地址范围和预留余量。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '地址分段记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['seg.object', 'seg.purpose', 'seg.range', 'seg.margin'],
      fields: ['seg.object', 'seg.purpose', 'seg.range', 'seg.margin', 'seg.note'],
    },
    'performance-design': {
      title: '性能设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义关键链路或对象的实时性、带宽与性能措施。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '性能设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['performance.object', 'performance.latency', 'performance.bandwidth', 'performance.measure'],
      fields: ['performance.object', 'performance.latency', 'performance.bandwidth', 'performance.clock', 'performance.measure', 'performance.service', 'performance.delay', 'performance.risk', 'performance.note'],
    },
    'stability-design': {
      title: '稳定性设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义稳定性目标、风险点与控制措施。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '稳定性设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['stability.object', 'stability.target', 'stability.risk', 'stability.measure'],
      fields: ['stability.object', 'stability.target', 'stability.risk', 'stability.measure', 'stability.control', 'stability.maintain', 'stability.note'],
    },
    'redundancy-design': {
      title: '冗余设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义关键对象或链路的冗余目标与切换要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '冗余设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['redundancy.object', 'redundancy.target', 'redundancy.mode', 'redundancy.switch'],
      fields: ['redundancy.object', 'redundancy.target', 'redundancy.mode', 'redundancy.switch', 'redundancy.note'],
    },
    'access-design': {
      title: '对象接入',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义对象接入方式、适用范围与接入约束。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '对象接入记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['access.object', 'access.type', 'access.scope', 'access.limit'],
      fields: ['access.object', 'access.type', 'access.scope', 'access.limit', 'access.reason', 'access.note'],
    },
    'selection-design': {
      title: '设备选型',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义能力需求、关键能力与选型结果。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '设备选型记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['selection.object', 'selection.demand', 'selection.capability', 'selection.result'],
      fields: ['selection.object', 'selection.demand', 'selection.capability', 'selection.result', 'selection.reason', 'selection.note'],
    },
    'deployment-design': {
      title: '部署设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义部署位置、安装方式、布线与施工要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '部署设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['deployment.object', 'deployment.location', 'deployment.install', 'deployment.cabling'],
      fields: ['deployment.object', 'deployment.location', 'deployment.install', 'deployment.cabling', 'deployment.requirement', 'deployment.note'],
    },
    'link-design': {
      title: '连接关系',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义对象级连接、链路角色、介质与冗余关系。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '连接关系记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['link.source', 'link.target', 'link.scene', 'link.role', 'link.redundant'],
      fields: ['link.source', 'link.target', 'link.scene', 'link.type', 'link.role', 'link.redundant', 'link.sourceLocation', 'link.targetLocation', 'link.medium', 'link.note'],
    },
    'conduit-design': {
      title: '通道设计',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义区域间通道、方向、控制要求与关键等级。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '通道设计记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['conduit.source', 'conduit.target', 'conduit.scene', 'conduit.purpose', 'conduit.criticality'],
      fields: ['conduit.source', 'conduit.target', 'conduit.scene', 'conduit.purpose', 'conduit.direction', 'conduit.medium', 'conduit.control', 'conduit.delay', 'conduit.criticality', 'conduit.note'],
    },
    'interconnect-design': {
      title: '边界互联',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义边界设备、互联结构与控制要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '边界互联记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['interconnect.source', 'interconnect.target', 'interconnect.structure', 'interconnect.boundary'],
      fields: ['interconnect.source', 'interconnect.target', 'interconnect.structure', 'interconnect.boundary', 'interconnect.control', 'interconnect.note'],
    },
    'tech-selection': {
      title: '技术选择',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义技术方向、作用范围、设计目标与确认状态。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '技术选择记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['tech.name', 'tech.category', 'tech.technology', 'tech.scopeTarget', 'tech.confirmStatus'],
      fields: ['tech.name', 'tech.category', 'tech.technology', 'tech.scopeType', 'tech.scopeTarget', 'tech.scopeNote', 'tech.goal', 'tech.reason', 'tech.alternative', 'tech.alternativeReason', 'tech.constraint', 'tech.confirmStatus', 'tech.note'],
    },
    'security-limit': {
      title: '安全约束',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于整理安全相关的停机窗口、维护方式与强制约束。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '安全约束记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secLimit.name', 'secLimit.type', 'secLimit.object', 'secLimit.required'],
      fields: ['secLimit.name', 'secLimit.type', 'secLimit.object', 'secLimit.required', 'secLimit.note'],
    },
    'delay-analysis': {
      title: '时延分析',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于估算链路长度、跳数、边界转接与时延结论。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '时延分析记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['delay.name', 'delay.medium', 'delay.demand', 'delay.risk', 'delay.result'],
      fields: ['delay.name', 'delay.length', 'delay.medium', 'delay.hops', 'delay.boundary', 'delay.dmz', 'delay.demand', 'delay.risk', 'delay.result'],
    },
    'perf-evaluation': {
      title: '性能评估',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于定义对象性能负载、关键路径与评估结论。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '性能评估记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['perf.object', 'perf.type', 'perf.load', 'perf.bandwidth', 'perf.result'],
      fields: ['perf.object', 'perf.type', 'perf.load', 'perf.bandwidth', 'perf.path', 'perf.risk', 'perf.result'],
    },
    'planning-rules': {
      title: '规划规则',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于沉淀规划过程中可复用的规则、触发条件与推荐动作。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '规划规则记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['planningRule.name', 'planningRule.domain', 'planningRule.category', 'planningRule.scene'],
      fields: ['planningRule.name', 'planningRule.domain', 'planningRule.category', 'planningRule.trigger', 'planningRule.scene', 'planningRule.recommend', 'planningRule.avoid', 'planningRule.reason', 'planningRule.impact', 'planningRule.example', 'planningRule.note'],
    },
    'security-analysis': {
      title: '安全分析',
      type: 'group',
      description: '用于承载威胁识别和风险评估等分析子页面。',
    },
    'security-scenario': {
      title: '安全场景',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录场景类型、覆盖范围、远程访问与外部互联。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '安全场景记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secScenario.name', 'secScenario.type', 'secScenario.scope', 'secScenario.remote', 'secScenario.external'],
      fields: ['secScenario.name', 'secScenario.type', 'secScenario.scope', 'secScenario.remote', 'secScenario.external', 'secScenario.note'],
    },
    'exposure-analysis': {
      title: '暴露面',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于记录对象暴露方式、来源、现有控制与初步风险判断。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '暴露面记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secExposure.name', 'secExposure.relatedScenario', 'secExposure.type', 'secExposure.source', 'secExposure.risk'],
      fields: [
        'secExposure.name',
        'secExposure.relatedScenario',
        'secExposure.type',
        'secExposure.source',
        'secExposure.control',
        'secExposure.risk',
        'secExposure.note',
      ],
    },
    'consequence-analysis': {
      title: '后果分析',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于评估关键对象在场景下的业务后果、严重程度与恢复要求。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '后果分析记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secConsequence.name', 'secConsequence.relatedScenario', 'secConsequence.type', 'secConsequence.severity', 'secConsequence.recovery'],
      fields: [
        'secConsequence.name',
        'secConsequence.relatedScenario',
        'secConsequence.type',
        'secConsequence.impact',
        'secConsequence.severity',
        'secConsequence.recovery',
        'secConsequence.note',
      ],
    },
    'baseline-check': {
      title: '基线检查',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于梳理对象的基线类型、现状证据与缺口判断。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '基线检查记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secBaseline.object', 'secBaseline.type', 'secBaseline.status', 'secBaseline.gap'],
      fields: [
        'secBaseline.type',
        'secBaseline.object',
        'secBaseline.status',
        'secBaseline.evidence',
        'secBaseline.gap',
        'secBaseline.note',
      ],
    },
    'key-asset-analysis': {
      title: '关键对象',
      type: 'record-collection',
      layout: 'table-form',
      description: '用于沉淀关键对象、关键原因、安全关注点与优先级。',
      sections: [
        { key: 'record-list', kind: 'record-list', title: '关键对象记录表' },
        { key: 'record-editor', kind: 'record-editor', title: '当前记录编辑区' },
      ],
      summaryColumns: ['secKey.name', 'secKey.type', 'secKey.focus', 'secKey.priority'],
      fields: ['secKey.name', 'secKey.type', 'secKey.reason', 'secKey.focus', 'secKey.priority', 'secKey.note'],
    },
    'threat-identification': {
      title: '威胁识别',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于梳理潜在威胁来源、攻击面和关键影响对象。',
      fields: [
        'threat.relatedScenario',
        'threat.relatedExposure',
        'threat.relatedConsequence',
        'threat.source',
        'threat.surface',
        'threat.asset',
        'threat.relatedConstraint',
        'threat.relatedEnvironment',
      ],
    },
    'risk-assessment': {
      title: '风险评估',
      type: 'standard-record',
      layout: 'single-form',
      description: '用于评估风险等级、影响程度和优先处理顺序。',
      fields: ['risk.relatedBaseline', 'risk.relatedKeyAsset', 'risk.level', 'risk.impact', 'risk.priority'],
    },
    'design-result': {
      title: '设计结果',
      type: 'output',
      layout: 'summary-output',
      description: '用于集中展示设计输出和最终结果摘要。',
      sections: [
        { key: 'project-summary', kind: 'key-value-summary', title: '项目摘要' },
        { key: 'scope-summary', kind: 'record-summary', title: '范围界定摘要' },
        { key: 'business-summary', kind: 'record-summary', title: '业务记录摘要' },
        { key: 'asset-summary', kind: 'record-summary', title: '关键对象摘要' },
        { key: 'environment-summary', kind: 'record-summary', title: '环境条件摘要' },
        { key: 'constraint-summary', kind: 'record-summary', title: '实施约束摘要' },
        { key: 'security-scenario-summary', kind: 'record-summary', title: '安全场景摘要' },
        { key: 'exposure-summary', kind: 'record-summary', title: '暴露面摘要' },
        { key: 'consequence-summary', kind: 'record-summary', title: '后果分析摘要' },
        { key: 'baseline-summary', kind: 'record-summary', title: '基线检查摘要' },
        { key: 'key-asset-summary', kind: 'record-summary', title: '关键对象分析摘要' },
        { key: 'zone-summary', kind: 'key-value-summary', title: '区域规划摘要' },
        { key: 'principle-summary', kind: 'record-summary', title: '设计原则摘要' },
        { key: 'topology-summary', kind: 'record-summary', title: '网络拓扑摘要' },
        { key: 'layer-summary', kind: 'record-summary', title: '分层设计摘要' },
        { key: 'performance-summary', kind: 'record-summary', title: '性能设计摘要' },
        { key: 'stability-summary', kind: 'record-summary', title: '稳定性设计摘要' },
        { key: 'redundancy-summary', kind: 'record-summary', title: '冗余设计摘要' },
        { key: 'seg-summary', kind: 'record-summary', title: '地址分段摘要' },
        { key: 'access-summary', kind: 'record-summary', title: '对象接入摘要' },
        { key: 'selection-summary', kind: 'record-summary', title: '设备选型摘要' },
        { key: 'deployment-summary', kind: 'record-summary', title: '部署设计摘要' },
        { key: 'link-summary', kind: 'record-summary', title: '连接关系摘要' },
        { key: 'conduit-summary', kind: 'record-summary', title: '通道设计摘要' },
        { key: 'interconnect-summary', kind: 'record-summary', title: '边界互联摘要' },
        { key: 'tech-summary', kind: 'record-summary', title: '技术选择摘要' },
        { key: 'security-limit-summary', kind: 'record-summary', title: '安全约束摘要' },
        { key: 'delay-summary', kind: 'record-summary', title: '时延分析摘要' },
        { key: 'perf-summary', kind: 'record-summary', title: '性能评估摘要' },
        { key: 'planning-rule-summary', kind: 'record-summary', title: '规划规则摘要' },
        { key: 'security-analysis-text', kind: 'text-summary', title: '安全分析综合结论' },
        { key: 'project-judgement', kind: 'text-summary', title: '项目判断与设计关注重点' },
        { key: 'next-actions', kind: 'text-summary', title: '后续设计要求' },
      ],
    },
    'delivery-list': {
      title: '交付清单',
      type: 'output',
      layout: 'summary-output',
      description: '用于整理交付物组成和导出清单。',
      sections: [
        { key: 'delivery-summary', kind: 'key-value-summary', title: '交付内容摘要' },
        { key: 'delivery-focus', kind: 'text-summary', title: '交付重点说明' },
      ],
    },
    'topology-result': {
      title: '拓扑结果',
      type: 'output',
      layout: 'summary-output',
      description: '用于输出正式拓扑绘制要求与关键信息。',
      sections: [
        { key: 'topology-drawing-brief', kind: 'text-summary', title: '拓扑绘制要求' },
      ],
    },
    'ip-plan-result': {
      title: 'IP规划结果',
      type: 'output',
      layout: 'summary-output',
      description: '用于输出 IP 地址规划的结构化结果。',
      sections: [
        { key: 'ip-plan-brief', kind: 'text-summary', title: 'IP规划说明' },
      ],
    },
  },
  fields: {
    'project.name': {
      label: '项目名称',
      type: 'text',
      defaultValue: '工业网络规划项目',
    },
    'project.customer': {
      label: '客户名称',
      type: 'text',
      defaultValue: '某工业客户',
    },
    'project.industry': {
      label: '所属行业',
      type: 'select',
      defaultValue: '离散制造',
      options: ['离散制造', '流程工业', '食品饮料', '制药', '化工', '冶金', '能源', '水务环保', '仓储物流', '轨道交通', '电子半导体', '汽车制造', '其他'],
    },
    'project.scope': {
      label: '建设范围',
      type: 'select',
      defaultValue: '整厂',
      options: ['整厂', '单厂区', '单车间', '单产线', '专项系统'],
    },
    'project.goal': {
      label: '建设目标',
      type: 'select',
      defaultValue: '新建',
      options: ['新建', '改造', '现状梳理', '安全加固', '升级扩展'],
    },
    'project.delivery': {
      label: '期望交付',
      type: 'textarea',
      defaultValue: '',
    },
    'project.owner': {
      label: '业主确认人',
      type: 'text',
      defaultValue: '',
    },
    'project.confirmStatus': {
      label: '确认状态',
      type: 'select',
      defaultValue: '待确认',
      options: ['待确认', '业主已确认', '方案建议', '现场待复核'],
    },
    'input.site': {
      label: '现场位置',
      type: 'text',
      defaultValue: '华东区域工厂',
    },
    'input.assets': {
      label: '关键资产',
      type: 'textarea',
      defaultValue: 'PLC\nHMI\n工程师站\n交换机',
    },
    'input.constraints': {
      label: '主要约束',
      type: 'textarea',
      defaultValue: '不停产改造、老旧设备兼容、预算分期',
    },
    'zone.scope': {
      label: '规划范围',
      type: 'text',
      defaultValue: '控制网与工业 DMZ',
    },
    'zone.boundary': {
      label: '区域边界',
      type: 'textarea',
      defaultValue: '按产线、控制域和远程接入边界划分',
    },
    'zone.strategy': {
      label: '隔离策略',
      type: 'select',
      defaultValue: '分区分域',
      options: ['分区分域', '单网扁平优化', '核心隔离'],
    },
    'zone.relatedAsset': {
      label: '关联资产',
      type: 'select',
      defaultValue: 'PLC',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'zone.relatedScene': {
      label: '关联业务场景',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'business-description',
        field: 'scene.name',
        dedupe: true,
      },
    },
    'principle.category': {
      label: '原则分类',
      type: 'select',
      defaultValue: '区域划分思路',
      options: ['区域划分思路', '网络结构思路', '安全边界思路', '地址规划思路'],
    },
    'principle.main': {
      label: '主要原则',
      type: 'text',
      defaultValue: '优先按物理区域与业务边界划分',
    },
    'principle.scope': {
      label: '适用范围',
      type: 'text',
      defaultValue: '',
    },
    'principle.basis': {
      label: '判断依据',
      type: 'textarea',
      defaultValue: '',
    },
    'principle.desc': {
      label: '原则说明',
      type: 'textarea',
      defaultValue: '',
    },
    'principle.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'topology.object': {
      label: '对象',
      type: 'text',
      defaultValue: '全厂主干网络',
    },
    'topology.type': {
      label: '拓扑类型',
      type: 'select',
      defaultValue: '星型',
      options: ['星型', '环型', '树型', '混合型'],
    },
    'topology.backbone': {
      label: '骨干说明',
      type: 'text',
      defaultValue: '',
    },
    'topology.access': {
      label: '接入说明',
      type: 'text',
      defaultValue: '',
    },
    'topology.scope': {
      label: '适用范围',
      type: 'text',
      defaultValue: '',
    },
    'topology.basis': {
      label: '设计依据',
      type: 'textarea',
      defaultValue: '',
    },
    'topology.tech': {
      label: '关联技术',
      type: 'text',
      defaultValue: '',
    },
    'topology.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'layer.object': {
      label: '对象',
      type: 'text',
      defaultValue: '车间汇聚层',
    },
    'layer.mode': {
      label: '模式',
      type: 'select',
      defaultValue: '二层',
      options: ['二层', '三层', '二三层混合'],
    },
    'layer.structure': {
      label: '层级结构',
      type: 'text',
      defaultValue: '',
    },
    'layer.policy': {
      label: '分层策略',
      type: 'textarea',
      defaultValue: '',
    },
    'layer.scope': {
      label: '适用范围',
      type: 'text',
      defaultValue: '',
    },
    'layer.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'seg.object': {
      label: '网段对象',
      type: 'text',
      defaultValue: '控制区网段',
    },
    'seg.purpose': {
      label: '用途',
      type: 'text',
      defaultValue: '控制通信',
    },
    'seg.range': {
      label: '地址范围',
      type: 'text',
      defaultValue: '',
    },
    'seg.margin': {
      label: '预留余量',
      type: 'text',
      defaultValue: '',
    },
    'seg.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'performance.object': {
      label: '评估对象',
      type: 'text',
      defaultValue: '控制区主链路',
    },
    'performance.latency': {
      label: '实时性要求',
      type: 'text',
      defaultValue: '毫秒级',
    },
    'performance.bandwidth': {
      label: '带宽等级',
      type: 'text',
      defaultValue: '千兆',
    },
    'performance.clock': {
      label: '时钟/周期',
      type: 'text',
      defaultValue: '',
    },
    'performance.measure': {
      label: '性能措施',
      type: 'textarea',
      defaultValue: '',
    },
    'performance.service': {
      label: '业务类型',
      type: 'text',
      defaultValue: '',
    },
    'performance.delay': {
      label: '时延要求',
      type: 'text',
      defaultValue: '',
    },
    'performance.risk': {
      label: '性能风险',
      type: 'textarea',
      defaultValue: '',
    },
    'performance.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'stability.object': {
      label: '评估对象',
      type: 'text',
      defaultValue: '控制系统主链路',
    },
    'stability.target': {
      label: '稳定性目标',
      type: 'text',
      defaultValue: '',
    },
    'stability.risk': {
      label: '风险点',
      type: 'textarea',
      defaultValue: '',
    },
    'stability.measure': {
      label: '控制措施',
      type: 'textarea',
      defaultValue: '',
    },
    'stability.control': {
      label: '控制措施（兼容）',
      type: 'textarea',
      defaultValue: '',
    },
    'stability.maintain': {
      label: '维护要求（兼容）',
      type: 'textarea',
      defaultValue: '',
    },
    'stability.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'redundancy.object': {
      label: '对象',
      type: 'text',
      defaultValue: '主干光纤链路',
    },
    'redundancy.target': {
      label: '冗余目标',
      type: 'text',
      defaultValue: '',
    },
    'redundancy.mode': {
      label: '冗余模式',
      type: 'select',
      defaultValue: '主备',
      options: ['主备', '双活', '环网'],
    },
    'redundancy.switch': {
      label: '切换要求',
      type: 'text',
      defaultValue: '',
    },
    'redundancy.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'access.object': {
      label: '对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'access.type': {
      label: '接入方式',
      type: 'select',
      defaultValue: '有线',
      options: ['有线', '无线', '串口', '远程接入'],
    },
    'access.scope': {
      label: '适用范围',
      type: 'text',
      defaultValue: '',
    },
    'access.limit': {
      label: '接入约束',
      type: 'textarea',
      defaultValue: '',
    },
    'access.reason': {
      label: '设计依据',
      type: 'textarea',
      defaultValue: '',
    },
    'access.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'selection.object': {
      label: '对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'selection.demand': {
      label: '能力需求',
      type: 'text',
      defaultValue: '控制通信',
    },
    'selection.capability': {
      label: '关键能力',
      type: 'textarea',
      defaultValue: '',
    },
    'selection.result': {
      label: '选型结果',
      type: 'text',
      defaultValue: '',
    },
    'selection.reason': {
      label: '选型依据',
      type: 'textarea',
      defaultValue: '',
    },
    'selection.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'deployment.object': {
      label: '对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'deployment.location': {
      label: '部署位置',
      type: 'text',
      defaultValue: '主项目范围',
    },
    'deployment.install': {
      label: '安装方式',
      type: 'text',
      defaultValue: '',
    },
    'deployment.cabling': {
      label: '布线方式',
      type: 'text',
      defaultValue: '',
    },
    'deployment.requirement': {
      label: '施工要求',
      type: 'textarea',
      defaultValue: '',
    },
    'deployment.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'link.source': {
      label: '源对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'link.target': {
      label: '目标对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'link.scene': {
      label: '关联场景',
      type: 'select',
      defaultValue: '核心业务场景',
      optionsSource: {
        type: 'record-field',
        recordPage: 'business-description',
        field: 'scene.name',
        dedupe: true,
      },
    },
    'link.type': {
      label: '连接类型',
      type: 'select',
      defaultValue: '电口',
      options: ['电口', '光口', '无线', '串口'],
    },
    'link.role': {
      label: '链路角色',
      type: 'text',
      defaultValue: '接入链路',
    },
    'link.redundant': {
      label: '是否冗余',
      type: 'select',
      defaultValue: '否',
      options: ['是', '否'],
    },
    'link.sourceLocation': {
      label: '源位置',
      type: 'text',
      defaultValue: '',
    },
    'link.targetLocation': {
      label: '目标位置',
      type: 'text',
      defaultValue: '',
    },
    'link.medium': {
      label: '介质/速率',
      type: 'text',
      defaultValue: '',
    },
    'link.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'conduit.source': { label: '源区域', type: 'text', defaultValue: '控制区' },
    'conduit.target': { label: '目标区域', type: 'text', defaultValue: '监控区' },
    'conduit.scene': {
      label: '关联场景',
      type: 'select',
      defaultValue: '核心业务场景',
      optionsSource: {
        type: 'record-field',
        recordPage: 'business-description',
        field: 'scene.name',
        dedupe: true,
      },
    },
    'conduit.purpose': { label: '目的', type: 'text', defaultValue: '数据采集' },
    'conduit.direction': { label: '方向', type: 'select', defaultValue: '单向', options: ['单向', '双向'] },
    'conduit.medium': { label: '介质', type: 'text', defaultValue: '有线' },
    'conduit.control': { label: '控制要求', type: 'textarea', defaultValue: '受控开放' },
    'conduit.delay': { label: '时延要求', type: 'text', defaultValue: '毫秒级' },
    'conduit.criticality': { label: '关键等级', type: 'select', defaultValue: '高', options: ['高', '中', '低'] },
    'conduit.note': { label: '补充说明', type: 'textarea', defaultValue: '' },
    'interconnect.source': {
      label: '源区域',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'conduit-design',
        field: 'conduit.source',
        dedupe: true,
      },
    },
    'interconnect.target': {
      label: '目标区域',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'conduit-design',
        field: 'conduit.target',
        dedupe: true,
      },
    },
    'interconnect.structure': { label: '互联结构', type: 'text', defaultValue: '边界设备互联' },
    'interconnect.boundary': { label: '边界设备', type: 'text', defaultValue: '' },
    'interconnect.control': { label: '控制要求', type: 'textarea', defaultValue: '' },
    'interconnect.note': { label: '补充说明', type: 'textarea', defaultValue: '' },
    'tech.name': { label: '技术选择名称', type: 'text', defaultValue: '核心交换技术选择' },
    'tech.category': { label: '技术分类', type: 'text', defaultValue: '网络结构' },
    'tech.technology': { label: '技术名称', type: 'text', defaultValue: '工业以太网' },
    'tech.scopeType': { label: '范围类型', type: 'text', defaultValue: '区域' },
    'tech.scopeTarget': {
      label: '范围对象',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'tech.scopeNote': { label: '范围补充', type: 'textarea', defaultValue: '' },
    'tech.goal': { label: '设计目标', type: 'text', defaultValue: '' },
    'tech.reason': { label: '采用原因', type: 'textarea', defaultValue: '' },
    'tech.alternative': { label: '备选方案', type: 'text', defaultValue: '' },
    'tech.alternativeReason': { label: '备选原因', type: 'textarea', defaultValue: '' },
    'tech.constraint': { label: '约束条件', type: 'textarea', defaultValue: '' },
    'tech.confirmStatus': { label: '确认状态', type: 'select', defaultValue: '待确认', options: ['待确认', '已确认', '待复核'] },
    'tech.note': { label: '补充说明', type: 'textarea', defaultValue: '' },
    'secLimit.name': { label: '约束名称', type: 'text', defaultValue: '停机窗口限制' },
    'secLimit.type': { label: '约束类型', type: 'text', defaultValue: '停机窗口' },
    'secLimit.object': {
      label: '约束对象',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'secLimit.required': { label: '是否必须', type: 'select', defaultValue: '是', options: ['是', '否'] },
    'secLimit.note': { label: '补充说明', type: 'textarea', defaultValue: '' },
    'delay.name': { label: '链路名称', type: 'text', defaultValue: '控制区到监控区主链路' },
    'delay.length': { label: '链路长度', type: 'text', defaultValue: '' },
    'delay.medium': { label: '介质类型', type: 'text', defaultValue: '双绞线' },
    'delay.hops': { label: '交换跳数', type: 'text', defaultValue: '' },
    'delay.boundary': { label: '边界转接', type: 'text', defaultValue: '无' },
    'delay.dmz': { label: '工业DMZ', type: 'select', defaultValue: '否', options: ['是', '否'] },
    'delay.demand': { label: '时延要求', type: 'text', defaultValue: '毫秒级' },
    'delay.risk': { label: '风险等级', type: 'select', defaultValue: '低', options: ['高', '中', '低'] },
    'delay.result': { label: '估算结论', type: 'textarea', defaultValue: '' },
    'perf.object': { label: '评估对象', type: 'text', defaultValue: '控制区上联' },
    'perf.type': { label: '对象类型', type: 'text', defaultValue: '区域' },
    'perf.load': { label: '通信负载', type: 'text', defaultValue: '低' },
    'perf.bandwidth': { label: '带宽等级', type: 'text', defaultValue: '百兆' },
    'perf.path': { label: '关键路径', type: 'text', defaultValue: '' },
    'perf.risk': { label: '性能风险', type: 'select', defaultValue: '低', options: ['高', '中', '低'] },
    'perf.result': { label: '评估结论', type: 'textarea', defaultValue: '' },
    'planningRule.name': { label: '规则名称', type: 'text', defaultValue: '区域优先划分' },
    'planningRule.domain': { label: '所属大类', type: 'text', defaultValue: '网络设计' },
    'planningRule.category': { label: '规则分类', type: 'text', defaultValue: '拓扑设计' },
    'planningRule.trigger': { label: '触发条件', type: 'textarea', defaultValue: '' },
    'planningRule.scene': { label: '适用场景', type: 'text', defaultValue: '' },
    'planningRule.recommend': { label: '推荐动作', type: 'textarea', defaultValue: '' },
    'planningRule.avoid': { label: '应避免', type: 'textarea', defaultValue: '' },
    'planningRule.reason': { label: '设计理由', type: 'textarea', defaultValue: '' },
    'planningRule.impact': { label: '影响范围', type: 'text', defaultValue: '' },
    'planningRule.example': { label: '示例', type: 'textarea', defaultValue: '' },
    'planningRule.note': { label: '备注', type: 'textarea', defaultValue: '' },
    'scene.name': {
      label: '场景名称',
      type: 'text',
      defaultValue: '核心业务场景',
    },
    'scene.mode': {
      label: '通信方式',
      type: 'text',
      defaultValue: '周期通信',
    },
    'scene.source': {
      label: '源对象',
      type: 'text',
      defaultValue: '',
    },
    'scene.target': {
      label: '目标对象',
      type: 'text',
      defaultValue: '',
    },
    'scene.purpose': {
      label: '业务目的',
      type: 'text',
      defaultValue: '生产控制',
    },
    'scene.medium': {
      label: '通信介质',
      type: 'text',
      defaultValue: '有线',
    },
    'scene.continuity': {
      label: '连续性要求',
      type: 'text',
      defaultValue: '高',
    },
    'scene.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'overview.name': {
      label: '范围名称',
      type: 'text',
      defaultValue: '主项目范围',
    },
    'overview.space': {
      label: '空间范围',
      type: 'text',
      defaultValue: '',
    },
    'overview.distribution': {
      label: '分布方式',
      type: 'text',
      defaultValue: '',
    },
    'overview.cross': {
      label: '跨域情况',
      type: 'text',
      defaultValue: '',
    },
    'overview.scale': {
      label: '总体规模',
      type: 'text',
      defaultValue: '',
    },
    'overview.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'asset.name': {
      label: '对象名称',
      type: 'text',
      defaultValue: 'PLC-01',
    },
    'asset.type': {
      label: '对象类型',
      type: 'text',
      defaultValue: 'PLC',
    },
    'asset.system': {
      label: '所属系统',
      type: 'text',
      defaultValue: '',
    },
    'asset.location': {
      label: '部署位置',
      type: 'text',
      defaultValue: '',
    },
    'asset.level': {
      label: '网络层级',
      type: 'text',
      defaultValue: 'Level 1',
    },
    'asset.status': {
      label: '对象状态',
      type: 'text',
      defaultValue: '在用',
    },
    'asset.access': {
      label: '接入方式',
      type: 'text',
      defaultValue: '有线固定接入',
    },
    'asset.criticality': {
      label: '关键等级',
      type: 'select',
      defaultValue: '高',
      options: ['高', '中', '低'],
    },
    'asset.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'env.topic': {
      label: '环境主题',
      type: 'text',
      defaultValue: '现场环境条件',
    },
    'env.interference': {
      label: '干扰情况',
      type: 'text',
      defaultValue: '',
    },
    'env.install': {
      label: '安装条件',
      type: 'text',
      defaultValue: '',
    },
    'env.distance': {
      label: '距离要求',
      type: 'text',
      defaultValue: '',
    },
    'env.medium': {
      label: '介质条件',
      type: 'text',
      defaultValue: '',
    },
    'env.power': {
      label: '供电条件',
      type: 'text',
      defaultValue: '',
    },
    'env.wireless': {
      label: '无线条件',
      type: 'text',
      defaultValue: '',
    },
    'env.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'zone.businessZone': {
      label: '引用业务区域',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'business-description',
        field: 'scene.name',
        dedupe: true,
      },
    },
    'secScenario.name': {
      label: '场景名称',
      type: 'text',
      defaultValue: '本地生产场景',
    },
    'secScenario.type': {
      label: '场景类型',
      type: 'text',
      defaultValue: '本地生产',
    },
    'secScenario.scope': {
      label: '覆盖范围',
      type: 'text',
      defaultValue: '',
    },
    'secScenario.remote': {
      label: '远程访问',
      type: 'text',
      defaultValue: '无',
    },
    'secScenario.external': {
      label: '外部互联',
      type: 'text',
      defaultValue: '无',
    },
    'secScenario.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'secExposure.name': {
      label: '暴露对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'secExposure.relatedScenario': {
      label: '关联安全场景',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'security-scenario',
        field: 'secScenario.name',
        dedupe: true,
      },
    },
    'secExposure.type': {
      label: '暴露类型',
      type: 'select',
      defaultValue: '远程接入',
      options: ['远程接入', '外部互联', '无线接入', '移动介质', '供应商维护'],
    },
    'secExposure.source': {
      label: '暴露来源',
      type: 'text',
      defaultValue: '',
    },
    'secExposure.control': {
      label: '现有控制',
      type: 'textarea',
      defaultValue: '',
    },
    'secExposure.risk': {
      label: '初步风险',
      type: 'select',
      defaultValue: '中',
      options: ['高', '中', '低'],
    },
    'secExposure.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'secConsequence.name': {
      label: '对象名称',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'secConsequence.relatedScenario': {
      label: '关联安全场景',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'security-scenario',
        field: 'secScenario.name',
        dedupe: true,
      },
    },
    'secConsequence.type': {
      label: '影响类型',
      type: 'select',
      defaultValue: '生产中断',
      options: ['生产中断', '质量波动', '数据中断', '设备停机', '安全事故'],
    },
    'secConsequence.impact': {
      label: '影响描述',
      type: 'textarea',
      defaultValue: '',
    },
    'secConsequence.severity': {
      label: '严重程度',
      type: 'select',
      defaultValue: '高',
      options: ['高', '中', '低'],
    },
    'secConsequence.recovery': {
      label: '恢复要求',
      type: 'text',
      defaultValue: '',
    },
    'secConsequence.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'secBaseline.type': {
      label: '基线类型',
      type: 'select',
      defaultValue: '边界防护',
      options: ['边界防护', '账户权限', '远程访问', '日志审计', '补丁维护'],
    },
    'secBaseline.object': {
      label: '对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'secBaseline.status': {
      label: '现状状态',
      type: 'select',
      defaultValue: '已具备',
      options: ['已具备', '部分具备', '未具备'],
    },
    'secBaseline.evidence': {
      label: '证据',
      type: 'textarea',
      defaultValue: '',
    },
    'secBaseline.gap': {
      label: '缺口判断',
      type: 'select',
      defaultValue: '基本满足',
      options: ['基本满足', '存在缺口', '明显不足'],
    },
    'secBaseline.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'secKey.name': {
      label: '关键对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'secKey.type': {
      label: '对象类型',
      type: 'text',
      defaultValue: '控制器',
    },
    'secKey.reason': {
      label: '关键原因',
      type: 'textarea',
      defaultValue: '',
    },
    'secKey.focus': {
      label: '关注点',
      type: 'textarea',
      defaultValue: '',
    },
    'secKey.priority': {
      label: '优先级',
      type: 'select',
      defaultValue: '高',
      options: ['高', '中', '低'],
    },
    'secKey.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
    'threat.relatedScenario': {
      label: '关联安全场景',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'security-scenario',
        field: 'secScenario.name',
        dedupe: true,
      },
    },
    'threat.relatedExposure': {
      label: '关联暴露面',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'exposure-analysis',
        field: 'secExposure.name',
        dedupe: true,
      },
    },
    'threat.relatedConsequence': {
      label: '关联后果',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'consequence-analysis',
        field: 'secConsequence.name',
        dedupe: true,
      },
    },
    'zone.isolationNotes': {
      label: '隔离补充说明',
      type: 'textarea',
      defaultValue: '当采用核心隔离时，需要补充边界访问控制与例外说明。',
      visibleWhen: {
        field: 'zone.strategy',
        equals: '核心隔离',
      },
    },
    'threat.source': {
      label: '威胁来源',
      type: 'textarea',
      defaultValue: '远程维护、供应链引入、内部误操作',
    },
    'threat.surface': {
      label: '攻击面',
      type: 'textarea',
      defaultValue: 'VPN 接入、工程师站、边界交换节点',
    },
    'threat.asset': {
      label: '关键影响对象',
      type: 'select',
      defaultValue: 'PLC-01',
      optionsSource: {
        type: 'record-field',
        recordPage: 'asset-allocation',
        field: 'asset.name',
        dedupe: true,
      },
    },
    'threat.relatedConstraint': {
      label: '关联实施约束',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'implementation-constraints',
        field: 'constraint.name',
        dedupe: true,
      },
    },
    'threat.relatedEnvironment': {
      label: '关联环境条件',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'environment-conditions',
        field: 'env.topic',
        dedupe: true,
      },
    },
    'risk.level': {
      label: '风险等级',
      type: 'select',
      defaultValue: '中',
      options: ['低', '中', '高'],
    },
    'risk.relatedBaseline': {
      label: '关联基线检查',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'baseline-check',
        field: 'secBaseline.object',
        dedupe: true,
      },
    },
    'risk.relatedKeyAsset': {
      label: '关联关键对象',
      type: 'select',
      defaultValue: '',
      optionsSource: {
        type: 'record-field',
        recordPage: 'key-asset-analysis',
        field: 'secKey.name',
        dedupe: true,
      },
    },
    'risk.impact': {
      label: '影响描述',
      type: 'textarea',
      defaultValue: '可能导致产线停机与远程运维中断',
    },
    'risk.priority': {
      label: '处置优先级',
      type: 'select',
      defaultValue: 'P1',
      options: ['P1', 'P2', 'P3'],
    },
    'constraint.name': {
      label: '约束名称',
      type: 'text',
      defaultValue: '预算约束',
    },
    'constraint.type': {
      label: '约束类型',
      type: 'text',
      defaultValue: '预算',
    },
    'constraint.required': {
      label: '是否必须',
      type: 'select',
      defaultValue: '是',
      options: ['是', '否'],
    },
    'constraint.scope': {
      label: '影响范围',
      type: 'text',
      defaultValue: '',
    },
    'constraint.existing': {
      label: '现网继承',
      type: 'text',
      defaultValue: '',
    },
    'constraint.note': {
      label: '补充说明',
      type: 'textarea',
      defaultValue: '',
    },
  },
  outputs: {
    'design-result': {
      'project-summary': ['project.name', 'project.customer', 'project.industry'],
      'business-summary': {
        recordPage: 'business-description',
        fields: ['scene.name', 'scene.source', 'scene.target', 'scene.purpose'],
      },
      'scope-summary': {
        recordPage: 'scope-definition',
        fields: ['overview.name', 'overview.space', 'overview.distribution', 'overview.cross', 'overview.scale'],
      },
      'asset-summary': {
        recordPage: 'asset-allocation',
        fields: ['asset.name', 'asset.type', 'asset.system', 'asset.location'],
      },
      'environment-summary': {
        recordPage: 'environment-conditions',
        fields: ['env.topic', 'env.interference', 'env.install', 'env.distance', 'env.medium'],
      },
      'constraint-summary': {
        recordPage: 'implementation-constraints',
        fields: ['constraint.name', 'constraint.type', 'constraint.required', 'constraint.scope', 'constraint.existing'],
      },
      'security-scenario-summary': {
        recordPage: 'security-scenario',
        fields: ['secScenario.name', 'secScenario.type', 'secScenario.scope', 'secScenario.remote', 'secScenario.external'],
      },
      'exposure-summary': {
        recordPage: 'exposure-analysis',
        fields: ['secExposure.name', 'secExposure.relatedScenario', 'secExposure.type', 'secExposure.source', 'secExposure.risk'],
      },
      'consequence-summary': {
        recordPage: 'consequence-analysis',
        fields: ['secConsequence.name', 'secConsequence.relatedScenario', 'secConsequence.type', 'secConsequence.severity', 'secConsequence.recovery'],
      },
      'baseline-summary': {
        recordPage: 'baseline-check',
        fields: ['secBaseline.object', 'secBaseline.type', 'secBaseline.status', 'secBaseline.gap'],
      },
      'key-asset-summary': {
        recordPage: 'key-asset-analysis',
        fields: ['secKey.name', 'secKey.type', 'secKey.focus', 'secKey.priority'],
      },
      'zone-summary': ['zone.scope', 'zone.businessZone', 'zone.relatedAsset', 'zone.strategy'],
      'principle-summary': {
        recordPage: 'design-principles',
        fields: ['principle.category', 'principle.main', 'principle.scope', 'principle.basis'],
      },
      'topology-summary': {
        recordPage: 'network-topology',
        fields: ['topology.object', 'topology.type', 'topology.backbone', 'topology.access'],
      },
      'layer-summary': {
        recordPage: 'layer-design',
        fields: ['layer.object', 'layer.mode', 'layer.structure', 'layer.policy'],
      },
      'performance-summary': {
        recordPage: 'performance-design',
        fields: ['performance.object', 'performance.latency', 'performance.bandwidth', 'performance.measure'],
      },
      'stability-summary': {
        recordPage: 'stability-design',
        fields: ['stability.object', 'stability.target', 'stability.risk', 'stability.measure'],
      },
      'redundancy-summary': {
        recordPage: 'redundancy-design',
        fields: ['redundancy.object', 'redundancy.target', 'redundancy.mode', 'redundancy.switch'],
      },
      'seg-summary': {
        recordPage: 'segmentation-plan',
        fields: ['seg.object', 'seg.purpose', 'seg.range', 'seg.margin'],
      },
      'access-summary': {
        recordPage: 'access-design',
        fields: ['access.object', 'access.type', 'access.scope', 'access.limit'],
      },
      'selection-summary': {
        recordPage: 'selection-design',
        fields: ['selection.object', 'selection.demand', 'selection.capability', 'selection.result'],
      },
      'deployment-summary': {
        recordPage: 'deployment-design',
        fields: ['deployment.object', 'deployment.location', 'deployment.install', 'deployment.cabling'],
      },
      'link-summary': {
        recordPage: 'link-design',
        fields: ['link.source', 'link.target', 'link.scene', 'link.role', 'link.redundant'],
      },
      'conduit-summary': {
        recordPage: 'conduit-design',
        fields: ['conduit.source', 'conduit.target', 'conduit.scene', 'conduit.purpose', 'conduit.criticality'],
      },
      'interconnect-summary': {
        recordPage: 'interconnect-design',
        fields: ['interconnect.source', 'interconnect.target', 'interconnect.structure', 'interconnect.boundary'],
      },
      'tech-summary': {
        recordPage: 'tech-selection',
        fields: ['tech.name', 'tech.category', 'tech.technology', 'tech.scopeTarget', 'tech.confirmStatus'],
      },
      'security-limit-summary': {
        recordPage: 'security-limit',
        fields: ['secLimit.name', 'secLimit.type', 'secLimit.object', 'secLimit.required'],
      },
      'delay-summary': {
        recordPage: 'delay-analysis',
        fields: ['delay.name', 'delay.medium', 'delay.demand', 'delay.risk', 'delay.result'],
      },
      'perf-summary': {
        recordPage: 'perf-evaluation',
        fields: ['perf.object', 'perf.type', 'perf.load', 'perf.bandwidth', 'perf.result'],
      },
      'planning-rule-summary': {
        recordPage: 'planning-rules',
        fields: ['planningRule.name', 'planningRule.domain', 'planningRule.category', 'planningRule.scene'],
      },
      'security-analysis-text': {
        lines: [
          {
            type: 'record-join',
            label: '业务后果与影响',
            recordPage: 'consequence-analysis',
            labels: false,
            fields: ['secConsequence.name', 'secConsequence.type', 'secConsequence.impact', 'secConsequence.severity', 'secConsequence.recovery'],
          },
          {
            type: 'record-join',
            label: '暴露面与访问控制',
            recordPage: 'exposure-analysis',
            labels: false,
            fields: ['secExposure.name', 'secExposure.type', 'secExposure.source', 'secExposure.control', 'secExposure.risk'],
          },
          {
            type: 'record-join',
            label: '安全基线与缺口',
            recordPage: 'baseline-check',
            labels: false,
            fields: ['secBaseline.object', 'secBaseline.type', 'secBaseline.status', 'secBaseline.gap'],
          },
          {
            type: 'record-join',
            label: '关键保护对象',
            recordPage: 'key-asset-analysis',
            labels: false,
            fields: ['secKey.name', 'secKey.type', 'secKey.priority', 'secKey.focus'],
          },
        ],
        paragraphs: [
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '本项目的设计边界不仅来自业务需求，也来自安全与实施条件约束。后续设计需确保跨区访问受控、关键对象可审计、环境条件可满足、现网继承关系清晰，同时在停机窗口、第三方协同、扩容预留和维护组织方式上具备可执行性。' },
            ],
          },
        ],
      },
      'project-judgement': {
        paragraphs: [
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '项目总体判断：' },
              {
                kind: 'field-join',
                labels: false,
                fields: ['project.goal', 'project.scope', 'zone.strategy', 'risk.priority'],
              },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '重点关注事项：' },
              {
                kind: 'record-join',
                recordPage: 'key-asset-analysis',
                labels: false,
                fields: ['secKey.name', 'secKey.focus'],
              },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '关键约束清单：' },
              {
                kind: 'record-join',
                recordPage: 'implementation-constraints',
                labels: false,
                fields: ['constraint.name', 'constraint.type', 'constraint.required'],
              },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '综合当前信息，本项目的设计重点不在单一设备选型，而在于把业务协同关系、区域边界、对象接入、总体网络结构、实施约束和后续扩展要求统一收敛到一套完整方案中，为后续设计概要、网络拓扑和 IP 规划提供一致输入。' },
            ],
          },
        ],
      },
      'next-actions': {
        bullets: [
          { text: '明确网络总体拓扑、分层关系与区域边界，避免业务路径和结构路径脱节。' },
          { text: '明确关键对象的接入方式、部署位置、边界控制与维护路径。' },
          { text: '明确地址分段原则、容量依据、网关位置及扩容预留策略。' },
          { text: '明确现网继承、实施窗口、第三方协同和上线切换要求。' },
          { text: '输出设计概要、网络拓扑和 IP 规划成果，并进行一致性校核。' },
        ],
      },
    },
    'delivery-list': {
      'delivery-summary': ['project.name', 'zone.strategy', 'risk.priority'],
      'delivery-focus': {
        lines: [
          {
            type: 'field-join',
            label: '当前交付主线',
            labels: false,
            fields: ['project.name', 'project.delivery', 'zone.strategy', 'risk.priority'],
          },
          {
            type: 'record-join',
            label: '关键对象与关注点',
            recordPage: 'key-asset-analysis',
            labels: false,
            fields: ['secKey.name', 'secKey.focus', 'secKey.priority'],
          },
          {
            type: 'record-join',
            label: '建议优先处理项',
            recordPage: 'baseline-check',
            labels: false,
            fields: ['secBaseline.object', 'secBaseline.type', 'secBaseline.gap'],
          },
        ],
      },
    },
    'topology-result': {
      'topology-drawing-brief': {
        paragraphs: [
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '绘图目标：体现本项目的区域边界、网络总体结构、关键对象、关键链路、边界设备、冗余关系、维护入口与对象部署关系。' },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '项目背景：' },
              { kind: 'field', key: 'project.name' },
              { kind: 'text', value: ' / ' },
              { kind: 'field', key: 'project.scope' },
              { kind: 'text', value: ' / ' },
              { kind: 'field', key: 'project.goal' },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '绘图要求：必须明确表现层级、区域、边界、关键对象、关键链路、边界设备、维护入口与冗余关系；同类普通对象可按逻辑归组表示，但核心交换机、边界设备、服务器、控制器和关键链路应单独绘出。' },
            ],
          },
        ],
        bullets: [
          {
            type: 'record-join',
            label: '网络总体拓扑',
            recordPage: 'network-topology',
            labels: false,
            fields: ['topology.object', 'topology.type', 'topology.backbone', 'topology.access'],
          },
          {
            type: 'record-join',
            label: '网络分层',
            recordPage: 'layer-design',
            labels: false,
            fields: ['layer.object', 'layer.mode', 'layer.structure', 'layer.policy'],
          },
          {
            type: 'record-join',
            label: '关键对象',
            recordPage: 'asset-allocation',
            labels: false,
            fields: ['asset.name', 'asset.type', 'asset.level', 'asset.location'],
          },
          {
            type: 'record-join',
            label: '关键链路',
            recordPage: 'link-design',
            labels: false,
            fields: ['link.source', 'link.target', 'link.scene', 'link.role', 'link.redundant'],
          },
          {
            type: 'record-join',
            label: '区域通道',
            recordPage: 'conduit-design',
            labels: false,
            fields: ['conduit.source', 'conduit.target', 'conduit.scene', 'conduit.control', 'conduit.criticality'],
          },
          {
            type: 'record-join',
            label: '边界互联',
            recordPage: 'interconnect-design',
            labels: false,
            fields: ['interconnect.source', 'interconnect.target', 'interconnect.structure', 'interconnect.boundary'],
          },
          {
            type: 'record-join',
            label: '技术选择',
            recordPage: 'tech-selection',
            labels: false,
            fields: ['tech.name', 'tech.technology', 'tech.scopeTarget', 'tech.constraint'],
          },
          {
            type: 'record-join',
            label: '部署与位置提示',
            recordPage: 'deployment-design',
            labels: false,
            fields: ['deployment.object', 'deployment.location', 'deployment.install'],
          },
        ],
      },
    },
    'ip-plan-result': {
      'ip-plan-brief': {
        paragraphs: [
          {
            type: 'template',
            parts: [
              { kind: 'text', value: 'IP 规划目标：形成适合方案设计、实施配置和交付存档使用的地址规划结果。' },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '项目背景：' },
              { kind: 'field', key: 'project.name' },
              { kind: 'text', value: ' / ' },
              { kind: 'field', key: 'project.scope' },
              { kind: 'text', value: ' / ' },
              { kind: 'field', key: 'project.goal' },
            ],
          },
          {
            type: 'template',
            parts: [
              { kind: 'text', value: '规划说明：IP 地址规划应体现区域隔离、网络层次和业务边界，固定地址对象应便于管理、维护和故障定位，地址段需考虑后续扩展余量，并避免与既有地址规则冲突。' },
            ],
          },
        ],
        bullets: [
          {
            type: 'record-join',
            label: '地址分段依据',
            recordPage: 'segmentation-plan',
            labels: false,
            fields: ['seg.object', 'seg.purpose', 'seg.range', 'seg.margin'],
          },
          {
            type: 'record-join',
            label: '分层结构',
            recordPage: 'layer-design',
            labels: false,
            fields: ['layer.object', 'layer.structure', 'layer.mode'],
          },
          {
            type: 'record-join',
            label: '接入与接口预留',
            recordPage: 'access-design',
            labels: false,
            fields: ['access.object', 'access.type', 'access.limit'],
          },
          {
            type: 'record-join',
            label: '关键约束',
            recordPage: 'implementation-constraints',
            labels: false,
            fields: ['constraint.name', 'constraint.scope', 'constraint.existing'],
          },
          {
            type: 'record-join',
            label: '安全约束',
            recordPage: 'security-limit',
            labels: false,
            fields: ['secLimit.name', 'secLimit.object', 'secLimit.required'],
          },
          {
            type: 'record-join',
            label: '通道与边界控制',
            recordPage: 'conduit-design',
            labels: false,
            fields: ['conduit.source', 'conduit.target', 'conduit.control', 'conduit.delay'],
          },
        ],
        codeBlocks: [
          {
            type: 'record-join',
            label: '建议地址表',
            recordPage: 'segmentation-plan',
            labels: false,
            fields: ['seg.object', 'seg.range', 'seg.purpose', 'seg.margin'],
          },
        ],
      },
    },
  },
  cases: [
    {
      key: 'isa95-iec62443-case-1',
      title: '案例一：离散制造产线改造',
      description: '聚焦产线边界梳理与控制区隔离策略。',
      formData: {
        'project.name': '离散制造产线改造项目',
        'project.customer': '某装备制造客户',
        'project.industry': '离散制造',
        'project.scope': '单车间',
        'project.goal': '改造',
        'project.delivery': '网络规划方案、地址规划、拓扑图与实施建议。',
        'project.owner': '张工',
        'project.confirmStatus': '业主已确认',
        'input.site': '苏州工厂',
        'input.assets': 'PLC\nHMI\n工程师站\n工业交换机',
        'input.constraints': '不停产切换、窗口期短',
        'zone.scope': '产线控制区与工业 DMZ',
        'zone.businessZone': '区域1',
        'zone.relatedAsset': 'PLC',
        'zone.strategy': '核心隔离',
        'zone.boundary': '按控制域与远程运维边界划分',
        'zone.isolationNotes': '对远程维护通道实施白名单与审计。',
        'threat.source': '远程接入与供应链维护',
        'threat.surface': 'VPN、工程师站、边界交换设备',
        'threat.asset': '核心控制器',
        'risk.level': '高',
        'risk.impact': '可能导致关键产线停机',
        'risk.priority': 'P1',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '离散制造产线改造项目',
            'project.customer': '某装备制造客户',
            'project.industry': '离散制造',
            'project.scope': '单车间',
            'project.goal': '改造',
            'project.delivery': '网络规划方案、地址规划、拓扑图与实施建议。',
            'project.owner': '张工',
            'project.confirmStatus': '业主已确认',
          },
        ],
        'business-description': [
          {
            'scene.name': 'MES 下发工单',
            'scene.mode': '周期通信',
            'scene.source': 'MES-01',
            'scene.target': 'SCADA-01',
            'scene.purpose': '生产任务下发',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
          {
            'scene.name': 'SCADA 采集 PLC',
            'scene.mode': '周期通信',
            'scene.source': 'SCADA-01',
            'scene.target': 'PLC-01',
            'scene.purpose': '状态采集与受限控制',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '总装车间与信息中心',
            'overview.space': '1 个厂区 / 2 个车间 / 1 个信息中心',
            'overview.distribution': '生产区与信息中心分布',
            'overview.cross': '存在跨区访问',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'MES-01',
            'asset.type': 'MES',
            'asset.system': 'MES系统',
            'asset.location': '信息中心',
            'asset.level': 'Level 4',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
          {
            'asset.name': 'PLC-01',
            'asset.type': 'PLC',
            'asset.system': '产线控制系统',
            'asset.location': '总装车间',
            'asset.level': 'Level 1',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
        'environment-conditions': [
          {
            'env.topic': '总装车间环境',
            'env.interference': '一般工业干扰',
            'env.install': '桥架敷设',
            'env.distance': '车间至信息中心 300m',
            'env.medium': '工业以太网',
            'env.power': '双路供电',
            'env.wireless': '无',
            'env.note': '',
          },
        ],
        'security-scenario': [
          {
            'secScenario.name': '供应商远程维护',
            'secScenario.type': '远程维护',
            'secScenario.scope': 'PLC 与工程师站',
            'secScenario.remote': '有',
            'secScenario.external': '有',
            'secScenario.note': '',
          },
        ],
        'exposure-analysis': [
          {
            'secExposure.name': 'PLC-01',
            'secExposure.relatedScenario': '供应商远程维护',
            'secExposure.type': '远程接入',
            'secExposure.source': '供应商 VPN 维护',
            'secExposure.control': '账号口令 + 白名单',
            'secExposure.risk': '中',
            'secExposure.note': '',
          },
        ],
        'consequence-analysis': [
          {
            'secConsequence.name': 'PLC-01',
            'secConsequence.relatedScenario': '供应商远程维护',
            'secConsequence.type': '生产中断',
            'secConsequence.impact': '异常操作导致产线停机',
            'secConsequence.severity': '高',
            'secConsequence.recovery': '30 分钟内恢复',
            'secConsequence.note': '',
          },
        ],
        'baseline-check': [
          {
            'secBaseline.type': '远程访问',
            'secBaseline.object': 'PLC-01',
            'secBaseline.status': '部分具备',
            'secBaseline.evidence': '已有 VPN 账号审批流程',
            'secBaseline.gap': '存在缺口',
            'secBaseline.note': '',
          },
        ],
        'key-asset-analysis': [
          {
            'secKey.name': 'PLC-01',
            'secKey.type': '控制器',
            'secKey.reason': '直接影响主产线连续运行',
            'secKey.focus': '远程维护边界、变更审计',
            'secKey.priority': '高',
            'secKey.note': '',
          },
        ],
        'design-principles': [
          {
            'principle.category': '区域划分思路',
            'principle.main': '优先按产线与控制边界划分',
            'principle.scope': '总装产线与工业DMZ',
            'principle.basis': '业务连续性与远程运维边界',
            'principle.desc': '保证控制流量与维护流量边界清晰',
            'principle.note': '',
          },
        ],
        'network-topology': [
          {
            'topology.object': '产线主干网络',
            'topology.type': '星型',
            'topology.backbone': '车间汇聚交换机双上联',
            'topology.access': '控制柜交换机接入',
            'topology.scope': '总装车间',
            'topology.basis': '便于维护与边界收敛',
            'topology.tech': '工业以太网',
            'topology.note': '',
          },
        ],
        'layer-design': [
          {
            'layer.object': '车间汇聚层',
            'layer.mode': '二三层混合',
            'layer.structure': '核心 / 汇聚 / 接入',
            'layer.policy': '控制层稳定，DMZ 单独边界控制',
            'layer.scope': '总装车间与信息中心',
            'layer.note': '',
          },
        ],
        'segmentation-plan': [
          {
            'seg.object': 'PLC 控制网段',
            'seg.purpose': '控制通信',
            'seg.range': '192.168.10.0/24',
            'seg.margin': '预留 30%',
            'seg.note': '',
          },
        ],
        'performance-design': [
          {
            'performance.object': 'PLC 控制主链路',
            'performance.latency': '毫秒级',
            'performance.bandwidth': '百兆',
            'performance.clock': '10ms 周期',
            'performance.measure': '核心链路优先保障控制流量',
            'performance.service': 'PLC 控制通信',
            'performance.delay': '≤10ms',
            'performance.risk': '广播风暴影响控制报文',
            'performance.note': '',
          },
        ],
        'stability-design': [
          {
            'stability.object': '车间汇聚主链路',
            'stability.target': '连续稳定运行',
            'stability.risk': '维护误操作与边界异常',
            'stability.measure': '配置基线 + 变更审批',
            'stability.control': '链路监测与日志审计',
            'stability.maintain': '窗口期维护',
            'stability.note': '',
          },
        ],
        'redundancy-design': [
          {
            'redundancy.object': '汇聚上联链路',
            'redundancy.target': '核心不中断',
            'redundancy.mode': '主备',
            'redundancy.switch': '30s 内切换',
            'redundancy.note': '',
          },
        ],
        'access-design': [
          {
            'access.object': 'PLC-01',
            'access.type': '有线',
            'access.scope': '总装车间控制柜',
            'access.limit': '仅允许控制网交换机接入',
            'access.reason': '保障控制链路稳定',
            'access.note': '',
          },
        ],
        'selection-design': [
          {
            'selection.object': 'PLC-01',
            'selection.demand': '控制通信',
            'selection.capability': '工业协议支持、宽温',
            'selection.result': '工业交换机千兆上联',
            'selection.reason': '满足实时性与环境要求',
            'selection.note': '',
          },
        ],
        'deployment-design': [
          {
            'deployment.object': 'PLC-01',
            'deployment.location': '总装车间控制柜',
            'deployment.install': '机柜内导轨安装',
            'deployment.cabling': '屏蔽双绞线',
            'deployment.requirement': '不停产窗口切换',
            'deployment.note': '',
          },
        ],
        'link-design': [
          {
            'link.source': 'SCADA-01',
            'link.target': 'PLC-01',
            'link.scene': 'SCADA 采集 PLC',
            'link.type': '电口',
            'link.role': '控制采集链路',
            'link.redundant': '否',
            'link.sourceLocation': '信息中心',
            'link.targetLocation': '总装车间',
            'link.medium': '工业以太网 / 百兆',
            'link.note': '',
          },
        ],
        'conduit-design': [
          {
            'conduit.source': '控制区',
            'conduit.target': '监控区',
            'conduit.scene': 'SCADA 采集 PLC',
            'conduit.purpose': '控制采集',
            'conduit.direction': '双向',
            'conduit.medium': '有线',
            'conduit.control': '白名单放行',
            'conduit.delay': '毫秒级',
            'conduit.criticality': '高',
            'conduit.note': '',
          },
        ],
        'interconnect-design': [
          {
            'interconnect.source': '控制区',
            'interconnect.target': '监控区',
            'interconnect.structure': '工业防火墙互联',
            'interconnect.boundary': '工业防火墙-01',
            'interconnect.control': '仅开放必要端口',
            'interconnect.note': '',
          },
        ],
        'tech-selection': [
          {
            'tech.name': '控制区主干技术',
            'tech.category': '网络结构',
            'tech.technology': '工业以太网',
            'tech.scopeType': '对象',
            'tech.scopeTarget': 'PLC-01',
            'tech.scopeNote': '',
            'tech.goal': '保障实时控制通信',
            'tech.reason': '成熟稳定，便于维护',
            'tech.alternative': 'TSN',
            'tech.alternativeReason': '当前项目无必要',
            'tech.constraint': '不停产切换',
            'tech.confirmStatus': '待确认',
            'tech.note': '',
          },
        ],
        'security-limit': [
          {
            'secLimit.name': '不停产切换限制',
            'secLimit.type': '停机窗口',
            'secLimit.object': 'PLC-01',
            'secLimit.required': '是',
            'secLimit.note': '',
          },
        ],
      },
    },
    {
      key: 'isa95-iec62443-case-2',
      title: '案例二：流程工业远程运维整治',
      description: '聚焦远程接入面收敛与分区分域。',
      formData: {
        'project.name': '流程工业远程运维整治项目',
        'project.customer': '某化工客户',
        'project.industry': '流程工业',
        'project.scope': '专项系统',
        'project.goal': '安全加固',
        'project.delivery': '边界梳理、安全策略建议与整改清单。',
        'project.owner': '李经理',
        'project.confirmStatus': '方案建议',
        'input.site': '宁波生产基地',
        'input.assets': 'DCS\n工程师站\n历史数据库',
        'input.constraints': '合规审计压力高、变更窗口受限',
        'zone.scope': '控制区、监控区与 DMZ',
        'zone.businessZone': '工艺区',
        'zone.relatedAsset': 'DCS',
        'zone.strategy': '分区分域',
        'zone.boundary': '按工艺系统与远程接入链路划分',
        'zone.isolationNotes': '',
        'threat.source': '供应商维护与跨网访问',
        'threat.surface': '远程维护平台、跳板路径',
        'threat.asset': 'DCS 控制节点',
        'risk.level': '中',
        'risk.impact': '可能造成关键工艺监控受影响',
        'risk.priority': 'P2',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '流程工业远程运维整治项目',
            'project.customer': '某化工客户',
            'project.industry': '流程工业',
            'project.scope': '专项系统',
            'project.goal': '安全加固',
            'project.delivery': '边界梳理、安全策略建议与整改清单。',
            'project.owner': '李经理',
            'project.confirmStatus': '方案建议',
          },
        ],
        'business-description': [
          {
            'scene.name': '远程维护访问',
            'scene.mode': '按需通信',
            'scene.source': '堡垒机',
            'scene.target': '工程师站',
            'scene.purpose': '远程维护',
            'scene.medium': 'VPN',
            'scene.continuity': '中',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '主控室与生产控制区',
            'overview.space': '单厂区 / 主控室 / 生产装置区',
            'overview.distribution': '集中控制 + 分布现场',
            'overview.cross': '存在远程维护跨域',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'DCS-01',
            'asset.type': 'DCS',
            'asset.system': '控制系统',
            'asset.location': '主控室',
            'asset.level': 'Level 2',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
        'environment-conditions': [
          {
            'env.topic': '主控室环境',
            'env.interference': '低干扰',
            'env.install': '机柜集中安装',
            'env.distance': '主控室到现场装置区 500m',
            'env.medium': '光纤 + 工业以太网',
            'env.power': 'UPS 保障',
            'env.wireless': '无',
            'env.note': '',
          },
        ],
        'security-scenario': [
          {
            'secScenario.name': '中控与罐区跨区访问',
            'secScenario.type': '跨区访问',
            'secScenario.scope': 'DCS 与边界服务器',
            'secScenario.remote': '无',
            'secScenario.external': '有',
            'secScenario.note': '',
          },
        ],
        'exposure-analysis': [
          {
            'secExposure.name': 'DCS-01',
            'secExposure.relatedScenario': '中控与罐区跨区访问',
            'secExposure.type': '外部互联',
            'secExposure.source': '生产管理网访问中控区',
            'secExposure.control': '防火墙 + 访问白名单',
            'secExposure.risk': '中',
            'secExposure.note': '',
          },
        ],
        'consequence-analysis': [
          {
            'secConsequence.name': 'DCS-01',
            'secConsequence.relatedScenario': '中控与罐区跨区访问',
            'secConsequence.type': '设备停机',
            'secConsequence.impact': '控制异常导致工艺停机',
            'secConsequence.severity': '高',
            'secConsequence.recovery': '1 小时内恢复稳定',
            'secConsequence.note': '',
          },
        ],
        'baseline-check': [
          {
            'secBaseline.type': '边界防护',
            'secBaseline.object': 'DCS-01',
            'secBaseline.status': '已具备',
            'secBaseline.evidence': '现网已有工业防火墙',
            'secBaseline.gap': '基本满足',
            'secBaseline.note': '',
          },
        ],
        'key-asset-analysis': [
          {
            'secKey.name': 'DCS-01',
            'secKey.type': '控制系统',
            'secKey.reason': '承担核心工艺控制',
            'secKey.focus': '边界访问控制、工艺连续性',
            'secKey.priority': '高',
            'secKey.note': '',
          },
        ],
        'design-principles': [
          {
            'principle.category': '安全边界思路',
            'principle.main': '优先分区分域并控制跨区访问',
            'principle.scope': '主控室与装置区',
            'principle.basis': '跨区访问与合规审计要求',
            'principle.desc': '边界访问统一收口到工业防火墙',
            'principle.note': '',
          },
        ],
        'network-topology': [
          {
            'topology.object': '控制与监控主干',
            'topology.type': '星型',
            'topology.backbone': '主控室双核心',
            'topology.access': '装置区交换机汇聚上联',
            'topology.scope': '主控室与现场装置区',
            'topology.basis': '便于边界统一管理',
            'topology.tech': '工业以太网 + 防火墙',
            'topology.note': '',
          },
        ],
        'layer-design': [
          {
            'layer.object': '控制主干层',
            'layer.mode': '三层',
            'layer.structure': '核心 / 区域汇聚 / 接入',
            'layer.policy': '生产区与管理区三层隔离',
            'layer.scope': '主控室与现场',
            'layer.note': '',
          },
        ],
        'segmentation-plan': [
          {
            'seg.object': 'DCS 控制网段',
            'seg.purpose': '控制与监控',
            'seg.range': '10.10.20.0/24',
            'seg.margin': '预留 25%',
            'seg.note': '',
          },
        ],
        'performance-design': [
          {
            'performance.object': 'DCS 控制主干',
            'performance.latency': '毫秒级',
            'performance.bandwidth': '千兆',
            'performance.clock': '20ms 周期',
            'performance.measure': '控制与历史数据分流',
            'performance.service': 'DCS 控制 / 历史采集',
            'performance.delay': '≤20ms',
            'performance.risk': '跨区访问占用主干带宽',
            'performance.note': '',
          },
        ],
        'stability-design': [
          {
            'stability.object': '主控室主干网络',
            'stability.target': '工艺监控持续可用',
            'stability.risk': '边界配置漂移',
            'stability.measure': '边界设备集中纳管',
            'stability.control': '工业防火墙统一策略',
            'stability.maintain': '季度审计复核',
            'stability.note': '',
          },
        ],
        'redundancy-design': [
          {
            'redundancy.object': '主控室双核心',
            'redundancy.target': '单点故障不中断',
            'redundancy.mode': '双活',
            'redundancy.switch': '故障自动收敛',
            'redundancy.note': '',
          },
        ],
        'access-design': [
          {
            'access.object': 'DCS-01',
            'access.type': '有线',
            'access.scope': '主控室控制网络',
            'access.limit': '跨区访问必须经边界防火墙',
            'access.reason': '满足合规要求',
            'access.note': '',
          },
        ],
        'selection-design': [
          {
            'selection.object': 'DCS-01',
            'selection.demand': '控制与历史采集',
            'selection.capability': '高可靠、支持冗余',
            'selection.result': '双核心 + 工业防火墙',
            'selection.reason': '满足连续性与边界要求',
            'selection.note': '',
          },
        ],
        'deployment-design': [
          {
            'deployment.object': 'DCS-01',
            'deployment.location': '主控室机柜区',
            'deployment.install': '机柜集中安装',
            'deployment.cabling': '光纤主干 + 铜缆接入',
            'deployment.requirement': '防爆区接口需隔离处理',
            'deployment.note': '',
          },
        ],
        'link-design': [
          {
            'link.source': 'DCS-01',
            'link.target': '工程师站',
            'link.scene': '远程维护访问',
            'link.type': '电口',
            'link.role': '维护链路',
            'link.redundant': '是',
            'link.sourceLocation': '主控室',
            'link.targetLocation': '主控室',
            'link.medium': '工业以太网 / 千兆',
            'link.note': '',
          },
        ],
        'conduit-design': [
          {
            'conduit.source': '控制区',
            'conduit.target': '管理区',
            'conduit.scene': '远程维护访问',
            'conduit.purpose': '维护访问',
            'conduit.direction': '双向',
            'conduit.medium': '有线',
            'conduit.control': '堡垒机 + 防火墙审批放行',
            'conduit.delay': '秒级',
            'conduit.criticality': '高',
            'conduit.note': '',
          },
        ],
        'interconnect-design': [
          {
            'interconnect.source': '控制区',
            'interconnect.target': '管理区',
            'interconnect.structure': 'DMZ 边界互联',
            'interconnect.boundary': '工业防火墙 + 跳板机',
            'interconnect.control': '经堡垒机审批审计',
            'interconnect.note': '',
          },
        ],
        'tech-selection': [
          {
            'tech.name': '边界隔离技术',
            'tech.category': '安全边界',
            'tech.technology': '工业防火墙',
            'tech.scopeType': '对象',
            'tech.scopeTarget': 'DCS-01',
            'tech.scopeNote': '',
            'tech.goal': '远程维护收口与审计',
            'tech.reason': '满足边界控制与合规',
            'tech.alternative': '普通 IT 防火墙',
            'tech.alternativeReason': '工业协议适配不足',
            'tech.constraint': '防爆区域限制',
            'tech.confirmStatus': '待确认',
            'tech.note': '',
          },
        ],
        'security-limit': [
          {
            'secLimit.name': '防爆区维护限制',
            'secLimit.type': '维护方式',
            'secLimit.object': 'DCS-01',
            'secLimit.required': '是',
            'secLimit.note': '',
          },
        ],
      },
    },
    {
      key: 'isa95-iec62443-case-3',
      title: '案例三：能源站网络分层优化',
      description: '聚焦区域边界清晰化与输出清单整理。',
      formData: {
        'project.name': '能源站网络分层优化项目',
        'project.customer': '某能源企业',
        'project.industry': '能源电力',
        'project.scope': '单厂区',
        'project.goal': '升级扩展',
        'project.delivery': '分层优化方案、关键对象清单与实施建议。',
        'project.owner': '王主任',
        'project.confirmStatus': '待确认',
        'input.site': '华北能源站',
        'input.assets': 'SCADA\nRTU\n防火墙\n交换机',
        'input.constraints': '老旧设备较多、网络连续性要求高',
        'zone.scope': '监控区与现场控制区',
        'zone.businessZone': '监控区',
        'zone.relatedAsset': 'SCADA',
        'zone.strategy': '单网扁平优化',
        'zone.boundary': '按监控层与现场层边界梳理',
        'zone.isolationNotes': '',
        'threat.source': '内部误操作与边界配置缺失',
        'threat.surface': '监控主机与边界设备',
        'threat.asset': 'SCADA 平台',
        'risk.level': '中',
        'risk.impact': '可能造成监控数据异常',
        'risk.priority': 'P2',
      },
      recordCollections: {
        'project-goal': [
          {
            'project.name': '能源站网络分层优化项目',
            'project.customer': '某能源企业',
            'project.industry': '能源电力',
            'project.scope': '单厂区',
            'project.goal': '升级扩展',
            'project.delivery': '分层优化方案、关键对象清单与实施建议。',
            'project.owner': '王主任',
            'project.confirmStatus': '待确认',
          },
        ],
        'business-description': [
          {
            'scene.name': '主站监控采集',
            'scene.mode': '周期通信',
            'scene.source': 'SCADA',
            'scene.target': 'RTU',
            'scene.purpose': '监控采集',
            'scene.medium': '有线',
            'scene.continuity': '高',
            'scene.note': '',
          },
        ],
        'scope-definition': [
          {
            'overview.name': '监控室与现场采集区',
            'overview.space': '单厂区 / 监控室 / 现场设备区',
            'overview.distribution': '集中监控 + 现场采集',
            'overview.cross': '少量跨区访问',
            'overview.scale': '中等规模',
            'overview.note': '',
          },
        ],
        'asset-allocation': [
          {
            'asset.name': 'SCADA-01',
            'asset.type': 'SCADA',
            'asset.system': '监控系统',
            'asset.location': '监控室',
            'asset.level': 'Level 3',
            'asset.status': '在用',
            'asset.access': '有线固定接入',
            'asset.criticality': '高',
            'asset.note': '',
          },
        ],
        'environment-conditions': [
          {
            'env.topic': '能源站监控环境',
            'env.interference': '中等电磁干扰',
            'env.install': '监控室与现场混合部署',
            'env.distance': '监控室到现场设备区 200m',
            'env.medium': '工业以太网',
            'env.power': '稳定交流供电',
            'env.wireless': '少量无线巡检',
            'env.note': '',
          },
        ],
        'security-scenario': [
          {
            'secScenario.name': '监控与现场跨层访问',
            'secScenario.type': '跨层访问',
            'secScenario.scope': 'SCADA 与 RTU',
            'secScenario.remote': '无',
            'secScenario.external': '无',
            'secScenario.note': '',
          },
        ],
        'exposure-analysis': [
          {
            'secExposure.name': 'SCADA-01',
            'secExposure.relatedScenario': '监控与现场跨层访问',
            'secExposure.type': '外部互联',
            'secExposure.source': '监控层到现场层通信',
            'secExposure.control': '访问控制列表 + 边界审计',
            'secExposure.risk': '中',
            'secExposure.note': '',
          },
        ],
        'consequence-analysis': [
          {
            'secConsequence.name': 'SCADA-01',
            'secConsequence.relatedScenario': '监控与现场跨层访问',
            'secConsequence.type': '数据中断',
            'secConsequence.impact': '监控数据采集中断或误报',
            'secConsequence.severity': '中',
            'secConsequence.recovery': '20 分钟内恢复',
            'secConsequence.note': '',
          },
        ],
        'baseline-check': [
          {
            'secBaseline.type': '日志审计',
            'secBaseline.object': 'SCADA-01',
            'secBaseline.status': '部分具备',
            'secBaseline.evidence': '主机审计开启，边界日志未统一',
            'secBaseline.gap': '存在缺口',
            'secBaseline.note': '',
          },
        ],
        'key-asset-analysis': [
          {
            'secKey.name': 'SCADA-01',
            'secKey.type': '监控系统',
            'secKey.reason': '承载主站监控与现场采集',
            'secKey.focus': '边界配置、日志审计、采集连续性',
            'secKey.priority': '高',
            'secKey.note': '',
          },
        ],
        'design-principles': [
          {
            'principle.category': '网络结构思路',
            'principle.main': '优先保持现网连续性并清晰层级边界',
            'principle.scope': '监控室与现场采集区',
            'principle.basis': '老旧设备多且连续性要求高',
            'principle.desc': '先梳理边界，再逐步优化分层结构',
            'principle.note': '',
          },
        ],
        'network-topology': [
          {
            'topology.object': '能源站监控主干',
            'topology.type': '树型',
            'topology.backbone': '监控室主干交换机',
            'topology.access': '现场 RTU 分支接入',
            'topology.scope': '监控室与现场设备区',
            'topology.basis': '继承现网并便于扩容',
            'topology.tech': '工业以太网',
            'topology.note': '',
          },
        ],
        'layer-design': [
          {
            'layer.object': '监控与采集层',
            'layer.mode': '二层',
            'layer.structure': '监控层 / 采集层',
            'layer.policy': '控制广播域并预留后续三层演进空间',
            'layer.scope': '能源站单厂区',
            'layer.note': '',
          },
        ],
        'segmentation-plan': [
          {
            'seg.object': 'SCADA 监控网段',
            'seg.purpose': '监控采集',
            'seg.range': '172.16.30.0/24',
            'seg.margin': '预留 20%',
            'seg.note': '',
          },
        ],
        'performance-design': [
          {
            'performance.object': 'SCADA 采集链路',
            'performance.latency': '秒级',
            'performance.bandwidth': '百兆',
            'performance.clock': '1s 采样周期',
            'performance.measure': '监控与巡检流量分开',
            'performance.service': '监控采集',
            'performance.delay': '≤1s',
            'performance.risk': '无线巡检占用接入带宽',
            'performance.note': '',
          },
        ],
        'stability-design': [
          {
            'stability.object': '监控采集网络',
            'stability.target': '监控数据连续可见',
            'stability.risk': '老旧交换机稳定性不足',
            'stability.measure': '逐步替换并分区维护',
            'stability.control': '链路告警与巡检制度',
            'stability.maintain': '月度维护复盘',
            'stability.note': '',
          },
        ],
        'redundancy-design': [
          {
            'redundancy.object': '监控主机上联',
            'redundancy.target': '采集不中断',
            'redundancy.mode': '主备',
            'redundancy.switch': '人工切换预案',
            'redundancy.note': '',
          },
        ],
        'access-design': [
          {
            'access.object': 'SCADA-01',
            'access.type': '有线',
            'access.scope': '监控室网络',
            'access.limit': '现场侧通过汇聚交换机接入',
            'access.reason': '保持现网连续性',
            'access.note': '',
          },
        ],
        'selection-design': [
          {
            'selection.object': 'SCADA-01',
            'selection.demand': '监控采集',
            'selection.capability': '日志审计、告警联动',
            'selection.result': '监控主机 + 汇聚交换机优化',
            'selection.reason': '兼顾现网继承与稳定性',
            'selection.note': '',
          },
        ],
        'deployment-design': [
          {
            'deployment.object': 'SCADA-01',
            'deployment.location': '监控室',
            'deployment.install': '机柜上架',
            'deployment.cabling': '工业以太网',
            'deployment.requirement': '巡检期避免中断采集',
            'deployment.note': '',
          },
        ],
        'link-design': [
          {
            'link.source': 'SCADA-01',
            'link.target': 'RTU',
            'link.scene': '主站监控采集',
            'link.type': '电口',
            'link.role': '采集链路',
            'link.redundant': '否',
            'link.sourceLocation': '监控室',
            'link.targetLocation': '现场设备区',
            'link.medium': '工业以太网 / 百兆',
            'link.note': '',
          },
        ],
        'conduit-design': [
          {
            'conduit.source': '监控区',
            'conduit.target': '现场控制区',
            'conduit.scene': '主站监控采集',
            'conduit.purpose': '数据采集',
            'conduit.direction': '双向',
            'conduit.medium': '有线',
            'conduit.control': '按采集白名单通信',
            'conduit.delay': '秒级',
            'conduit.criticality': '中',
            'conduit.note': '',
          },
        ],
        'interconnect-design': [
          {
            'interconnect.source': '监控区',
            'interconnect.target': '现场控制区',
            'interconnect.structure': '汇聚交换互联',
            'interconnect.boundary': '汇聚交换机-01',
            'interconnect.control': 'ACL 限制访问方向',
            'interconnect.note': '',
          },
        ],
        'tech-selection': [
          {
            'tech.name': '采集网络优化技术',
            'tech.category': '网络结构',
            'tech.technology': '工业以太网',
            'tech.scopeType': '对象',
            'tech.scopeTarget': 'SCADA-01',
            'tech.scopeNote': '',
            'tech.goal': '保证采集连续性',
            'tech.reason': '兼容现网设备',
            'tech.alternative': '无线专网',
            'tech.alternativeReason': '稳定性不足',
            'tech.constraint': '老旧交换机较多',
            'tech.confirmStatus': '待确认',
            'tech.note': '',
          },
        ],
        'security-limit': [
          {
            'secLimit.name': '巡检期不得中断采集',
            'secLimit.type': '运维限制',
            'secLimit.object': 'SCADA-01',
            'secLimit.required': '是',
            'secLimit.note': '',
          },
        ],
      },
    },
  ],
};
